### ISSUE TITLE
local file linking

### ISSUE THREAD

**Issue by dragonwocky** [notion-enhancer/desktop#121]
**problem**
this would allow for a more centralised user experience: everything can be managed from notion and relevant files can be directly referenced/edited.
provided you only needed the file locally, it would make things easier to e.g. edit a word doc and not have to download/reupload to notion every time.

**solution(s)**
1. ~~adding this as a new block variant with the /file command.~~
    - the enhancer cannot modify page content, only change how it appears.
    - even if it could in theory be done, this would cause issues for non-enhanced clients. 
2. adding a button to a callout with the file emoji selected as its icon to attempt to open that from the filesystem.
    - potential to be a confusing/annoying way of doing things.
    - example:
![image](https://user-images.githubusercontent.com/16874139/94340987-5b576980-0049-11eb-8fd0-376f11048a8c.png)

this idea is a work-in-progress and community feedback/ideas are welcome.

**Comment by Eldhrimer** [comment]
My 2 cents on this issue. I think we can make use of a category of deep enhancements that would break compatibility with non enhanced clients. Something like experimental features, with a nice big warning to alert the user of potential misbehaviors. With some toggle under core to enable or disable globally those modules. Like a #deepmod category (I don't really like the name thou). Mainly for hardcore users to power up their use of the app. Maybe with the official api we can expand on the concept, or maybe a separate app that communicates with the enhancer.

**Comment by dragonwocky** [comment]
@Eldhrimer that comment was still only theoretical anyway. As-is, because of the way Notion stores and renders content, the enhancer *cannot* reliably modify page contents without an API: after reloading or reopening the app blocks are (usually) either duplicated, deleted, or have their content messed up even in an enhancer client. Even with the API, custom block types will probably out of scope.

Experimental features aren't coming to non-dev builds. I don't have the time to work on a mod until I'm ready to build it properly.
