### ISSUE TITLE
make feature-modifying enhancements work on a per-page/per-db basis

### ISSUE THREAD

**Issue by dragonwocky** [notion-enhancer/desktop#159]
~~**bypass preview**~~
~~* global default.~~
~~* option under the 3 dots.~~

**property layout**
* global default.
* save state (hidden/visible).

**word counter**
* global default.
* option under 3 dots.

**Comment by dragonwocky** [comment]
this is a master-discussion for requests like https://github.com/dragonwocky/notion-enhancer/issues/144 and https://github.com/dragonwocky/notion-enhancer/issues/158

**Comment by a13ph** [comment]
I guess this would also make it possible to handle keyboard shortcuts to toggle those options

**Comment by dragonwocky** [comment]
better solution for word-counter: display it in a sidebar that can be toggled.
![image](https://user-images.githubusercontent.com/16874139/137678966-4944564d-c56a-457a-a573-d6682331a708.png)

property layout will remember whether it was last opened/closed per-page in v0.11.0.
