### ISSUE TITLE
Emojis In Page Path

### ISSUE THREAD

**Issue by Soft-Bred** [notion-enhancer/desktop#185]
**describe the bug**
Emojis In the Page Path only show that of which page was opened first
This only happens with pages inside another page.

**expected behaviour**
The emoji should be shown respective to the page opened

**platform**
Windows 10

![One](https://user-images.githubusercontent.com/60551230/97801245-271c2d80-1c33-11eb-917a-37019c35c574.png)
![Two](https://user-images.githubusercontent.com/60551230/97801249-284d5a80-1c33-11eb-9087-c6e067d0ce3b.png)

**Comment by a13ph** [comment]
I observe similar or same bug with tab icons, but not with path navigation icons.

**Comment by dragonwocky** [comment]
This only happens if the emoji sets extension is enabled, right?
