### ISSUE TITLE
improvements for the tabs feature

### ISSUE THREAD

**Issue by dragonwocky** [notion-enhancer/desktop#186]
original issue: https://github.com/dragonwocky/notion-enhancer/issues/84

moved here for easier tracking of what could still be done after initial release.

* pinned tabs: maybe?
* change tab size: use `font_heading3-size` variable? (as that defaults to the same size as tabs currently are.)
* drag a tab out as its own window: would be nice for full parity with other tab systems, but is difficult to detect.

**Comment by Anahkiasen** [comment]
I'd also like an option to hide the tab bar if only one tab is opened, unless that's possible already currently? Didn't find it

**Comment by dragonwocky** [comment]
@Anahkiasen not possible and not going to happen: hiding the tab bar breaks/loses functionality even if there's only one tab open.
I know on macOS Safari this happens, but that's because Safari has another bar at the top still with necessary buttons/inputs etc. Notion only has the one when tabs are enabled, and it's necessary for things like the minimise/maximise/close buttons, dragging tabs between windows and opening a new tab with the GUI.

**Comment by dragonwocky** [comment]
* closing rightmost tab focuses leftmost: change to focus next rightmost?
* shrink tabs instead of moving to second row?

**Comment by dragonwocky** [comment]
* focus mode extension integration: show only on hover.

**Comment by CloudHill** [comment]
- restore previously closed tab with a keyboard shortcut (Ctrl + Shift + T)

**Comment by admiraldus** [comment]
- side by side view.

**Comment by dragonwocky** [comment]
@admiraldus if you want side by side, open the page in a second window.

**Comment by livejamie** [comment]
> @Anahkiasen not possible already and not going to happen: hiding the tab bar breaks/loses functionality even if there's only one tab open.
> I know on macOS Safari this happens, but that's because Safari has another bar at the top still with necessary buttons/inputs etc. Notion only has the one when tabs are enabled, and it's necessary for things like the minimise/maximise/close buttons, dragging tabs between windows and opening a new tab with the GUI.

When I asked in #246 for the option to hide the tab bar when there's only one tab I was told that it was already planned and pointed me to this ticket but from this comment, it seems like you're saying it's not possible?

**Comment by dragonwocky** [comment]
@livejamie it's possible to the tabs go invisible as part of focus mode, that is planned, but the bar itself will still be there and moving the mouse near will make them appear again. no layout-shifted changes are possible.

**Comment by mrdeevid** [comment]
I'd like a way to directly open a new tab when clicking on a page-link. I know the middle mouse click is not considered because it already has a function in Notion. But maybe with an accompanied shift-press or something like that? Or ctrl+mouse click just like in Microsoft Office to open links? I don't know if that's possible.

**Comment by Davoleo** [comment]
it's a small thing but I guess I'll post it here
I've noticed the window title is missing the current selected View in Database Pages and only shows the page name
It'd be cool if you could bring it back 
Page:
![image](https://user-images.githubusercontent.com/24458276/113180181-b9f7dd00-9250-11eb-9ee3-3daae4643edc.png)

Tab plugin disabled:
![image](https://user-images.githubusercontent.com/24458276/113180264-d3992480-9250-11eb-9647-9df68288c8e3.png)

Tab plugin enabled (same page - same view): 
![image](https://user-images.githubusercontent.com/24458276/113180368-f3c8e380-9250-11eb-88cc-08de80cb7702.png)

Same thing for the actual tab name of course:
![image](https://user-images.githubusercontent.com/24458276/113180461-0d6a2b00-9251-11eb-948e-957a0f8a0974.png)

**Comment by dragonwocky** [comment]
marking this as awaiting release - not actually fully ready yet but here's quick overview of how the stuff here will be implemented, so I don't need to keep re-reading the whole thread:

- pinned tabs: no, but there will an option to re-open last used tabs on launch.
- tab sizing: different tab styles will become available, including a "compact" mode.
- hiding tabs: through the focus mode extension, tabs will be transparent (but still take up physical screen space) unless hovered over.
- tab shrinking: tabs will auto shrink/expand to take up available space instead of wrapping to a second line.
- restore prev tab with shortcut: yes.
- open new tabs via ctrl+click: yes.
- better tab name/icon detection + display (to fix what @Davoleo brought up.)
