### ISSUE TITLE
Keyboard shortcuts broken after latest update

### ISSUE THREAD

**Issue by DanTheDane** [notion-enhancer/desktop#191]
FILL OUT THIS TEMPLATE, REMOVING/REPLACING EVERYTHING HERE WITH YOUR OWN INFORMATION.
BE AS CLEAR AND CONCISE AS POSSIBLE.

**describe the bug**
Several keyboard shortcuts are broken, e.g. Cmd+Q doesn't work, Alt+E doesn't work etc.
A few does seem to work like Cmd+1

Tried to re-install both Notion and notion-enhancer, with cleared .notion-enhancer folder in home folder.

**expected behaviour**
That default shortcut works

**platform**
macOS, Notion 2.0.8, Notion-enhancer 0.10

**Comment by conigs** [comment]
Just adding my comment to say that I get the same behavior.
Notion v2.0.8
notion-enhancer v0.1.0
macOS 10.15.6

**Comment by DanTheDane** [comment]
Found out it's the new tabs feature which causes this. If I disable tabs and restart, shortcuts works again

**Comment by bangarangler** [comment]
Not sure it's related however fresh install on linux out of the box shortcuts Alt+E broken -> can't open enhancer window to save my life on linux. : ) good luck all.  Can't wait to use this *thumbs up*

**Comment by fcherman** [comment]
`Alt (OPT)+E` works for me but the new-tab shortcut `CMD+T`does not. 

MacOS 10.11.6 (yeah, I know)
Notion v2.0.8
notion-enhancer v0.10.0

**Comment by Jacob3075** [comment]
Just installed notion and notion-enhancer and `Alt+E`, `Ctrl+T` are not working, `Ctrl+W` and `Ctrl+Q` works tho. I removed tabs but it didn't change anything. 

Using Notion from jaredallard/notion-app v1.0.5
Elementary OS 5.1.7 Hera
notion-enhancer v0.10.0

**Comment by CharlieDixon** [comment]
Same here. Running on Windows 10 Pro N and Alt+E brings up a mini blank white window with a loading icon that never stops. 
![image](https://user-images.githubusercontent.com/58493339/99261904-37c4ca00-2815-11eb-94c4-dfd9a91fadec.png)

**Comment by CharlieDixon** [comment]
Nevermind, should have read more carefully. Fix coming out for this soon apparently: 
![image](https://user-images.githubusercontent.com/58493339/99262114-7bb7cf00-2815-11eb-8960-1e6846de2bb6.png)
