### ISSUE TITLE
Tabs title only "notion.so" - not title of page on Mac

### ISSUE THREAD

**Issue by eggplantsplz** [notion-enhancer/desktop#196]
FILL OUT THIS TEMPLATE, REMOVING/REPLACING EVERYTHING HERE WITH YOUR OWN INFORMATION.
BE AS CLEAR AND CONCISE AS POSSIBLE.

**describe the bug**
what is the bug - what happens?
as per title. No specified title names - only "notion.so"

**expected behaviour**
why is this a bug - what should be happening?
should be name of page please!

**screenshots**
if applicable, add screenshots of your problem.
<img width="281" alt="image" src="https://user-images.githubusercontent.com/23745768/97925978-307ec600-1d17-11eb-818b-5654552a0891.png">

**platform**
what OS are you using? e.g. windows 7, windows 10, WSL, ubuntu, arch linux, macOS

macOS (latesT). notion (latest). enhancer (latest)

**Comment by elky84** [comment]
![image](https://user-images.githubusercontent.com/4001940/98125759-2962de00-1ef8-11eb-9dc2-8ceca31ff713.png)

I have the same symptoms.
Attach Dev-Tools console log.

**Comment by fabiosangregorio** [comment]
Sometimes this happens to me too. I'm on Windows 10 (english/italian)
