### ISSUE TITLE
Use a packager to make installation & distribution easier

### ISSUE THREAD

**Issue by justjake** [notion-enhancer/desktop#206]
**problem**
Installing `notion-enhancer` is difficult for end-users. Currently the installation requires several rather technical steps:

1. Installing `nodejs` via some package. For linux, this is okay, but on mac and windows, this requires futzing with installer files or learning about `brew`
1. Use the command line to `npm install notion-enhancer`. This requires learning about the command line, and dealing with permissions or hidden dependency problems on mac and windows.
1. Run the `notion-enhancer` tool from the command line. For this to work, there can't have been a weird `npm` issue with (2) or a PATH/environment issue with (1).

Y'all might also want to consider using a packer to make distribution easier: something that takes the project dependencies and combines it into a single executable file. I haven't used it much, but vercel/pkg seems nice (https://github.com/vercel/pkg). That way you can provide a very easy install workflow that is more ore less just 1. download the binary from github release page, 2. run ./Downloads/notion-enhancer apply. Walking non-developers through the whole node install flow, etc, is asking for pain for everyone involved

**solution**
This could be simplified by using a packaging tool at build time that combines the `notion-enhancer` source code, it's `node_modules` and other dependent files, and a `nodejs` interpreter into a single file.

There are several packaging tools out there for `nodejs`. For example, https://github.com/vercel/pkg.

When performing a new release, upload a built `notion-enhancer` binary for each supported platform to the Github release page.

If this project used a packer, the install instructions would become:

1. Download the release CLI program from the releases page.
2. Run `~/Downloads/notion-enhancer apply`.

**Comment by davidbailey00** [comment]
For Debian-based and RPM-based Linux distributions, pre-enhanced packages are now available from [notion-linux](https://github.com/davidbailey00/notion-linux). See also: #321, #412

**Comment by dragonwocky** [comment]
marking this as solved by notion-repackaged.

notion-repackaged is an easy one-step installer, installations with finer control will remain the more technical route of installing via npm -- if you want to do it manually, you'll have to do it manually. i expect manual installations to be usually only done in development environments, so those users would want/already have nodejs installed anyway.

packaging and distributing the cli as an executable would at this point just end up being a 3rd way of using the enhancer that would probably create more confusion than it would simplicity.
