### ISSUE TITLE
table row lines

### ISSUE THREAD

**Issue by admiraldus** [notion-enhancer/desktop#234]
_firstly, english is not my native language. so, if you see something wrong or unfamiliar and weird sentences, sorry for that!_

**describe the bug**
actually, expected thing is all table rows must be have bottom lines. at least, table rows in default **notion** have it. but table rows in **notion _with notion enhancer_** does not have it.

**expected behaviour**
as i said, all table rows must be have bottom lines. this is default design of **notion**. but some bottom lines disappear when I switch to **notion enhancer**. first, i thought it was because of a module but hell no. this bug is valid even if all enhancements are disabled.

**screenshots**
default **notion**:
![default](https://user-images.githubusercontent.com/31805948/98481301-5b32b800-220a-11eb-939b-d2e6e04d845f.png)

enhanced **notion**:
![enhanced](https://user-images.githubusercontent.com/31805948/98481346-9b923600-220a-11eb-9c5a-ae130927cd50.png)
also column lines are unaligned too!

**platform**
`windows 10` and `notion-enhancer/0.10.0 win32-x64 node-v12.16.2`

**Comment by KeerthiNaathan** [comment]
Yea, for last 2 days I also Facing this issue. 

Here Windows 10.

**Comment by kursorbyte** [comment]
It also seems like the top border of calendars is also missing.
![Screenshot 2020-11-13 091808](https://user-images.githubusercontent.com/74338929/99081716-3a16f200-2591-11eb-9027-a82b928cfee3.png)

**Comment by Ludoal** [comment]
Same for me on Table view, Calendar view seems ok though.

Windows 10, Notion-Enhancer 0.10.0 and dev branch.

**Comment by axegirll** [comment]
Same for me as well. Mac.

**Comment by kursorbyte** [comment]
> Same for me on Table view, Calendar view seems ok though.
> 
> Windows 10, Notion-Enhancer 0.10.0 and dev branch.

Sorry, I wasn't clear enough. The inline calendar only exhibits this issue.

**Comment by hdaasari** [comment]
+1
