### ISSUE TITLE
color mismatch in reminder clock and reminder text

### ISSUE THREAD

**Issue by admiraldus** [notion-enhancer/desktop#243]
_firstly, english is not my native language. so, if you see something wrong or unfamiliar and weird sentences, sorry for that!_

**describe the bug**
i changed the color of the code inline text, which also changed the color of the reminder text. but it does not change the color of the reminder clock. now, i have a color mismatch.

**expected behaviour**
i think the color of the reminder clock should also change.

**screenshots**
**code inline text**
![image](https://user-images.githubusercontent.com/31805948/98808160-c65bd480-242c-11eb-923e-aa6557ffc00b.png)

**reminder**
![image](https://user-images.githubusercontent.com/31805948/98808251-da9fd180-242c-11eb-927a-3be46ce9ed4f.png)

**platform**
`windows 10` and `notion-enhancer/0.10.0 win32-x64 node-v12.16.2`

**Comment by dragonwocky** [comment]
hadn't noticed that! i've created a separate variable for reminders (will push my changes soon, but holding off since they'll break everything else)
