### ISSUE TITLE
Outline Panel

### ISSUE THREAD

**Issue by kursorbyte** [notion-enhancer/desktop#252]
FILL OUT THIS TEMPLATE, REMOVING/REPLACING EVERYTHING HERE WITH YOUR OWN INFORMATION.
BE AS CLEAR AND CONCISE AS POSSIBLE.

**problem**
Sometimes, a user may want to locate a specific topic on a long page and would have to either scroll through or use the find function to locate their objective block. Having a collapsible side panel that outlines a page according to header sizes will make navigating long pages much easier. The outline panel would always be in view unlike using Notion's own table of contents block.
It also allows the user to visually see different concepts of a page and the hierarchy of topics (parent topics, subtopics, etc.).
![Outline](https://user-images.githubusercontent.com/74338929/98978241-adfcc000-24e7-11eb-9c68-bad93e08def6.png)

**solution**
Ideally, there would be a pane on the right side that can be collapsed and opened so it can be called upon when necessary and won't pose as something taking up more space. 
Items in the outline panel would be clickable and would jump to the respective block when clicked.

**alternatives (optional)**
This has been done with a chrome web extension (https://chrome.google.com/webstore/detail/notion-boost/eciepnnimnjaojlkcpdpcgbfkpcagahd) by Gourav Goyal, and it would be interesting to see it be ported over to the desktop app.

**Comment by admiraldus** [comment]
i want this!
