### ISSUE TITLE
[Notion Themes] - Decreasing opacity in every new line

### ISSUE THREAD

**Issue by danmecj** [notion-enhancer/desktop#259]
**Problem**
So after using notion-enhancer after some time, I'm a big fan of the different types of themes that are available for use. However, one thing that looks a tad bit annoying as a part of those themes is that for every new line, the "_Type '/' for commands_" text is not as transparent as it can be. And the problem with this is that since the _text_  is as opaque as any text you type on a page, it's difficult to differentiate what text you're writing and what text isn't yours. The theme I'm using that has this is the Darcula theme.

Attached is an example of how it looks **vs** how the original looks.
<img width="223" alt="Screenshot 2020-11-15 at 2 15 18 PM" src="https://user-images.githubusercontent.com/4606555/99178331-fff24f80-274c-11eb-9e73-5d805ad5adec.png">

![Screenshot 2020-11-15 at 2 15 41 PM](https://user-images.githubusercontent.com/4606555/99178336-0da7d500-274d-11eb-945d-b7279146f8cf.png)

**Solution**
Perhaps a solution to this is to reduce the opacity of the _text_ ("_Type '/' for commands_") to ensure it's the same as the original  when you access the Notion app/website.

**Alternatives (optional)**
I have not tried this myself because I haven't a single clue on how to manipulate themes and if I knew how to I would do it first thing.

**Comment by dragonwocky** [comment]
Please list which themes this occurs on, as I know it doesn't for all of them.

**Comment by danmecj** [comment]
This occurs on the **_Dracula_** theme (dracula v0.1.0).

**Comment by dragonwocky** [comment]
Any others? In future, please be clearer in any bug reports / feature requests - you made it sound like this was a problem common to all themes, as opposed to a lack of contrast in just one.

**Comment by danmecj** [comment]
I apologise. I tolally understand how I seem to have generalised everything and I'll work on the clarity and being more specific in the future. Thanks for pointing that out. The one other theme I've noticed that had a similar issue is the **material ocean** theme.
