### ISSUE TITLE
Make enhancer switches style the same as Notion's 

### ISSUE THREAD

**Issue by fabiosangregorio** [notion-enhancer/desktop#261]
**problem**
For a more consistent and integrated look, it would be great if the switches on the enhancer's menu looked the same as the one from Notion's app. You can see a comparison below:

![](https://i.imgur.com/fnVFtSu.png)

**alternatives (optional)**
At least add some sort of shadow to the buttons, because (at least on light theme) they're missing depth right now.

**Comment by admiraldus** [comment]
that would be great!
