### ISSUE TITLE
Emoji Sets Not Working With Tabs 

### ISSUE THREAD

**Issue by Soft-Bred** [notion-enhancer/desktop#265]
Emojis do not appear on the tabs when using the Emoji Sets extension

Emojis should be visible in tab names when using the extension

![1](https://user-images.githubusercontent.com/60551230/99301723-4aa3c280-2846-11eb-9634-e01f2809244c.png)
![2](https://user-images.githubusercontent.com/60551230/99301729-4b3c5900-2846-11eb-8a6d-55eb05f09adc.png)

Windows 10

**Comment by dragonwocky** [comment]
related to #266
