### ISSUE TITLE
Indentation/relationship lines for To-do, Toggle and Numbered Lists.

### ISSUE THREAD

**Issue by fourteen-1** [notion-enhancer/desktop#277]
**problem**

Hard to navigate lists with indentations on many levels. Relationship lines make it easier to be in grasp of what connects to what.

**solution**
This feature is in works or has already been implemented for Bullet point Lists. [pull99](https://github.com/notion-enhancer/notion-enhancer/pull/199)

I think it should be able to be achieved for the other types of lists as well.

**Comment by dragonwocky** [comment]
this also already works for numbered lists.

**Comment by fourteen-1** [comment]
> 
> 
> this also already works for numbered lists.

Right. Consider it for the other two types of lists then, please. 

Thanks!
