### ISSUE TITLE
Responsive mode: give possiblity to set "width to wrap columns at" in percentage

### ISSUE THREAD

**Issue by fabiosangregorio** [notion-enhancer/desktop#288]
**problem**
Hi dragon, I love the responsive feature, it has been a life saver. **I always use it to trigger on half the display width**. 
Though, I often use notion on my Surface attached to a big 2k screen. I set responsive mode to trigger at half the size of my 2k screen, calculating the width in pixels. But when I detach the surface from the screen, the responsive mode always triggers even with width higher than half the screen. On the other way, if I set it to trigger on half the width on my surface, it almost never gets triggered on the 2k screen.

**solution**
Would it be possible to give the possibility to the user to set the responsive width in percentage (relative to the screen width), instead of pixels? That way I could always set it to 50% no matter what the screen width.

**Comment by dragonwocky** [comment]
![image](https://user-images.githubusercontent.com/16874139/136680469-684311b6-5b8f-4d50-ba37-78632fb689fc.png)
