### ISSUE TITLE
Global linking blocks

### ISSUE THREAD

**Issue by haroldsnyers** [notion-enhancer/desktop#294]
**problem**
When copying a link of a block, if we paste it on another page, we will just get a link to that page (maybe if to that block). What I want is an additional button that enable us to copy the global link of a block? 

What is a global link? It's a block that can be shown on multiple pages and when modified, it will be reflected on all the pages that contains that global linking block. 

For now the solution is to copy the link block URL (https://www.notion.so/<url_to_remove>#<id_to_keep>). And then remove everything between the "www.notion.so/" and the # (including the #). Thus the new URL will be https://www.notion.so/<id_block>. Now we can copy this URL and then past it using ctrl+maj+v, then click on link page. This way, it gives the preview of the block and not just the link.

**solution**
I think the best way to implement this would be to add a button under "copy link" of the block. This button would take the same argument as the copy link and just apply a regex filter (`^https://.*\#` with substitution https://www.notion.so/) on it. For the last part when pasting the link as preview, I don't know if there is a way to bypass that we need to use maj to past it. However having that URL directly available would be a great plus.

**Comment by admiraldus** [comment]
i'm developing a module for this, don't worry.

**Comment by alyssasmith0328** [comment]
@admiraldus this would be soo nifty! thank you!

**Comment by admiraldus** [comment]
> > i'm developing a module for this, don't worry.
> 
> Oh nice, good to know, was on the brink of trying to implement it myself.



> @admiraldus this would be soo nifty! thank you!

what do you think about this?
![GIF](https://i.imgur.com/lJSMyI3.gif)
![GIF](https://i.imgur.com/f4FIFMW.gif)

**Comment by snihar2** [comment]
> > > i'm developing a module for this, don't worry.
> > 
> > 
> > Oh nice, good to know, was on the brink of trying to implement it myself.
> 
> > @admiraldus this would be soo nifty! thank you!
> 
> what do you think about this?
> ![GIF](https://camo.githubusercontent.com/e643dcd3b280568dcc1e70948d67438e14371aabf3dc3cfacc84cd5dccd09ee5/68747470733a2f2f692e696d6775722e636f6d2f6c4a534d7949332e676966)
> ![GIF](https://camo.githubusercontent.com/85b1043ff0e639f3f8384a2aafc96b40cc45aab98132ba1bfca13735058b13ac/68747470733a2f2f692e696d6775722e636f6d2f66344649464d572e676966)

Hey, seems perfect! I see you thought about global links for pages and blocks which awesome! Can't wait for the release!

**Comment by admiraldus** [comment]
> > > > i'm developing a module for this, don't worry.
> > > 
> > > 
> > > Oh nice, good to know, was on the brink of trying to implement it myself.
> > 
> > 
> > > @admiraldus this would be soo nifty! thank you!
> > 
> > 
> > what do you think about this?
> > ![GIF](https://camo.githubusercontent.com/e643dcd3b280568dcc1e70948d67438e14371aabf3dc3cfacc84cd5dccd09ee5/68747470733a2f2f692e696d6775722e636f6d2f6c4a534d7949332e676966)
> > ![GIF](https://camo.githubusercontent.com/85b1043ff0e639f3f8384a2aafc96b40cc45aab98132ba1bfca13735058b13ac/68747470733a2f2f692e696d6775722e636f6d2f66344649464d572e676966)
> 
> Hey, seems perfect! I see you thought about global links for pages and blocks which awesome! Can't wait for the release!

https://github.com/notion-enhancer/notion-enhancer/pull/345
