### ISSUE TITLE
Togglable headers

### ISSUE THREAD

**Issue by MedBlueprint** [notion-enhancer/desktop#317]
I like to outline my documents using headers, but the only thing keeps me away from using headers is it's inability to toggle, making the documents way longer and needless to say, less neat.

If the headers can be toggled like usual > followed by space notion toggles, then it would be of tremendous help for students, researchers and others who use notion to maintain long text documents. 

Also, the new "OUTLINER" add-on by cloudhill will turn into a more handy tool as well.

**Comment by dragonwocky** [comment]
already wip by @CloudHill 

![](https://media.discordapp.net/attachments/748162550910287922/782213882205700096/collapsible.gif)

**Comment by MedBlueprint** [comment]
As a medical student with zero coding knowledge, I'm really overwhelmed by the contribution of you guys❤
Thanks a Ton!

**Comment by MedBlueprint** [comment]
Also, I hope to see a chrome extension, maybe when you guys can manage more time.. as the notion desktop app gets really sluggish after opening a few tabs :(

The speed of web interface is still way ahead if the desktop app too.

**Comment by dragonwocky** [comment]
@MedBlueprint one is planned, but see https://github.com/notion-enhancer/notion-enhancer/issues/316#issuecomment-739149142

**Comment by snihar2** [comment]
I know it's not directly related to this issues but if you could implement this, I wonder what other applications could be taken out it but would need notion developers. 

You see when you have global blocks, only the indented text underneath is taken with that global block text you took. Here however if you could have toggable headers, it would eventually mean that you are able to see which blocks correspond to the header you are toggling. Imagine now global blocks that take all the blocks that correspond to a header

**Comment by dragonwocky** [comment]
@snihar2 this works by selecting all blocks between 2 headers and adding some extra interactivity. It can't be applied to global blocks - Notion only loads the content of an individual block when it's embedded, so there's no context to infer other blocks/headers from. To be able to do what you're suggesting, we need a way of customising Notion's internal data store format and parsing so we can add custom blocks - which I unfortunately can't see happening.

**Comment by Jkker** [comment]
> already wip by @CloudHill
> 
> ![collapsible](https://user-images.githubusercontent.com/16874139/101241677-7088fc80-374c-11eb-835a-b024f2d90865.gif)

Any follow-up to the progress? @CloudHill

**Comment by CloudHill** [comment]
@Jkker it's already available in the dev build, so you can expect it in the next enhancer update
