### ISSUE TITLE
An option to select a font family for headings (h1, h2, h3) only

### ISSUE THREAD

**Issue by b4nn** [notion-enhancer/desktop#318]
**problem**

This feature would allow users to improve readability and aesthetic of Notion. Selecting a font family for headings that is different from body text and rest of UI, helps with legibility by making the headings stand out more. From the visual perspective, using two font families is a staple of beautiful and original designs.

**solution**

In font chooser addon, implement a new field for headings (h1, h2, h3). For usability sake a single field should be enough i.e. selected font applies to all heading styles, as opposed to having an option to select a different font for each heading size.

**Comment by admiraldus** [comment]
if @dragonwocky approves this, i can add the feature you want to font chooser module.
