### ISSUE TITLE
mod menu redesign

### ISSUE THREAD

**Issue by dragonwocky** [notion-enhancer/desktop#325]
this issue is for tracking the visual redesign of the mod menu. i will add some diagrams and mockups soon, but want to test a few things first so i can confirm which functionality is being implemented.

the basic rundown is that the ui elements aren't going to change much, but the layout will significantly - it'll be more designed to work with a bigger window (although when shrunk it can collapse back into something similar to the current).

general-layout-wise, there'll be a few different views for mods to replace the current tag filtering (e.g. all, enabled, disabled, downloaded, online, updates, only-if-this-tag). a search bar will be present beneath those view tabs that when focused goes into a "search all mods regardless of view" mode.

the mods themselves will still be much the same in the card-with-options-beneath form, so things can easily be configured without having to go through submenus etc. - they might be laid out in a masonry grid style (though that might negatively affect mod re-ordering and sizing).

each mod might also need a preview image above the title (e.g. a screenshot or colour palette of a theme) and a download/delete/update button. then in the top-right of the menu would be a switch to go into re-order mode and a switch to hide those preview images.

additionally each mod could have its documentation viewed - this would be sourced from a markdown file and would document json formats for the icons mod or have more pictures etc. not sure yet whether this would work better as a tab beneath the mod (e.g. to be swapped with the options) or something that would be in a sidebar on the right and would be viewed based on the currently selected/last clicked mod.

it needs some work in terms of making sure that it's still user friendly to reorder & browse everything (e.g. minimal clicks are required, things look good), but that's an outline of what's functionally required.

**Comment by MedBlueprint** [comment]
a friendly suggestion: is there a possibility to a have a full page view of mod menu that's presented in ### **Kanban style?**
i.e: All the mods categorized under 4-5 columns(something like enhancer-core, Tabs, Themes, Tweaks, Custom inserts)

That would be super friendly way for a user to find the mods under expected Column :)

**Comment by MedBlueprint** [comment]
a friendly suggestion: is there a possibility to a have a full page view of mod menu that's presented in  
### Kanban style?


i.e: All the mods categorized under 4-5 columns(something like enhancer-core, Tabs, Themes, Tweaks, Custom inserts)

That would be super friendly way for a user to find the mods under expected Column :)

**Comment by dragonwocky** [comment]
@MedBlueprint there will not be a kanban view. most things are pretty unrelated or if you do try and relate them you end up finding that 1/2 of the extensions match that, so you either end up with 10 columns of 1 or 2 mods each or 3 columns with 10 mods in them. that's not very helpful or user friendly.

**Comment by dragonwocky** [comment]
![](https://cdn.discordapp.com/attachments/748162550910287922/786037940211286046/image0.jpg)

![](https://cdn.discordapp.com/attachments/748162550910287922/786037940517601310/image1.jpg)

![](https://cdn.discordapp.com/attachments/748162550910287922/786037940911341588/image2.jpg)

alerts can live inside the menu's update tab, but a numerical indicator will be present in the main app
