### ISSUE TITLE
'css insert' file path disappears

### ISSUE THREAD

**Issue by Ludoal** [notion-enhancer/desktop#340]
**describe the bug**
In the custom insert configuration, the file path to custom css sometimes disappear, reseting to 'choose a file...'

**platform**
windows 10

**Comment by dragonwocky** [comment]
@Ludoal if the file has been moved or deleted it may reset, could that be what's going on here?

**Comment by Ludoal** [comment]
> @Ludoal if the file has been moved or deleted it may reset, could that be what's going on here?

No, it has not moved, nor did I close the app.
My custom.css is in my Dropbox though, but this didn't happen with previous version of Notion (2.0.8) and Notion-Enhancer (0.10.1)

**Comment by dragonwocky** [comment]
nothing in the custom inserts extension changed in the update. unless a few others are also experiencing this I'm guessing it's a user issue (maybe it tries to access it while dropbox it syncing it and that breaks things?).

**Comment by Ludoal** [comment]
> nothing in the custom inserts extension changed in the update. unless a few others are also experiencing this I'm guessing it's a user issue (maybe it tries to access it while dropbox is syncing it and that breaks things?).

Yeah maybe...
I will put the file in a non synced folder and see if this issue persists.
But with happened multiple times since the new updates, and I did't change anything to my setup.

**Comment by BillionJothi** [comment]
I have the same issue with both the CSS inserts & the js insert. Files are on a local (non-sync folder). Only can verify issues exist in the latest version, (as didn't test/use this feature on previous ones)

**Comment by dragonwocky** [comment]
do any other options also reset randomly or is this specifically only the inserts?

**Comment by BillionJothi** [comment]
> do any other options also reset randomly or is this specifically only the inserts?

Just the inserts only. Unsure when it resets (randomly) - will have to pay more attention to see if it is active.

I suspect it potentially resets when Notion crashes (window does not appear back after minimised & relaunched) and goes unnoticed for some time before being caught - hence appearing random.

Will test this out when it happens again & confirm

**Comment by BillionJothi** [comment]
Hey, an update, have narrowed it down to when opening a new tab - the inserts are reset
