### ISSUE TITLE
Block dragger overlaps with indentation indicators

### ISSUE THREAD

**Issue by foxdoescode** [notion-enhancer/desktop#342]
**describe the bug**
Block dragger overlaps with indentation indicator lines.

**expected behaviour**
There should be a background or something to distinguish the layer.

**screenshots**
![image](https://user-images.githubusercontent.com/75043185/101896568-2dc58b00-3b77-11eb-9d55-d3f9903da6aa.png)

**Comment by dragonwocky** [comment]
![image](https://user-images.githubusercontent.com/16874139/137624933-a4e9280c-c6cc-4190-bf8c-3fc886df85a3.png)
