### ISSUE TITLE
list of missing variables / css

### ISSUE THREAD

**Issue by admiraldus** [notion-enhancer/desktop#352]
**describe the bug**
new variables have missing variables or css codes are not working as expected.

**expected behaviour**
some variables should be added or css codes should be expanded.

**screenshots**
###### no variable for future time reminder
![IMG](https://i.imgur.com/MnrWrSz.png)
###### unchangeable variables (always 1.5 and 1)
```
--theme_dark--text_block-line_height
--theme_dark--text_block-margin_top
```
###### danger button variables
![IMG](https://i.imgur.com/QdbGhKf.png)
don't work here.
![IMG](https://i.imgur.com/5Hia6ks.png)
but work here.
###### wrong bg color for almost all notion blocks
![IMG](https://i.imgur.com/cbE2B0F.png)
###### wrong colors for the account menu
![IMG](https://i.imgur.com/EQUKISu.png)
![IMG](https://i.imgur.com/EegeCHT.png)
![IMG](https://i.imgur.com/NlrzgbL.png)
###### wrong colors for the introduction process
![IMG](https://i.imgur.com/M6rB3BS.png)
###### the "heading2_size" variable also affects the bullet point
![IMG](https://i.imgur.com/0GZwnVW.png)
###### wrong colors for the sort menu buttons
![IMG](https://i.imgur.com/o5mQyWK.png)
###### 1.5 line height causes some alignment problems
![IMG](https://i.imgur.com/xrA9SEo.png)
###### wrong colors for the plan indicators
![IMG](https://i.imgur.com/wYhTQET.png)
![IMG](https://i.imgur.com/RxaS41m.png)
![IMG](https://i.imgur.com/yyURGre.png)

i'll let you know as i discover more bugs.

**platform**
`windows 10`

**Comment by admiraldus** [comment]
###### even if i change colors, they stay the same in the color selection menu
![IMG](https://i.imgur.com/UcHbfLR.png)

**Comment by dragonwocky** [comment]
these should all be fixed (plus some other bugs). a couple new variables have been created for them. let me know how that goes, if everything is working I'll close this issue.

**Comment by admiraldus** [comment]
> these should all be fixed (plus some other bugs). a couple new variables have been created for them. let me know how that goes, if everything is working I'll close this issue.

to my theory, if the variables handle the entire theme, when i make everything the same color, i shouldn't see anything but that color. so i did everything red for a powerful test. i made red EVERYTHING that contains color. and i discovered a few interesting bugs.

**here is a list of them:**
note: because of the color differences, i think you will understand the problem without me explaining in detail, but if further explanation is needed, please tell me...
###### change cover menu
![IMG](https://i.imgur.com/z7wyStn.png)
###### rich text tooltip
![IMG](https://i.imgur.com/Eb8vTzt.png)
###### icon select menu
![IMG](https://i.imgur.com/tasq9we.png)
###### "list view" (inline code)
![IMG](https://i.imgur.com/nsrl6Ht.png)
###### databases (shadow and border)
![IMG](https://i.imgur.com/O2oku2Y.png) (kanban)
![IMG](https://i.imgur.com/vzM0WxO.png) (timeline)
![IMG](https://i.imgur.com/dw8C1aZ.png) (gallery and yes, the "new+" button is in the hover state)
![IMG](https://i.imgur.com/BvVqG14.png) (calendar)
###### settings > upgrade > for teams & members
![IMG](https://i.imgur.com/r0IjazU.png)
###### settings > my connected apps (button hover state)
![IMG](https://i.imgur.com/cBBjnXJ.png)
###### blue circle checks
![IMG](https://i.imgur.com/vcOPPDW.png)
###### "with my team" page select menus
![IMG](https://i.imgur.com/uxJgrqw.png)
###### "with my team" invite vie email input border
![IMG](https://i.imgur.com/XNRHkQ7.png)
###### add comment mention tooltip
![IMG](https://i.imgur.com/w03549C.png)
###### add comment page link border bottom and hover state
![IMG](https://i.imgur.com/l19OEMU.png)
###### database entry preview properties border bottoms
![IMG](https://i.imgur.com/ySkLdX3.png)
this border bottom bug is global i guess
###### image hover state buttons
![IMG](https://i.imgur.com/P5MAxZi.png)
###### second layer danger button
![IMG](https://i.imgur.com/0T9rpEV.png)
###### add to private pages bottom arrow
![IMG](https://i.imgur.com/yjGOSCR.png)
![IMG](https://i.imgur.com/TN1R5qX.png)
use team trial
###### "untitled" placeholder
![IMG](https://i.imgur.com/P9YvbVV.png)
###### "you're editing a template" warn
![IMG](https://i.imgur.com/DNVjxap.png)
###### all updates > all (private indicator, colored texts, select tags)
![IMG](https://i.imgur.com/0FGCRHi.png)
![IMG](https://i.imgur.com/LAgmezb.png)
same as the updates tab (topbar) (colored callout)
![IMG](https://i.imgur.com/roArToF.png)
###### notion blocks
1. person mention
2. future reminder
3. bookmark block
4. audio block
5. file embed block
6. template block
7. whimsical block (icon)
![IMG](https://i.imgur.com/pjMG14y.png)
![IMG](https://i.imgur.com/3wRsLuF.png)
![IMG](https://i.imgur.com/Tre8O4u.png)
###### drag and drop, slide line (blocks and databases)
![IMG](https://i.imgur.com/Sy47owM.png)
![IMG](https://i.imgur.com/rAFjvPl.png)
![IMG](https://i.imgur.com/FoQ4oZ9.png)
###### "weird" sort buttons 🥴 
![GIF](https://i.imgur.com/2mJJ3JY.gif)
###### database sort button hover state (when a sort rule is added)
![IMG](https://i.imgur.com/TU13sTA.png)
###### "this page is in trash" warn
![IMG](https://i.imgur.com/CJh93Ec.png)
###### cover upload progress
![IMG](https://i.imgur.com/AHFPtSo.png)
---
also, as you can see, the shadows are not red and tooltips have a gray border. finally, there were 2 variables for the shadows in old variables and we were changing not only the shadow color but the direct css code of the shadow. this must come back because i'm not just changing the color.

these are what i've discovered so far, i'll let you know if i find more. i hope so many bugs didn't overwhelm you. yes there are a lot of them, but actually they are all simple.
