### ISSUE TITLE
[Feature Request] Emoji Only Tab Labels

### ISSUE THREAD

**Issue by mstites** [notion-enhancer/desktop#354]
Current:
![current](https://user-images.githubusercontent.com/26208921/102648985-757b8200-4136-11eb-9127-50d494837f3e.jpg)

Suggested:
![suggested](https://user-images.githubusercontent.com/26208921/102649004-7c09f980-4136-11eb-9c4f-08e6de19dd53.jpg)

This suggested implementation, in my opinion, would align better with the minimal aesthetic of many of the other feature implementations (e.g. hiding help, symbol only share, focus mode). This would also give users who are distracted by the flashing "notion.so" website when changing pages the option of using tabs without that distraction.

**Comment by ayush729p** [comment]
Nice Idea...... The emojis must work in the first place though which seems to be a hit and miss. (#323 )
