### ISSUE TITLE
Permissions issue with Big Sure/M1 Mac for notion-enhancer

### ISSUE THREAD

**Issue by rafaelosoto** [notion-enhancer/desktop#355]
Hi this is sort of a bug-request sort of a brute-force solution for people who just want to get it to work. 
i'm on latest big sur, installed Notion.app, then notion-enhancer. Post restart I get "you do not have permission to open this app. "Also got a traceback. 

after lots of searching this is the only think that worked, based on the error I am assuming that you guys are replacing the Notion.app/ contents and the signature becomes invalid

This is what worked to fix it for me 

codesign --force --deep --sign - /Applications/Notion.app

thanks for this tool I'm liking it so far

trace:

Process:               Notion [1005]
Path:                  /Applications/Notion.app/Contents/MacOS/Notion
Identifier:            Notion
Version:               ???
Code Type:             ARM-64 (Native)
Parent Process:        ??? [1]
Responsible:           Notion [1005]
User ID:               501

Date/Time:             2020-12-20 17:28:52.473 -0600
OS Version:            macOS 11.0 (20A2411)
Report Version:        12
Anonymous UUID:        FC84E640-DBD3-B716-5D67-5BE0642BE926

Time Awake Since Boot: 100 seconds

System Integrity Protection: disabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (Code Signature Invalid)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace CODESIGNING, Code 0x1

kernel messages:

VM Regions Near 0 (cr2):
--> 
    __TEXT                      10051c000-100544000    [  160K] r-x/r-x SM=COW  

Thread 0 Crashed:
0                                 	0x00000001005f5000 _dyld_start + 0

Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000000   x1: 0x0000000000000000   x2: 0x0000000000000000   x3: 0x0000000000000000
    x4: 0x0000000000000000   x5: 0x0000000000000000   x6: 0x0000000000000000   x7: 0x0000000000000000
    x8: 0x0000000000000000   x9: 0x0000000000000000  x10: 0x0000000000000000  x11: 0x0000000000000000
   x12: 0x0000000000000000  x13: 0x0000000000000000  x14: 0x0000000000000000  x15: 0x0000000000000000
   x16: 0x0000000000000000  x17: 0x0000000000000000  x18: 0x0000000000000000  x19: 0x0000000000000000
   x20: 0x0000000000000000  x21: 0x0000000000000000  x22: 0x0000000000000000  x23: 0x0000000000000000
   x24: 0x0000000000000000  x25: 0x0000000000000000  x26: 0x0000000000000000  x27: 0x0000000000000000
   x28: 0x0000000000000000   fp: 0x0000000000000000   lr: 0x0000000000000000
    sp: 0x000000016f8e3c18   pc: 0x00000001005f5000 cpsr: 0x00000000
   far: 0x0000000000000000  esr: 0x00000000

Binary Images:
       0x10051c000 -        0x100543fff + (0) <F0ACCEB1-F45A-3FCA-ADCF-B88AA9477865> 
       0x1005f4000 -        0x10066ffff + (832.7) <CEF98E93-9E7A-3C9B-BBC9-6FEC25BDCCDE> 

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 6286
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=960K resident=0K(0%) swapped_out_or_unallocated=960K(100%)
Writable regions: Total=8384K written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=8384K(100%)
 
                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
STACK GUARD                       56.0M        1 
Stack                             8176K        1 
__DATA                             240K        3 
__DATA_CONST                        48K        2 
__LINKEDIT                         320K        3 
__TEXT                             656K        2 
===========                     =======  ======= 
TOTAL                             65.2M       12 

Model: MacBookPro17,1, BootROM 6723.41.11, proc 8:4:4 processors, 16 GB, SMC 
Graphics: kHW_AppleM1Item, Apple M1, spdisplays_builtin
Memory Module: lp_ddr4
AirPort: spairport_wireless_card_type_airport_extreme, wl0: Sep 11 2020 18:25:33 version 18.20.222.10.7.8.97 FWID 01-17360706
Bluetooth: Version 8.0.0f2, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
PCI Card: Universal Audio Apollo x8p - HEXA, sppci_othermultimedia, Thunderbolt@4,0,0
USB Device: USB 3.1 Bus
USB Device: USB 3.1 Bus
USB Device: USB3.1 Hub
USB Device: StarTech DK30CH2DPPD
USB Device: USB3.1 Hub
USB Device: USB2.0 Hub
USB Device: USB2.0 Hub
USB Device: Kinesis Keyboard Hub
USB Device: USB Receiver
USB Device: Composite Device
USB Device: Ableton Push 2
USB Device: KeyLab mkII 49
USB Device: USB2.0 Hub
USB Device: HID to SPI Device
Thunderbolt Bus: MacBook Pro, Apple Inc., 0.0
Thunderbolt Device: Thunderbolt 3 Option Card, Universal Audio, Inc., 1, 29.3
Thunderbolt Bus: MacBook Pro, Apple Inc., 0.0

**describe the bug**
what is the bug - what happens?

**expected behaviour**
why is this a bug - what should be happening?

**screenshots**
if applicable, add screenshots of your problem.

**platform**
what OS are you using? e.g. windows 7, windows 10, WSL, ubuntu, arch linux, macOS

**Comment by dragonwocky** [comment]
thanks @rafaelosoto, if we can't find a better fix this might just have to be part of the installation instructions.

**Comment by erlingur** [comment]
@rafaelosoto thanks for the fix! I have the same issue on latest Big Sur.

**Comment by NorahSketch** [comment]
hi, i tried this solution but it did not work for me - it just returned this:
```
/Applications/Notion.app: replacing existing signature
/Applications/Notion.app: resource fork, Finder information, or similar detritus not allowed
```
and notion still sends the same error.

**Comment by dragonwocky** [comment]
@NorahSketch if you've browsed the files with the Finder app then it's possible that's preventing the codesigning. You might need to uninstall/reinstall and then try again (but this time don't edit things in Finder).

**Comment by martyns0n** [comment]
> This is what worked to fix it for me
> 
> `codesign --force --deep --sign - /Applications/Notion.app`

@rafaelosoto Thanks, it worked for me. I duplicate this command for fast searching.

**Comment by dmercado2001** [comment]
So I had to restart my Mac running on Big Sir for a separate reason, and when I reopened it, I was unable to reopen the Notion app. I put that code above in and I got this as my reply

/Applications/Notion.app: replacing existing signature
 xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
/Applications/Notion.app: the codesign_allocate helper tool cannot be found or used
In subcomponent: /Applications/Notion.app/Contents/Frameworks/Notion Helper (Plugin).app`

**Comment by dragonwocky** [comment]
@dmercado2001 https://stackoverflow.com/questions/58280652/git-doesnt-work-on-macos-catalina-xcrun-error-invalid-active-developer-path

**Comment by fawnlies** [comment]
I'm on Mac Big Sur 11.2.1. After running... 
> codesign --force --deep --sign - /Applications/Notion.app

I open notion but can't view the window. I open the app, but nothing happens except the menu bar showing that Notion is open. I can't view the Notion window, I can't create new windows. Clicking "Show Available Windows" in my dock says that there are "No Available Windows." I've tried restarting multiple times. 

This is after installing vanilla Notion, opening it, closing it, installing Notion enhancer, opening notion to get the same issue above, restarting my computer, getting the permission error, running the code above, and now getting the issue above, now with multiple restart attempts.

**Comment by ArthurJakobsson** [comment]
I am getting the same error as @fawnlies . I am on Mac Big Sur 11.2.2. I run the same commands and it does not work. I no longer get the error (which happened the first time I did it exactly as fawnlies did). Now the app opens and shows in the menu bar, but no window opens. I, too, have restarted a few times.  I have also uninstalled notion-enhancer and notion multiple times to no avail. Any help is extremely appreciated.  

When I remove notion-enhancer using npm, opening Notion normally gives me this error:

![Screen Shot 2021-02-28 at 7 54 54 PM](https://user-images.githubusercontent.com/39499551/109450049-d52bbe80-79fe-11eb-846c-b480331dc09a.png)

`Uncaught Exception:
Error: Cannot find module '/usr/local/lib/node_modules/notion-enhancer/pkg/loader.js'
Require stack:
- /Applications/Notion.app/Contents/Resources/app/config.js
- /Applications/Notion.app/Contents/Resources/app/main/crashReporter.js
- /Applications/Notion.app/Contents/Resources/app/main/main.js
- 
at Module._resolveFilename (internal/modules/cjs/loader.js:972:15)
at Function.n._resolveFilename (electron/js2c/browser_init.js:249:921)
at Module._load (internal/modules/cjs/loader.js:848:27)
at Function.f._load (electron/js2c/asar_bundle.js:5:12694)
at Module.require (internal/modules/cjs/loader.js:1032:19)
at require (internal/modules/cjs/helpers.js:72:18)
at Object.<anonymous> (/Applications/Notion.app/Contents/Resources/app/config.js:8:1)
at Module._compile (internal/modules/cjs/loader.js:1152:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1173:10)
at Module.load (internal/modules/cjs/loader.js:992:32)`

**Comment by rafaelosoto** [comment]
For the record that file exists on my computer. Big Sur 11.0. maybe install
is broken

**Comment by ArthurJakobsson** [comment]
@rafaelosoto thank you for you response. I reinstalled it and I managed to get it to work! I joined the discord and dragonwocky has posted this article which helps: [link](https://www.notion.so/Custom-Notion-Themes-57c56474b49544969f92fa0937f78956).

I copy his instructions below
1. uninstall/reinstall notion to refresh it
2.. if the enhancer is already installed, run `notion-enhancer apply -y`. otherwise, run `npm i -g notion-enhancer`.
3. replace line 108 of `notion-enhancer/mods/core/client.js` with
`!document.querySelector('.notion-topbar > div[style*="display: flex"]')`
4. add the following to line 19 of `notion-enhancer/mods/core/createWindow.js`:
5. if on a newer version of macOS and you get a permissions error when opening the app, run `codesign --force --deep --sign - /Applications/Notion.app`

Hopefully this works for you as well @fawnlies

**Comment by vpopovs** [comment]
@ArthurJakobsson, I believe you forgot to add the contents of line 19 to your comment. Hence I am also attaching a link to the issue with the fix you described.
https://github.com/notion-enhancer/notion-enhancer/issues/437
@fawnlies hope his helps.

**Comment by dragonwocky** [comment]
as of v0.11.0 there will be 2 simple solutions for this:
- run `notion-enhancer sign`, which will run `xcode-select --install && codesign --force --deep --sign - /Applications/Notion.app`
- use notion-repackaged
