### ISSUE TITLE
rainbow style bullets and indentations 

### ISSUE THREAD

**Issue by MedBlueprint** [notion-enhancer/desktop#367]
Current situation: If I colour a block, the bullets within the block get the same colour. 

Cordial request: Any possibility of  automatically rainbow style colouring (without manually colouring the blocks)
in cloudhill's already great '**indentation lines**' extension would be amazing!

![image](https://user-images.githubusercontent.com/75526224/103868278-e50bde00-50f2-11eb-8b7c-7852f70e2aec.png)

**Comment by MedBlueprint** [comment]
It's a pretty theme for roam research, the sources for actual css is mentioned here: https://roamresearch.com/#/app/roamcss/page/aT9-qyjya

**Comment by dragonwocky** [comment]
![image](https://user-images.githubusercontent.com/16874139/137624296-7d78e558-5bab-42bf-b4b7-58b1265a2f6c.png)
