### ISSUE TITLE
Timeline not displaying correctly

### ISSUE THREAD

**Issue by Tripp3235** [notion-enhancer/desktop#385]
FILL OUT THIS TEMPLATE, REMOVING/REPLACING ALL NON-BOLD TEXT WITH YOUR OWN INFORMATION.
BE AS CLEAR AND CONCISE AS POSSIBLE.

**describe the bug**
Timeline view is useless within Notion Enchancer while dark mode and dark+ is toggled

**expected behaviour**
Timeline should display with appropriate background color (dark) and the fonts shouldn't be whited out.

**screenshots**
if applicable, add screenshots of your problem.

**platform**
OS X 11.1 Apple M1

**Comment by dragonwocky** [comment]
screenshot?

**Comment by Tripp3235** [comment]
So. I have found it works on my regular intel mac.  This must have something with the Apple M1 processor as the rest of the versions are the same.
<img width="1301" alt="Screen Shot 2021-01-25 at 9 17 53 AM" src="https://user-images.githubusercontent.com/77940549/105725356-78fce880-5eee-11eb-8682-a4ee99aac12d.png">
