### ISSUE TITLE
Tab History

### ISSUE THREAD

**Issue by bokonist** [notion-enhancer/desktop#399]
**problem**

Have to reopen tabs when notion is restarted. Not convenient when working with more than a few tabs.

**solution**

how will this feature appear/act?

On starting Notion, pick up where we left off from the previous session.

how could this be technically implemented using the available
capabilities of the enhancer and notion?

1.Keep a file to track page IDs for pages that are open currently. Initially it's just the homepage.
2. When you open a new tab, add that page ID to the file.
3. When you close a tab, remove that page ID from the file.
4. When a notion window is opened fresh, open all the pages in that file.
5. Provide an option to switch  "Pick up where you left off" off in the notion enhancer menu

**cons**

what are the potential costs or dangers of this feature, or things that may go
outside of the enhancer's scope? e.g. bad performance, security issues, or
modifying the data notion stores.

Can't think of any except memory issues with large number of tabs.

**alternatives**

would a different feature remove the need for this?

Could be integrated into the tabs core feature.

does this need to be implemented by the enhancer? could an external service work better?
No.

**Comment by dmercado2001** [comment]
hey I opened #389 and I wouldn't say this is a potential duplicate! Mine is a bug that has to do with the tab not showing the title like it's supposed to (and like it used to before the Big Sur 11.1 update), and this is a enhancement to pick up where you left off.

**Comment by dragonwocky** [comment]
@dmercado2001 you're right, this is a different issue... I'd actually forgotten the bot was even there because it's never worked before lol, bit strange.

**Comment by dmercado2001** [comment]
@dragonwocky thank you! if you get the chance, please check out my bug #389, it seems other people have the same issue as well!
