### ISSUE TITLE
Enabling #core tabs creates issues with cursor location and keyboard input

### ISSUE THREAD

**Issue by JJKW1984** [notion-enhancer/desktop#400]
**describe the bug**
Enabling #core tabs creates issues with cursor location and keyboard input. The cursor line no longer blinks or indicates where it is and typing sometimes works and sometimes doesn't depending on the context. For example if you create a new text block then hit return the cursor will disappears and you will have to use the mouse to select where you want to type next. 

It seems to break all keyboard navigation.

I would be happy to create a video of the issue if that is helpful.

**expected behavior**
The plugin shouldn't effect any change into the input of text or the cursor positioning.

**screenshots**
if applicable, add screenshots of your problem.

**platform**
what OS are you using? e.g. windows 7, windows 10, WSL, ubuntu, arch linux, macOS
Windows 10 Latest version of node and notion-enhancer.

**Comment by limittox** [comment]
Same issue here. The cursor disappears as if there is nothing. I don't know where I am typing.
But the issue fixes itself when tabs are removed.

Windows 10

**Comment by robinpdev** [comment]
I know javascript and a bit of electron, where should I look to attempt to solve this bug?

**Comment by robinpdev** [comment]
I found a temporary fix for this, all you have to do is go back to another tab where you do have a cursor, click somewhere where you can enter text and return to the other tab, you should also have a cursor there

**Comment by 0GreenClover0** [comment]
Or just click on the tab in the titlebar, in which you are trying to type (at least it works for me). I guess there is some problem with focusing on the newly created tab

**Comment by rockmanvnx6** [comment]
Same issue for linux and osx.
