### ISSUE TITLE
Toggles as Headings

### ISSUE THREAD

**Issue by dmercado2001** [notion-enhancer/desktop#405]
**problem**
why is this feature necessary? how will it help? what existing shortcomings does it address?

Headings being toggle-able (is that even a word? lol) would be extremely useful for notetaking and simply organizing notes in general. It would address the shortcoming of toggles always being only in the same size. Generally the things that are placed as toggles are heading kind of things, so it would be awesome to be able to conceptualize this as actual headings and see the toggle font go down in size as we go down.

**solution**
how will this feature appear/act? how could this be technically implemented using the available
capabilities of the enhancer and notion?

This feature will look and act same as regular toggles and headings, except now the toggles can take on the heading sizes.

**cons**
what are the potential costs or dangers of this feature, or things that may go outside of the enhancer's scope? e.g. bad performance, security issues, or modifying the data notion stores.

I don't forsee any dangers. However, I do forsee difficulty in creating this setting, as toggle and heading typically counteract each other (as in it can be one or the other but not both as a type of input). I think maybe either when clicking toggle, you can have another thing that specifies what kind of toggle you want (heading 1, heading 2, heading 3, regular text), or when you go to edit the line it can be an option, or when highlighting the text, it can be changed to any of the options listed (or any others I didn't think of). Or all of these ideas can be options to getting there. These are just ideas.

**alternatives**
would a different feature remove the need for this? does this need to be implemented by the enhancer? could an external service work better? e.g. playing background music via noisli or youtube.

A different feature wouldn't remove it, but if regular notion would come out with that feature, then there wouldn't be a need to include it in the enhancer.

**Comment by dragonwocky** [comment]
https://github.com/notion-enhancer/notion-enhancer/pull/320 will be out in next release

**Comment by dmercado2001** [comment]
@dragonwocky ooo that sounds awesome! thank you all for your hard work!!

**Comment by caster-guy** [comment]
> #320 will be out in next release

i installed n.e and i can't find it can u help with that?

**Comment by dragonwocky** [comment]
@caster-guy if this issue is open, it hasn't been released in the version installable from the command line yet. It is available if you install notion-repackaged, though: https://github.com/notion-enhancer/notion-repackaged/releases/

**Comment by dword-design** [comment]
Just found out that this is now possible with toggle headings, in case it's relevant for this project.

**Comment by twistedmacaroni** [comment]
> @caster-guy if this issue is open, it hasn't been released in the version installable from the command line yet. It is available if you install notion-repackaged, though: https://github.com/notion-enhancer/notion-repackaged/releases/

hi, 
is it possible to get To-Do lists in headings as well? just to match the others..
