### ISSUE TITLE
Custom/Differentiated Bullet Points

### ISSUE THREAD

**Issue by dmercado2001** [notion-enhancer/desktop#407]
**problem**
why is this feature necessary? how will it help? what existing shortcomings does it address?

this feature would allow for clearer distinction in levels of bullets while note-taking.

**solution**
how will this feature appear/act? how could this be technically implemented using the available capabilities of the enhancer and notion?

this feature will look like different bullet points depending on the level of indentation. it can either be customizable or set in stone, depending on how you all want to customize it if you do.

**cons**
what are the potential costs or dangers of this feature, or things that may go outside of the enhancer's scope? e.g. bad performance, security issues, or modifying the data notion stores.

I don't forsee any potential costs, dangers, or difficulties.

**alternatives**
would a different feature remove the need for this? does this need to be implemented by the enhancer? could an external service work better? e.g. playing background music via noisli or youtube.

no removal of any feature needed. only way I can forsee it not being implemented by the enhancer is if Notion does it themselves.

**Comment by dragonwocky** [comment]
now implemented natively in notion
![image](https://user-images.githubusercontent.com/16874139/147819295-cca2826d-e84f-4f1a-8138-93351d8e4cde.png)
