### ISSUE TITLE
Code line numbers extension hides part of code on single lined blocks

### ISSUE THREAD

**Issue by fabiosangregorio** [notion-enhancer/desktop#436]
**describe the bug**
With the new update, when "code line numbers" extension is activated and "show line numbers on single-lined code blocks
" is NOT active, the initial part of code (**only in single lined blocks**) is hidden by the background of the line numbers container html node. 
I am tagging @CloudHill since he's the (great :D) author of the extension.

**expected behaviour**
why is this a bug - what should be happening?

**screenshots**
![https://i.imgur.com/SPZlULF.png](https://i.imgur.com/SPZlULF.png)

**platform**
Windows 10

**Comment by dragonwocky** [comment]
@l782993610 thanks, was that code based off https://github.com/notion-enhancer/notion-enhancer/pull/600?
