### ISSUE TITLE
Notion-enhancer doesnt work with new version(2.0.13+)

### ISSUE THREAD

**Issue by Pingye007** [notion-enhancer/desktop#437]
FILL OUT THIS TEMPLATE, REMOVING/REPLACING ALL NON-BOLD TEXT WITH YOUR OWN INFORMATION.
BE AS CLEAR AND CONCISE AS POSSIBLE.

**describe the bug**
what is the bug - what happens?
after downloading notion@2.0.13,I found the old version(0.8.5) of notion-enhancer installed on my computer didnt work,
so I downloaded notion-enhancer@0.10.2,and then notion just couldnt open.I have to uninstall the notion-enhancer so that
notion worked again,but when I checked with command: notion-enhancer -v,it showed me 'notion-enhancer/0.10.2'......
I clearly remembered Ive removed it...
**expected behaviour**
why is this a bug - what should be happening?
work again with notion@2.0.13
**screenshots**
if applicable, add screenshots of your problem.
![image](https://user-images.githubusercontent.com/54070404/109388431-ecf13d00-7941-11eb-80f6-fa50342a9dec.png)
![image](https://user-images.githubusercontent.com/54070404/109388438-009ca380-7942-11eb-8263-28b6f14dcec3.png)
**platform**
what OS are you using? e.g. windows 7, windows 10, WSL, ubuntu, arch linux, macOS
windows 10

**Comment by dragonwocky** [comment]
the next update is still a good while away from being ready for use, so for the meantime I've put together a few quick steps so you can patch your own installation of the current version to work with the latest notion update: https://www.notion.so/dragonwocky/hack-v0-10-2-to-work-with-notion-s-v2-0-13-app-a4ab1267e67b4126b6448641ca4a0041

**Comment by denipesto** [comment]
@dragonwocky It works! Thanks for such an extension!

**Comment by euler007** [comment]
Thank you @dragonwocky for the workaround!
A couple of points I noticed, open and close tab shortcuts are not working and app is not quitting with cmd+q

**Comment by mohamedelzero** [comment]
> the next update is still a good while away from being ready for use, so for the meantime I've put together a few quick steps so you can patch your own installation of the current version to work with the latest notion update: https://www.notion.so/dragonwocky/hack-v0-10-2-to-work-with-notion-s-v2-0-13-app-a4ab1267e67b4126b6448641ca4a0041



> Thank you @dragonwocky for the workaround!
> A couple of points I noticed, open and close tab shortcuts are not working, app is not quitting with cmd+q, side panel does not work.



> Thank you @dragonwocky for the workaround!
> A couple of points I noticed, open and close tab shortcuts are not working, app is not quitting with cmd+q, side panel does not work.

can you make a video for this I am not a programmer

**Comment by saifeddin1** [comment]
> the next update is still a good while away from being ready for use, so for the meantime I've put together a few quick steps so you can patch your own installation of the current version to work with the latest notion update: https://www.notion.so/dragonwocky/hack-v0-10-2-to-work-with-notion-s-v2-0-13-app-a4ab1267e67b4126b6448641ca4a0041

Thaaaaaaaaaaaaaanks

**Comment by Chlesea** [comment]
> the next update is still a good while away from being ready for use, so for the meantime I've put together a few quick steps so you can patch your own installation of the current version to work with the latest notion update: https://www.notion.so/dragonwocky/hack-v0-10-2-to-work-with-notion-s-v2-0-13-app-a4ab1267e67b4126b6448641ca4a0041

Thaaaaaaaaaaaaaanks

**Comment by whitehammer** [comment]
Now it's opening twice for me, what am I doing wrong?

**Comment by roadrunnerGH** [comment]
> the next update is still a good while away from being ready for use, so for the meantime I've put together a few quick steps so you can patch your own installation of the current version to work with the latest notion update: https://www.notion.so/dragonwocky/hack-v0-10-2-to-work-with-notion-s-v2-0-13-app-a4ab1267e67b4126b6448641ca4a0041

I looked at the link and I don't have 100+ lines of code where I can alter - my command prompt (after npm i -g notion-enhancer) 
`Microsoft Windows [Version 10.0.19042.804]
(c) 2020 Microsoft Corporation. All rights reserved.

C:\Users\[my name]>npm i -g notion-enhancer

changed 29 packages, and audited 30 packages in 2s

1 package is looking for funding
  run `npm fund` for details

found 0 vulnerabilities`

**Comment by dragonwocky** [comment]
@roadrunnerGH if you read the instructions carefully, it includes a link to how to find where node modules are installed to and once you've got there filepaths to the specific enhancer files you need to edit. Your command prompt looks fine.

**Comment by NicolaLino** [comment]
> the next update is still a good while away from being ready for use, so for the meantime I've put together a few quick steps so you can patch your own installation of the current version to work with the latest notion update: https://www.notion.so/dragonwocky/hack-v0-10-2-to-work-with-notion-s-v2-0-13-app-a4ab1267e67b4126b6448641ca4a0041

I found the file location of notion-enhancer but which file do I edit the code in ??

**Comment by dragonwocky** [comment]
@NicolaLino there are 2 different files you need to edit. please read the instructions. they say which files.

**Comment by NicolaLino** [comment]
> @NicolaLino there are 2 different files you need to edit. please read the instructions. they say which files.

thank you very very very much it worked. sorry I didn't read the instructions carefully

**Comment by Umeor** [comment]
> the next update is still a good while away from being ready for use, so for the meantime I've put together a few quick steps so you can patch your own installation of the current version to work with the latest notion update: https://www.notion.so/dragonwocky/hack-v0-10-2-to-work-with-notion-s-v2-0-13-app-a4ab1267e67b4126b6448641ca4a0041

Even after doing this exactly, Notion still won't open. I'm 100% sure I didn't mess up, is there a different way to fix this?

**Comment by roadrunnerGH** [comment]
> @roadrunnerGH if you read the instructions carefully, it includes a link to how to find where node modules are installed to and once you've got there filepaths to the specific enhancer files you need to edit. Your command prompt looks fine.

Took some doing as I'm pretty untechnical but got it working now! thx boss

**Comment by Pingye007** [comment]
@dragonwocky sorry too busy last week,I just used the patch just now and finally notion worked agian,thankkks so much!!

**Comment by dragonwocky** [comment]
don't close bug issues until they're solved in a release, not just have a temp fix, please.

**Comment by Pingye007** [comment]
@dragonwocky forgive me,I dont usually commit issues actually

**Comment by Juju6004** [comment]
I'm a little confused, I've run the notion-enhancer in command prompt and I even checked to see (notion-enhancer check) and it says that it is applied however notion itself won't open and I'm not sure what I'm doing wrong. (Not a coder so a little lost)

**Comment by joshdavies14** [comment]
> the next update is still a good while away from being ready for use, so for the meantime I've put together a few quick steps so you can patch your own installation of the current version to work with the latest notion update: https://www.notion.so/dragonwocky/hack-v0-10-2-to-work-with-notion-s-v2-0-13-app-a4ab1267e67b4126b6448641ca4a0041

@Juju6004 as mentioned above follow the instructions linked here which will fix the issue

**Comment by Juju6004** [comment]
@joshdavies14 Sorry I'm still a little confused. I tried doing the fix. I ran notion-enhancer apply -y and didn't get anywhere near 108 lines of code. I also tried using the link to understand what I was doing wrong but am still not sure. Is anyone able to create a video tutorial for this for those who aren't really coders? Would be much appreciated.

**Comment by roadrunnerGH** [comment]
> @joshdavies14 Sorry I'm still a little confused. I tried doing the fix. I ran notion-enhancer apply -y and didn't get anywhere near 108 lines of code. I also tried using the link to understand what I was doing wrong but am still not sure. Is anyone able to create a video tutorial for this for those who aren't really coders? Would be much appreciated.

Did you use `npm i -g notion-enhancer` to install notion enhancer in your command terminal?
If so, type `npm root -g` and press enter - this will show you the file path the notion enhancer files were downloaded to
Open up this file path by clicking down through the folders/sub folders it specifies until you can see the notion-enhancer subfolder
Click this folder, then mods, core, and find the client.js file (JavaScript File)
Right click on this file and press edit. This is where you will copy and paste/alter code as stated in the instructions.
Hit save and exit the file
Next find the createWindow.js file and follow step 4. Save and close.

**Comment by Juju6004** [comment]
@roadrunnerGH So I tried this, and when I use npm root -g ann I get in response is Users\AppData\Roaming\npm\node_modules
and nothing else. I don't really see a file path or anything I can even click.

**Comment by dragonwocky** [comment]
@Juju6004 that IS the filepath (`C:\Users\YOURNAME\AppData\Roaming\npm\node_modules`). then the filepaths within that folder to the specific files are stated in the instructions.

**Comment by ProductivityCorner** [comment]
Here is a quick step by step video tutorial on how to apply the fix mentioned by dragonwocky in his post. Hope you find it helpful! https://youtu.be/vcwUpwpQ2sY

> the next update is still a good while away from being ready for use, so for the meantime I've put together a few quick steps so you can patch your own installation of the current version to work with the latest notion update: https://www.notion.so/dragonwocky/hack-v0-10-2-to-work-with-notion-s-v2-0-13-app-a4ab1267e67b4126b6448641ca4a0041

**Comment by chris-larsen** [comment]
> the next update is still a good while away from being ready for use, so for the meantime I've put together a few quick steps so you can patch your own installation of the current version to work with the latest notion update: https://www.notion.so/dragonwocky/hack-v0-10-2-to-work-with-notion-s-v2-0-13-app-a4ab1267e67b4126b6448641ca4a0041

This solution is no longer working from me. I've reinstalled notion, reinstalled notion enhancer, even reinstalled NPM and have had no luck. 

The final `codesign` step is now resulting in this error:

```BASH
/Applications/Notion.app: replacing existing signature
/Applications/Notion.app: resource fork, Finder information, or similar detritus not allowed
```

**Comment by dragonwocky** [comment]
@chris-larsen 
> The final codesign step is now resulting in this error:

That error happens sometimes when it gets upset that you've viewed the app files in Finder. You'll need to reinstall Notion, run `notion-enhancer apply` to enhance it (the files you need to edit are stored outside of Notion itself, so you don't need to redo any of that), then run the codesign command.

**Comment by chris-larsen** [comment]
Cheers for the fix, that was exactly what was happening. I had another app (Pictogram) that I use to customize app icons on MacOS. App functionality provided that it would keep icons automatically updated when you update MacOS, and this also caused it to changed the icon to a customized one I chose even when I reinstalled. So technically Pictogram was modifying the Notion.app file every time I reinstalled and I couldn't figure out what was happening. Love this plugin, good luck with the next release!

**Comment by cpau570** [comment]
Hi @dragonwocky  I followed your instructions for the fix. I'm on MacOS. But now, the Notion app doesn't open. :-(  It says, You do not have permission to open the application “Notion”. But I'm the admin. I tried the 5th step of your instructions, but I got this prompt in Terminal "the codesign_allocate helper tool cannot be found or used".

**Comment by dragonwocky** [comment]
@cpau570 try running `sudo xcode-select --reset` in terminal and then do step 5 again.

**Comment by nandudb** [comment]
+1 Notion doesn't open on Mac after updating notion-enhancer/0.10.2 darwin-x64 node-v14.11.0. Any quick fix or workaround?

**Comment by dragonwocky** [comment]
@nandudb yes, actually, in the very first response to this issue.

**Comment by fengbeibei** [comment]
works on notion v2.0.16, thanks!

**Comment by imihandstand** [comment]
> the next update is still a good while away from being ready for use, so for the meantime I've put together a few quick steps so you can patch your own installation of the current version to work with the latest notion update: https://www.notion.so/dragonwocky/hack-v0-10-2-to-work-with-notion-s-v2-0-13-app-a4ab1267e67b4126b6448641ca4a0041

Where is that "notion-enhancer/mods/core/client.js" on Mac?! Cant find it, starting to get really frustrated...

**Comment by chris-larsen** [comment]
> > the next update is still a good while away from being ready for use, so for the meantime I've put together a few quick steps so you can patch your own installation of the current version to work with the latest notion update: https://www.notion.so/dragonwocky/hack-v0-10-2-to-work-with-notion-s-v2-0-13-app-a4ab1267e67b4126b6448641ca4a0041
> 
> 
> 
> Where is that "notion-enhancer/mods/core/client.js" on Mac?! Cant find it, starting to get really frustrated...

Open terminal and type this, it'll take you to the directory:

![image](https://user-images.githubusercontent.com/32186637/112640685-c8806780-8dfe-11eb-8601-b6657480ad44.jpeg)

**Comment by imihandstand** [comment]
> Open terminal and type this to find your root node directory (which can be different for everyone depending on how you installed it) `npm root -g`
Thank you - that way I found the folder. I then did the changes, but it didn't work - Notion still didn't open.

**Comment by optemism** [comment]
> > Open terminal and type this to find your root node directory (which can be different for everyone depending on how you installed it) `npm root -g`
> > Thank you - that way I found the folder. I then did the changes, but it didn't work - Notion still didn't open.
> 
> > > > the next update is still a good while away from being ready for use, so for the meantime I've put together a few quick steps so you can patch your own installation of the current version to work with the latest notion update: https://www.notion.so/dragonwocky/hack-v0-10-2-to-work-with-notion-s-v2-0-13-app-a4ab1267e67b4126b6448641ca4a0041
> > > 
> > > 
> > > Where is that "notion-enhancer/mods/core/client.js" on Mac?! Cant find it, starting to get really frustrated...
> > 
> > 
> > Open terminal and type this to find your root node directory (which can be different for everyone depending on how you installed it) `npm root -g`
> 
> Thank you - that way I found the folder. I then did the changes, but it didn't work - Notion still didn't open.

Did you manage to get it to work?

**Comment by chris-larsen** [comment]
> > Open terminal and type this to find your root node directory (which can be different for everyone depending on how you installed it) `npm root -g`
> > Thank you - that way I found the folder. I then did the changes, but it didn't work - Notion still didn't open.
> 
> > > > the next update is still a good while away from being ready for use, so for the meantime I've put together a few quick steps so you can patch your own installation of the current version to work with the latest notion update: https://www.notion.so/dragonwocky/hack-v0-10-2-to-work-with-notion-s-v2-0-13-app-a4ab1267e67b4126b6448641ca4a0041
> > > 
> > > 
> > > Where is that "notion-enhancer/mods/core/client.js" on Mac?! Cant find it, starting to get really frustrated...
> > 
> > 
> > Open terminal and type this to find your root node directory (which can be different for everyone depending on how you installed it) `npm root -g`
> 
> Thank you - that way I found the folder. I then did the changes, but it didn't work - Notion still didn't open.

Did you happen to open the /Applications/Notion.app -> show package contents when you were trying to find the root node directory? I found last week that messeing with anything inside the notion.app itself will break it, and I had to reinstall entirely and start over. 

Your node directory is separate so any of the patch workaround stuff outlined above that was put there doesn't need to be touched. Can you share screenshots of the createwindow.js and client.js you edited so I can confirm you did everything correctly (try to use an editor that shows line numbers for the screenshot).

**Comment by imihandstand** [comment]
@chris-larsen / @optemism : I tried it again and made a screenshot from everything. After completing every step from that hack-page, when I try to open Notion it says I don't have permission to open it AND a few seconds gives me a "Notion quit unexpectedly"-error too. You see everything in the screenshot.

![Screen Shot 2021-03-28 at 17 19 18](https://user-images.githubusercontent.com/44979581/112757381-ebbb3a80-8fe9-11eb-89c0-fb5a11481c55.png)

**Comment by dragonwocky** [comment]
@imihandstand if you read the response in terminal, the codesign command failed. running `xcode-select --install` in terminal and then the codesign command again afterwards should fix things.

**Comment by imihandstand** [comment]
> @imihandstand if you read the response in terminal, the codesign command failed. running `xcode-select --install` in terminal and then the codesign command again afterwards should fix things.

Thank you very much everybody! Now, after like 4 months of trying, it finally works! Really needed the multi-tab feature :)

**Comment by etherealego** [comment]
This fix has been working perfectly for me since the issue started, so I want to start out with a big thank you to @dragonwocky for the support. However (and I haven't seen anyone else mention this), for me this is only a temporary fix.

 Every week give or take, I will have to run through this again. Shortly after either a update/restart, notion crash, or simply exiting the program and notion-enhancer via tray icon, notion-enhancer just stops working. Honestly this could be a fault of some other things that run on my computer ($%#! NZXT cam) but I just wanted to check if that's to be expected or if there's anything I can do to make it a 'permanent' solution.

**Comment by imihandstand** [comment]
> This fix has been working perfectly for me since the issue started, so I want to start out with a big thank you to @dragonwocky for the support. However (and I haven't seen anyone else mention this), for me this is only a temporary fix.
> 
> Every week give or take, I will have to run through this again. Shortly after either a update/restart, notion crash, or simply exiting the program and notion-enhancer via tray icon, notion-enhancer just stops working. Honestly this could be a fault of some other things that run on my computer ($%#! NZXT cam) but I just wanted to check if that's to be expected or if there's anything I can do to make it a 'permanent' solution.

For me it's (so far) permanent - I restarted Notion since this hack multiple times already and the fix stays, I don't have to redo it.

**Comment by aminya** [comment]
Any reason for not releasing a patch to fix the issue? @dragonwocky

**Comment by dragonwocky** [comment]
@aminya basically:
a) it's not a "full" fix, in that even when patched there are almost more things broken than working (as you can tell by looking at all the other issues here). it's a temporary "this will get it to launch, at least".
b) it would make future updates more annoying to manage (e.g. git merging of the various stages of things and it would end up releasing features that are half-built and undocumented/not ready for use).

I just haven't had the time to finish a proper update yet. I have a short break after Easter, so I plan to make some progress this week.

**Comment by fharper** [comment]
> the next update is still a good while away from being ready for use, so for the meantime I've put together a few quick steps so you can patch your own installation of the current version to work with the latest notion update: https://www.notion.so/dragonwocky/hack-v0-10-2-to-work-with-notion-s-v2-0-13-app-a4ab1267e67b4126b6448641ca4a0041

Works for me, thanks!

**Comment by mekpower** [comment]
Hello! Anyone can help me? For me keep dot working, my notion works fine, but the notion-enhancer dont appear. The icon in taskbar dont show, in task manager dont appear nothing. I used the commands `notion-enhancer apply` and `notion-enhancer check` and it say that is applied.

**Comment by dragonwocky** [comment]
p.s. this is fixed in [notion-repackaged](https://github.com/notion-enhancer/notion-repackaged/releases/) - uninstall notion & the npm version of notion enhancer, then install the relevant file from here (e.g. a .exe for windows and a .dmg for macOS)
