### ISSUE TITLE
Duplicate Notion Windows

### ISSUE THREAD

**Issue by Rij29** [notion-enhancer/desktop#478]
A new notion window opens up if it is minimized and use the icon. 

I am using *MacOS big Sur*

**Comment by dragonwocky** [comment]
this is a bug that's come from the different ways windows and macos handle windows - try using `cmd+shift+a` or clicking on the menubar icon to make the minimised window re-focus

**Comment by imihandstand** [comment]
> A new notion window opens up if it is minimized and use the icon.
> 
> I am using _MacOS big Sur_

Can confirm this bug, have the same problem, using Big Sur too.

**Comment by watertreestar** [comment]
I have same bug on MacOS bigsur

**Comment by solirpa** [comment]
Same bug on MacOS bigsur newest version, It affects the normal use.

**Comment by HassanMojab** [comment]
+1
