### ISSUE TITLE
Too big icons used by default

### ISSUE THREAD

**Issue by spothound** [notion-enhancer/desktop#501]
FILL OUT THIS TEMPLATE, REMOVING/REPLACING ALL NON-BOLD TEXT WITH YOUR OWN INFORMATION.
BE AS CLEAR AND CONCISE AS POSSIBLE.

**describe the bug**
There are too much big icons on notion windows.

I've just installed this notion-enhancer on Arch Linux using the AUR package and there is something wrong with the icons? I've tried changing my system default icons but without success. 

**expected behaviour**
I think the icons shown in the screenshot should be others or at least be scaled to fit a regular size.

**screenshots**
![image](https://user-images.githubusercontent.com/15269938/120679195-31d4c480-c499-11eb-9399-fa58814dc4e0.png)

**platform**
Arch Linux

**Comment by dragonwocky** [comment]
duplicate, described in https://github.com/notion-enhancer/notion-enhancer/issues/291 with potential fixes
