### ISSUE TITLE
Full Width

### ISSUE THREAD

**Issue by skirmishd** [notion-enhancer/desktop#504]
Can we get the "Full Width" for all pages or at least inherited? 

Not everyone uses Notion with a big screen or resolution, but even when we do, I prefer to have Full Width turned on, since it won't hide my code inside the fences or the inline table.

**Comment by dragonwocky** [comment]
try adding this tweak to custom inserts:
```css
:root {
  --theme--page_normal-width: 100%;
}
```

**Comment by skirmishd** [comment]
Yeah, didn't work.
Tried appending the theme too, didn't change a thing.
