### ISSUE TITLE
[FR] Blue links with underscore

### ISSUE THREAD

**Issue by EmersonDing** [notion-enhancer/desktop#524]
**problem**
Currently double bracket is available, but traditional link format (blue + underscore) also will be helpful for eyeball.

**Comment by dragonwocky** [comment]
![image](https://user-images.githubusercontent.com/16874139/136681764-5bc660e7-6866-4101-8787-7028e40f34b9.png)
![image](https://user-images.githubusercontent.com/16874139/136681772-e74d4594-a4e7-414b-80ac-169ebb7ffb68.png)
