### ISSUE TITLE
Notion won't open "notion://" links, shows most recent page instead

### ISSUE THREAD

**Issue by djosci** [notion-enhancer/desktop#540]
I have tons of "notion://" links as desktop shortcuts. I use them to open Notion pages right from my desktop.

Notion Enhancer won't let me open these shortcuts - or any "notion://" URL - anymore. When I try to open a "notion://" URL, Notion shows the most recent page instead.

The "default page id/url" field is blank (as I believe it should be).

The issue disappears once Notion Enhancer is uninstalled.

I use Windows 10.

**Comment by jamezrin** [comment]
Are you using notion-repackaged or patching the app manually?

**Comment by djosci** [comment]
> Are you using notion-repackaged or patching the app manually?

I am using the official Notion desktop app for Windows 10.

**Comment by dragonwocky** [comment]
on testing, this is caused when notion hasn't actually been closed and is still running in the background, so following a `notion://` link merely re-shows the app instead of navigating to the intended link
