### ISSUE TITLE
Notion Repackaged No Longer Opening

### ISSUE THREAD

**Issue by rahulpatel1936** [notion-enhancer/desktop#562]
FILL OUT THIS TEMPLATE, REMOVING/REPLACING ALL NON-BOLD TEXT WITH YOUR OWN INFORMATION.
BE AS CLEAR AND CONCISE AS POSSIBLE.

**describe the bug**
Hello! Earlier, I had a problem with accessing Notion Enhanced. However, that issue had been resolved. At some point, I quit Notion Enhanced and then tried to relaunch it. However, the Notion Enhanced window does not launch.

**expected behaviour**
The Notion Enhanced window should pop up

**screenshots**
N/A

**platform**
MacOS M1

**Comment by dragonwocky** [comment]
it's likely that the app is actually still open when this happens, and is just hidden to your menubar. clicking the notion-enhancer icon in the top right of your screen should bring the window back.

**Comment by rahulpatel1936** [comment]
Hello @dragonwocky. Unfortunately, clicking on the icon at the top right of the screen did not bring the window back : (

**Comment by dragonwocky** [comment]
@rahulpatel1936 if you are able to right-click the icon (or kill the app in task manager - it may be called activity monitor on mac?) or restart the app and enter the enhancer menu, disabling the "close window to tray option" should stop this from happening.
