### ISSUE TITLE
Open new tabs when using `Open in Windows app` from chrome

### ISSUE THREAD

**Issue by DenisD3D** [notion-enhancer/desktop#569]
When using `Open in Windows app` from chrome, a new Notion windows open.
I would prefere that it open a new tab or replace the current opened window by the new one (maybe something customizable for those who don't use tabs)

I managed to do it adding :

Notion\resources\app\main\main.js replace line 188 by
```
let allWindows = electron_1.BrowserWindow.getAllWindows();
(allWindows.length == 1 ? allWindows[0] : allWindows[1]).webContents.send("enhancer:new-tab2", urlPath);
allWindows.length == 1 ? allWindows[0].focus() : allWindows[1].focus();
```
for opening a new tab or to replace the current window by
```
notionIpc.sendMainToNotionWindow(allWindows.length == 1 ? allWindows[0] : allWindows[1], "notion:navigate-to-url", urlPath);
allWindows.length == 1 ? allWindows[0].focus() : allWindows[1].focus();
```

notion-enhancer\mods\core\render.js line 174
```
electron.ipcRenderer.on('enhancer:new-tab2', (event, url) => {
          this.newTab(url);
        });
```
^must be a way without adding a new listener but i haven't found it

notion-enhancer\mods\core\tray.js comment line 32-43
```
/*electron.app.on('second-instance', (event, args, workingDirectory) => {
    const windows = getAllWindows();
    if (windows.some((win) => win.isVisible())) {
      newWindow();
    } else {
      windows.forEach((window) => {
        window.show();
        window.focus();
        if (store().maximized) window.maximize();
      });
    }
  });*/
```

Also found an issue that isn't related to the code here ^ : 
Closing all notion instance and using `Open in Windows app` in chrome open the app with the page opened before closing and not the one in chrome

Performance question : is it possible to improve the time required to open a new tab ? using notion:navigate-to-url to change an opened one is super fast while opening a new tab take a long time. Maybe it is possible to duplicate the tab and then change the page ?

I'm on your discord server if needed : DenisD3D#6912

Denis

**Comment by FekketCantenel** [comment]
I'm on Linux and would very much like the 'replace current window' option. It should also work whether the window is visible or hidden to the tray.
