### ISSUE TITLE
Add-on title sidebar can't be closed (">>" missing)

### ISSUE THREAD

**Issue by reVoniaC** [notion-enhancer/desktop#578]
**describe the bug**
Since this morning, the add-on side panel (on the right) that shows the table of contents can't be closed. The ">>" icon which should appear on hover can't be found.
I may have accidentally pressed a hotkey by accident when I was moving my PC between rooms.

**expected behaviour**
The side panel (on the right) should be able to open and close by clicking the ">>" or "<<" icon which appears on hover, just like the menu sidebar (on the left).

**screenshots**
This is how the my side panel (on the right) looks like on hover. I hovered everywhere within the panel but the ">>" icon isn't showing.
![image](https://user-images.githubusercontent.com/20645394/132544412-3e380e74-5fdd-4974-8a15-7c068ecda963.png)

This is what should happen: a "<<" icon that appears on hover and can close the sidebar/panel.
![image](https://user-images.githubusercontent.com/20645394/132544601-c7f20c48-e840-4b91-9341-91ca5391468c.png)

**platform**
Windows 10 Home 19043.

**Comment by salamijason** [comment]
same thing for me as well. except the top section of the table of contents seems to be covered by the titlebar?
![image](https://user-images.githubusercontent.com/90419732/132753243-3dd354a2-e8ea-4223-b217-ee2b3c0b7ce7.png)

i've tried disabling integrated titlebar and disabling and re-enabling outliner. this happens when the app is in full screen as well.

**Comment by ayush729p** [comment]
Can confirm, I'm facing the same issue. I hope this gets fixed soon.
In the meanwhile, you can use "CTRL + Shift + \" to toggle the outliner right sidebar.

PS: its "CTRL + \" for the default left side bar from notion.

**Comment by DavidJoyDong** [comment]
Same for me, and I think that is a bug.
I guess it was sheltered by the Notion's title bar. 
![side_panel_bug ](https://user-images.githubusercontent.com/47232992/132945237-1b0d0690-fee5-48ad-ab81-baf7984f4013.png)

**Comment by l782993610** [comment]
Here is a solution:
First step: find the npm root of your node by typing `npm root -g` in the terminal, which is '/Users/amadeus/.nvm/versions/node/v16.7.0/lib/node_modules/' for me
Second setp: modify the file '/Your npm path/notion-enhancer/mods/side-panel/app.css'，change  line 14 to :`top: 37px`;
![image](https://user-images.githubusercontent.com/59809602/133010362-7e8d7153-d6fd-4ffc-9a68-b1d70ba215fa.png)
Finally : restart your notion.

**Comment by dragonwocky** [comment]
note: the filepath for the file you need to edit will be different if you are using notion-repackaged (which you should be - it has some important extra patches that aren't in the npm version yet).

you will find the enhancer in your `Notion Enhanced/resources/app/embedded_enhancer` folder - e.g. on windows it would probably be in `C:\Users\YourName\AppData\Local\Programs\Notion Enhanced`, on macOS it would be `/Applications/Notion Enhanced`

**Comment by reVoniaC** [comment]
@l782993610 Works perfectly, thanks so much!
@dragonwocky Thanks for the info!
