### ISSUE TITLE
sidebar outline doesn't clear when leaving article/returning to database view

### ISSUE THREAD

**Issue by FekketCantenel** [notion-enhancer/desktop#583]
I have the right-hand addon sidebar with outline enabled and pinned (e.g. doesn't only appear on hover). It displays as expected when viewing an article.

When I go back to a database view (e.g. `CTRL+[`), I expect the table of contents to empty itself out and/or disappear. Instead it is unchanged and continues to show the last article's outline. If I visit an article with no headers, it blanks as expected and remains blank.

I would fix this myself with CSS, but I can't find a way to tell via CSS selectors whether I'm viewing an article or am in a database view (e.g. Table, Board, List). So even simply adding a view-based class or data attribute to `.notion-frame` would be helpful.

**Comment by dragonwocky** [comment]
https://github.com/notion-enhancer/repo/commit/9a71eb94e23dd8cb02cd103c98f7eb8191ece251
