### ISSUE TITLE
right-to-left Not Working

### ISSUE THREAD

**Issue by AhmedMub** [notion-enhancer/desktop#589]
### right-to-left Not Working

right-to-left stopped working I tried to uninstall notion app as well as the notion-enhancer and reinstalling it but still doesn't work, I'm using window 10.

I hope there is a sort of a fix as all my rtl pages are messed up

![rtl](https://user-images.githubusercontent.com/32661307/134771444-47385ded-5271-42a0-99f5-6f2d540d0c83.png)

Please Help..
Thank you!

**Comment by dragonwocky** [comment]
A temporary solution is to disable the right-to-left extension, then create a .txt file with the content below, rename it to a .js file, and add it using the custom inserts mod:
```js

document.addEventListener('readystatechange', (event) => {
  if (document.readyState !== 'complete') return false;
  let queue = [];
  const DOCUMENT_OBSERVER = new MutationObserver((list, observer) => {
      if (!queue.length) requestIdleCallback(() => handle(queue));
      queue.push(...list);
    }),
    PAGE_OBSERVER = new MutationObserver(autoAlignPageContent);
  DOCUMENT_OBSERVER.observe(document.body, {
    childList: true,
    subtree: true,
  });
  function handle(list) {
    queue = [];
    for (let { addedNodes } of list) {
      if (
        addedNodes[0] &&
        addedNodes[0].outerHTML.includes('notion-page-content')
      ) {
        autoAlignPageContent();

        PAGE_OBSERVER.disconnect();
        PAGE_OBSERVER.observe(addedNodes[0], {
          childList: true,
          subtree: false,
        });
      }
    }
  }
  function autoAlignPageContent() {
    document
      .querySelectorAll(
        `.notion-page-content > div[data-block-id]:not([dir]):not(.notion-column_list-block),
        [placeholder="Untitled"]:not([dir]),
        .notion-column-block > div[data-block-id]:not([dir])`
      )
      .forEach((block) => block.setAttribute('dir', 'auto'));
    document
      .querySelectorAll(
        "div[placeholder='List'], div[placeholder='To-do']"
      )
      .forEach((item) => {
        item.style['text-align'] = '-webkit-auto';
      });
  }
});
```

**Comment by AhmedMub** [comment]
Thank you very much @dragonwocky It worked fine, but for a new line added must close reopen the page to have an effect.
Hope this extension gets fix soon!

**Comment by dragonwocky** [comment]
@AhmedMub I've updated the code above to work for new lines too.

**Comment by AhmedMub** [comment]
Really appreciated. Thanks, Tom @dragonwocky

**Comment by obahareth** [comment]
@dragonwocky I've received reports this is also affecting the Chrome extension, do you have any idea what the cause for this is, is this something we can patch?

**Comment by dragonwocky** [comment]
@obahareth the version of rtl used in the enhancer is significantly refactored from what is in the chrome extension, but I think it still works the same way, so a similar fix should do the trick: the problem is that we were only listening for changes to the page root, and when pages are initially loaded sometimes Notion puts in the entire HTML chunk in one go with the page root as a child of another element that's being appended.

Long story short the check to see if it should run the alignment function needs to also happen if a page root is a child of the appended node or if the appended node is the child of a page root. For the enhancer version, it was changing:
```js
addedNodes[0].className === 'notion-page-content'
```
to 
```js
(addedNodes[0].outerHTML.includes('notion-page-content') ||
    document.querySelector('.notion-page-content')?.contains?.(addedNodes[0]))
```

I'm guessing https://github.com/obahareth/notion-rtl/blob/master/src/index.js#L85 would need to be changed to something similar, e.g. (Not yet tested, but could do the trick.)
```js
return ROOT_LEVEL_CLASS_NAMES.some(className => node.outerHTML.includes(className)
    || document.querySelector('.' + className)?.contains?.(node));
```

**Comment by obahareth** [comment]
@dragonwocky Thanks for the prompt reply!

Do you think we could come up with a way to have one version of the RTL script? Perhaps using git modules or something like that?

That way both our repos could benefit from PRs and/or fixes to the RTL plugin. What do you think?

**Comment by dragonwocky** [comment]
@obahareth that could definitely be helpful!

At the moment I'm doing a significant port and rework of the enhancer [here](https://github.com/notion-enhancer/extension) to a Chrome extension though, which includes standardising/API-ifying some of the common things used across mods (e.g. the observer), which would shrink the code for the whole script down basically to only the contents of the alignment function + improve code performance and reliability. Once that's done I'm going to port that updated version of things back across to desktop to have the exact same repository of mods running in both environments (obviously with some platform-enabled features), with the only differences being the launchers that inject them into the website or the app.

Maybe after that's done we can revisit the idea? At that point, it may not be worth doing anymore if it depends on the enhancer's API. There is also the question: if the whole enhancer is available as an extension, would people need to install the standalone extension at all or could they just do RTL through the enhancer? I only just realised now that that might mean the extensions would be conflicting, I probably should have mentioned it to you sooner.

We could just keep them separate, or it might mean you could instead fully "merge" the project into the enhancer and point people towards it instead for both browser and desktop use. What would you like to do? (I'd be happy to add you to the enhancer team if you're willing - message me on discord to talk about that if you want, dragonwocky#8449.)

This is still at least a couple of months away from being release-ready anyway, so there's time to find a solution.

**Comment by obahareth** [comment]
@dragonwocky No worries about the conflicting thing, you were doing what's best for your users. I would like to join the enhancer team, I'll drop you a message on Discord.

**Comment by abduumad** [comment]
> 
> 
> A temporary solution is to disable the right-to-left extension, then create a .txt file with the content below, rename it to a .js file, and add it using the custom inserts mod:
> 
> ```js
> let queue = [];
> const DOCUMENT_OBSERVER = new MutationObserver((list, observer) => {
>     if (!queue.length) requestIdleCallback(() => handle(queue));
>     queue.push(...list);
>   }),
>   PAGE_OBSERVER = new MutationObserver(autoAlignPageContent);
> DOCUMENT_OBSERVER.observe(document.body, {
>   childList: true,
>   subtree: true,
> });
> function handle(list) {
>   queue = [];
>   for (let { addedNodes } of list) {
>     if (
>       addedNodes[0] &&
>       (addedNodes[0].outerHTML.includes('notion-page-content') ||
>         document.querySelector('.notion-page-content')?.contains?.(addedNodes[0]))
>     ) {
>       autoAlignPageContent();
> 
>       PAGE_OBSERVER.disconnect();
>       PAGE_OBSERVER.observe(addedNodes[0], {
>         childList: true,
>         subtree: false,
>       });
>     }
>   }
> }
> function autoAlignPageContent() {
>   document
>     .querySelectorAll(
>       `.notion-page-content > div[data-block-id]:not([dir]):not(.notion-column_list-block),
>         [placeholder="Untitled"]:not([dir]),
>         .notion-column-block > div[data-block-id]:not([dir])`
>     )
>     .forEach((block) => block.setAttribute('dir', 'auto'));
>   document
>     .querySelectorAll("div[placeholder='List'], div[placeholder='To-do']")
>     .forEach((item) => {
>       item.style['text-align'] = '-webkit-auto';
>     });
> }
> ```

it worked for me too! thank you @dragonwocky

**Comment by mohamed12345samy** [comment]
it's not working with me, please. Can you explain the way in detail? @AhmedMub @abduumad

**Comment by mohamed12345samy** [comment]
I downloaded the notion enhancer again and created a .txt file with the content, but the app didn't open.
What's the solution, please? @dragonwocky

**Comment by dragonwocky** [comment]
@mohamed12345samy first please make sure that you are using notion-repackaged, not the version from npm. Second it needs to be a `.js` file, not a `.txt` file, and you need to add it to the app by selecting it in the menu (custom inserts -> client-side js insert) for it to work.

**Comment by Rokakun** [comment]
@abduumad 
Thanks a lot, it worked for me. 

Is there is a way to make the text RTL inside special text blocks like code blocks?

**Comment by sornay** [comment]
> A temporary solution is to disable the right-to-left extension, then create a .txt file with the content below, rename it to a .js file, and add it using the custom inserts mod:
> 
> ```js
> let queue = [];
> const DOCUMENT_OBSERVER = new MutationObserver((list, observer) => {
>     if (!queue.length) requestIdleCallback(() => handle(queue));
>     queue.push(...list);
>   }),
>   PAGE_OBSERVER = new MutationObserver(autoAlignPageContent);
> DOCUMENT_OBSERVER.observe(document.body, {
>   childList: true,
>   subtree: true,
> });
> function handle(list) {
>   queue = [];
>   for (let { addedNodes } of list) {
>     if (
>       addedNodes[0] &&
>       (addedNodes[0].outerHTML.includes('notion-page-content') ||
>         document.querySelector('.notion-page-content')?.contains?.(addedNodes[0]))
>     ) {
>       autoAlignPageContent();
> 
>       PAGE_OBSERVER.disconnect();
>       PAGE_OBSERVER.observe(addedNodes[0], {
>         childList: true,
>         subtree: false,
>       });
>     }
>   }
> }
> function autoAlignPageContent() {
>   document
>     .querySelectorAll(
>       `.notion-page-content > div[data-block-id]:not([dir]):not(.notion-column_list-block),
>         [placeholder="Untitled"]:not([dir]),
>         .notion-column-block > div[data-block-id]:not([dir])`
>     )
>     .forEach((block) => block.setAttribute('dir', 'auto'));
>   document
>     .querySelectorAll("div[placeholder='List'], div[placeholder='To-do']")
>     .forEach((item) => {
>       item.style['text-align'] = '-webkit-auto';
>     });
> }
> ```

Thanks.
This worked for me. But in toggle list it looks like this, could you fix this as well?
![image](https://user-images.githubusercontent.com/22280669/137373138-1d393f10-ec0d-4962-8328-8c58937bba6e.png)

**Comment by NinjaDark4411** [comment]
what is a custom inserts mod

**Comment by dragonwocky** [comment]
@NinjaDark4411 please don't comment on closed issues - they're closed for a reason 🙂

The custom inserts mod no longer exists. You can add custom CSS via the tweaks mod, but custom JS isn't currently possible, since the Chrome Web Store doesn't currently allow for executing user-provided code with manifest v3 browser extensions.

If you're having issues with the right-to-left mod, try asking in the Discord first to check what you're doing is right, otherwise please open a new issue with as much detail about what's going wrong as you can provide. Thanks!
