### ISSUE TITLE
Simpler databases extension stopped working

### ISSUE THREAD

**Issue by Enderlouis** [notion-enhancer/desktop#594]
**describe the bug**
Yesterday my Simpler Databases extension stopped working, I can't see the "gear" icon to hide things. I tried turning it off and on again, reinstalled the app and nothing seems to fix it. 

**expected behaviour**
It was perfect yesterday morning, but when I opened the app in the evening it had stopped working.  You can see my Dashboard in the screenshot below. 

**screenshots**
![Bug-report](https://user-images.githubusercontent.com/91395630/135092776-2b5bd2a0-9816-4686-b97e-af3ca6a8f37d.jpg)

**platform**
Windows 10

**Comment by gemanrioaks** [comment]
same!!

**Comment by vnavone** [comment]
Just installed and it doesn't work for me either.  I was really looking forward to it!  MacOS (intel).

**Comment by williamgomberg** [comment]
Am experiencing this same issue. Not quite sure exactly how long ago the issue started, my apologies for that, but I know that it used to work and must have disappeared sometime in the last ~4 weeks.
