### ISSUE TITLE
Collapsible headers stoped working

### ISSUE THREAD

**Issue by jexcarlo** [notion-enhancer/desktop#595]
FILL OUT THIS TEMPLATE, REMOVING/REPLACING ALL NON-BOLD TEXT WITH YOUR OWN INFORMATION.
BE AS CLEAR AND CONCISE AS POSSIBLE.

**describe the bug**
The toggles from "collapsible headers" are gone, even when the extension is on and now isn't possible to collapse my headers

**expected behaviour**
The extension should be working

**screenshots**
![image](https://user-images.githubusercontent.com/91605850/135260739-6a671a3e-d6e0-4b3c-8561-8bec4a18d554.png)

**platform**
windows 10

**Comment by Nouuu** [comment]
Same on Linux

**Comment by Abbabon** [comment]
Same on MacOS Big Sur (11.6)
