### ISSUE TITLE
notion-enhancer Outliner not working

### ISSUE THREAD

**Issue by NohemiSM** [notion-enhancer/desktop#596]
FILL OUT THIS TEMPLATE, REMOVING/REPLACING ALL NON-BOLD TEXT WITH YOUR OWN INFORMATION.
BE AS CLEAR AND CONCISE AS POSSIBLE.

**describe the bug**
I was using notion when I noticed the right side bar empty, I have the notion enhancer with the Outliner because I rely heavily in Titles and subtitles to structure long notes, and I love the Outliner  / Table of contents to browse on my notes.   
At some point I noticed the last heading I added was not present in the Outliner,   on the right side of the notion page. ... I closed and opened notion and the right side  of the page is empty.    
I uninstalled, reinstalled Notion, also I ran the instructions to install notion enhancer again, I've followed https://www.youtube.com/watch?v=vcwUpwpQ2sY&t=1s
and edit the two files    client.js and createwindow.js    and the notion opens and I can enable / disable other notion enhancer features, but the right side where the Outliner / Table of contents should show, it is empty    sad face.

**expected behaviour**
I expect to see the Table of contents / outlines and be able to click on the entries and go to that exact part of the page.

**screenshots**
if applicable, add screenshots of your problem.
![image](https://user-images.githubusercontent.com/65468717/135336290-5bc552eb-8b18-4a2b-8c57-2fda49f72cda.png)

**platform**
Windows 10

**Comment by NohemiSM** [comment]
Oh!  the issue seemed fixed for a little time..    I restarted and the Outliner / Table of contents are on.. 
but..  the Table of content is wrong:  

![image](https://user-images.githubusercontent.com/65468717/135336714-f29bd404-c677-4021-bdb3-a06bde868477.png)

In the screenshot, the note I am editing has a " 23 Sep " heading,  but this heading is not present in the Table of Contents.

**Comment by FekketCantenel** [comment]
This may be due to Notion's recent overhaul of comments (which also live in the sidebar). Using the inspector, I can see that the Outliner HTML is still there, just not being populated.

**Comment by FekketCantenel** [comment]
I upgraded to the newest [notion-repackaged](https://github.com/notion-enhancer/notion-repackaged) (2.0.16-5) but am still having this issue.

Note that if you refresh Notion (CTRL+R or F5) while viewing a page with headers, the table of contents will populate, but then won't update or clear when moving to other pages.

**Comment by RichardChenW** [comment]
> Oh! the issue seemed fixed for a little time.. I restarted and the Outliner / Table of contents are on.. but.. the Table of content is wrong:
> 
> ![image](https://user-images.githubusercontent.com/65468717/135338032-89977932-e261-4f3b-a6b9-021976b1cd0a.png)
> 
> In the screenshot, the note I am editing has a " 23 Sep " heading, but this heading is not present in the Table of Contents.

how did you fix it ?
