### ISSUE TITLE
Notion 2.0.17 infinite loading when tabs extension is active

### ISSUE THREAD

**Issue by AmodeusR** [notion-enhancer/desktop#606]
**describe the bug**

Notion doesn't load when *Multiple Tabs* extension is activated.

**expected behaviour**

Not having an infinite load on Notion launch.

**screenshots**

[bug print - infinite loading](https://ibb.co/qm0PXCY)

**platform**

 Windows 10 64 bits

**Comment by dragonwocky** [comment]
@AhmedMub if you are using notion-repackaged it shouldn't auto-update.

**Comment by dragonwocky** [comment]
@AmodeusR yes. however, the older one is just a .exe, so it's a much easier install than if you used the command line.

**Comment by Apolsus** [comment]
Now Notion has **officially launched** a formal tabbed function. But this function **doesn't seem to work** properly. Maybe we can develop tabs based on the new version.

**Comment by dragonwocky** [comment]
> But this function doesn't seem to work properly.

Well, yes. The notion-enhancer hasn't been updated to work with it yet. From the #announcements channel of the notion-enhancer's Discord server:
![image](https://user-images.githubusercontent.com/16874139/218932235-819d3009-8bb2-4854-ae65-d5b4a80ee8c0.png)
