### ISSUE TITLE
Tab title flickers when in preview mode

### ISSUE THREAD

**Issue by theisjendal** [notion-enhancer/desktop#609]
**describe the bug**
When the tab extension is activated and you open a page in preview mode, the tab name will start flickering between notion.so and the name of the parent page.

**expected behavior**
Either the name should be that of the parent or of the previewed page but definitely not flickering.

**platform**
I am running Manjaro KDE w/ kernel 5.10.68-1-MANJARO and version 2.0.16-7 of notion according to the aur repository.
I've encountered this error on two different Manjaro systems.

**Comment by Skotman** [comment]
Likewise, though I am on windows 10

**Comment by kaylamillerdev** [comment]
I'm seeing the same issue. I'm on the latest build of windows 10
