### ISSUE TITLE
rtl table of contents

### ISSUE THREAD

**Issue by yitzchoklowy** [notion-enhancer/desktop#616]
when using the rtl module table of contents indent for header levels doesn't work, it would be really helpful if it could work.

english toc
![image](https://user-images.githubusercontent.com/8303472/136988509-86589610-560f-46fb-8dc9-43662f6d4a8a.png)
hebrew toc
![image](https://user-images.githubusercontent.com/8303472/136988629-935d4ade-aea9-4fed-bfef-93d0413a6bc9.png)

**Comment by dragonwocky** [comment]
Bug re-observed in notion-enhancer v0.11.0 with the latest Notion updates (reported in Discord, replicated with a quick test).

**Comment by dragonwocky** [comment]
![image](https://github.com/notion-enhancer/notion-enhancer/assets/16874139/c30e95bd-9c6e-477f-ba95-a82b698ee41e)
Fixed in https://github.com/notion-enhancer/notion-enhancer/commit/6ceca21be391a7c23fe5e322f30ef84e33b3cfec.
