### ISSUE TITLE
Taps doesn't work

### ISSUE THREAD

**Issue by BaselCS** [notion-enhancer/desktop#646]
I can't ues tap  Feature in notion notion enhancer If I close the tap feature It work 

**screenshots**
![Screenshot_2](https://user-images.githubusercontent.com/93922382/140747241-3cbcf068-38b6-4c57-87d5-26b60cb9d6ba.png)
![Screenshot_3](https://user-images.githubusercontent.com/93922382/140747260-31826728-8129-4e92-9eab-7cca56f47dbc.png)

windows 10

**Comment by dragonwocky** [comment]
see https://github.com/notion-enhancer/desktop/issues/606, use notion-repackaged instead of manually patching if you aren't already.
