### ISSUE TITLE
Databases have grey line on top

### ISSUE THREAD

**Issue by yuvaldadon** [notion-enhancer/desktop#649]
**describe the bug**
Under each database title there is a grey line across the screen. This happens on every theme.
(also a small weird dent on the left of it).

**expected behaviour**
Line should not be there.

**screenshots**
![image](https://user-images.githubusercontent.com/80153715/142664523-feabd39a-e24c-4cb1-811b-6a037b076d01.png)

**platform**
Windows 10

**Comment by hariiprasath** [comment]
I got the same issue.
I tried inspecting to see if there is any custom CSS that can be added to fix this, but from the looks of it, the bg color attributes are added as element style and not in association with any particular class.

Here is what it looks like by default:
![before bg](https://user-images.githubusercontent.com/10820205/142817741-81d3802f-08c4-419b-a1d9-da4ceaa96ea5.png)

and after turning off the bg color:
![after bg](https://user-images.githubusercontent.com/10820205/142817734-c3c6616f-fdaf-4671-b0a5-25708932e39f.png)

Does anyone know how to write this change into custom CSS?

**Comment by imsumoregn** [comment]
Can you show us which file does that bg css thing come from? @hariiprasath I will make a pr to fix that.

**Comment by hariiprasath** [comment]
> Can you show us which file does that bg css thing come from? @hariiprasath I will make a pr to fix that.

umm.. I kinda don't know how to find out anything beyond the inspect element. 
The gradient is added under element style. So it's probably added by some js and not from a CSS file?

![Alt Text](https://c.tenor.com/uwo1nSOxPC8AAAAM/smile-kaylani-cole-jones.gif)

**Comment by Hamzailer** [comment]
Any updates?

**Comment by palerski** [comment]
i have the same problem using notion repackaged, any fixes?

**Comment by bryter-development** [comment]
As a _temporary_ fix until we get something properly made, I've inserted a small clause at the bottom of my theme (pastel-dark in this case).

`
div[style*="linear-gradient"] {
    background: transparent !important;
} 
`

This is a dirty fix, but for the moment will override the element settings on those databases.
