### ISSUE TITLE
No icon shown in windows 11 taskbar

### ISSUE THREAD

**Issue by ahmednrana** [notion-enhancer/desktop#652]
FILL OUT THIS TEMPLATE, REMOVING/REPLACING ALL NON-BOLD TEXT WITH YOUR OWN INFORMATION.
BE AS CLEAR AND CONCISE AS POSSIBLE.

**describe the bug**
No icon shown in windows 11 taskbar 

**expected behaviour**
An icon should be shown.

**screenshots**
![image](https://user-images.githubusercontent.com/21101759/142750618-ac1aea9f-6ec1-499c-b1c8-4e4306e4994b.png)

**platform**
Windows 11

**Comment by dragonwocky** [comment]
https://github.com/notion-enhancer/notion-repackaged/issues/13
