### ISSUE TITLE
NEW TO NOTION ENHANCER - STUCK ON INSTALLATION

### ISSUE THREAD

**Issue by sadevictoria** [notion-enhancer/desktop#653]
what is the bug - what happens?
I'm trying to download and install the enhancer on my Macbook and failing pretty spectacularly. I've tried following all the guides and several videos but to no avail. I just keep getting error messages spat at me :/ 

why is this a bug - what should be happening?
As I have followed everything correctly, the app should launch and be usable however it is now.

**screenshots**
<img width="568" alt="Screenshot 2021-11-21 at 14 04 47" src="https://user-images.githubusercontent.com/94791713/142765110-2dd8e16f-9bed-45d2-8494-a44b66cf05b4.png">
<img width="255" alt="Screenshot 2021-11-21 at 14 04 21" src="https://user-images.githubusercontent.com/94791713/142765116-c60d75fb-c704-4aba-acc1-b59866c679be.png">

what OS are you using? e.g. windows 7, windows 10, WSL, ubuntu, arch linux, macOS
using macOS Big Sur version 11.6

Please help!! I know nothing about code or techy stuff...

**Comment by dragonwocky** [comment]
at the moment, the only stable way to install the enhancer is via https://github.com/notion-enhancer/notion-repackaged

download and install the .dmg here: https://github.com/notion-enhancer/notion-repackaged/releases/download/v2.0.16-5/Notion-Enhanced-2.0.16-5.dmg

then you may need to follow this guide to open, as the app is unsigned: https://support.apple.com/en-us/HT202491

an update is in the works that will fix a ton of bugs and come with much better instructions on installation :)
