### ISSUE TITLE
Notion-app-enhanced from AUR gets stuck at loading screen

### ISSUE THREAD

**Issue by BrockMckjs** [notion-enhancer/desktop#657]
Whenever I start notion-app-enhanced, it is constantly loading. I checked the console and nothing seemed to be wrong. I uninstalled all notion apps and dependencies but it doesn't seem to work. I have restarted my computer several times and have removed all possible notion files (.config) and it still wont work. I recently reset my computer to an earlier point in time via timeshift and then this is when the issue started. Is there another configuration or any sort of file that I should delete?

**screenshots**
![image](https://user-images.githubusercontent.com/53315238/143790326-c9d61007-48df-449c-b4d5-3cd49dc19874.png)

**platform**
Arch Linux on KDE Plasma X11

**edit**
upon further investigation, I found that there actually was a console error that was different from the website
![image](https://user-images.githubusercontent.com/53315238/143792398-9d46d208-e7f2-4995-a3e7-6bb12e6d84f0.png)

**edit**

I have gone through all 1 TB of my file system and have scanned my root directory for every possible file notion could have created and then reinstalled. Same issue. Other notion apps work but the enhancer won't work with them. The only ones that don't work are from this repository. I'm not entirely sure what's going on, but it was working on my machine a few days ago. I'm guessing that it is an issue with Arch since it works fine on other distros and OSs. If anyone knows of any possible file, setting, etc. that could be causing this error that is in the console or any hidden error that I have not mentioned or found, info would be appreciated.

**Comment by dragonwocky** [comment]
does disabling tabs help? (try deleting `~/.notion-enhancer` to reset configuration)

**Comment by BrockMckjs** [comment]
> does disabling tabs help? (try deleting `~/.notion-enhancer` to reset configuration)

no, this did not work

**Comment by BrockMckjs** [comment]
The appimage does the same thing, too.

**Comment by BrockMckjs** [comment]
> The appimage does the same thing, too.

installing it via wine works, but it doesnt really qualify as usable.

**Comment by juam-sv** [comment]
same problem here on garuda linux.

**Comment by joyhumin** [comment]
same problem here on Arch Linux.

**Comment by lampask** [comment]
Same problem on  Arch Linux 5.15.5-arch1-1.

**Comment by PranaKnight** [comment]
Yup, same here

**Comment by jackchealdang** [comment]
same problem, arch linux 5.15.5-arch1-1

**Comment by dragonwocky** [comment]
seems related to https://github.com/notion-enhancer/desktop/issues/657 and https://github.com/notion-enhancer/desktop/issues/606
