### ISSUE TITLE
Notion Enhancer working, app not relaunching though

### ISSUE THREAD

**Issue by Itzabee** [notion-enhancer/desktop#658]
FILL OUT THIS TEMPLATE, REMOVING/REPLACING ALL NON-BOLD TEXT WITH YOUR OWN INFORMATION.
BE AS CLEAR AND CONCISE AS POSSIBLE.

**describe the bug**
what is the bug - what happens?

I followed every step when downloading the notion-enhancer, and when I first downloaded it and updated the coding the notion app opened up just fine. Once I started adding some enhancements to the app though, and hit relaunch, the notion app in itself won't open anymore no matter how many times I relaunch it. So at first it worked after all the extra coding, but once enhancements I added from the notion-enhancement page, it refuses to open.

**expected behaviour**
why is this a bug - what should be happening?

Once I relaunch the app, and apply all the enhancements, the notion app should open up but it's not. 

**screenshots**
if applicable, add screenshots of your problem.

https://www.notion.so/hack-notion-enhancer-v0-10-2-to-work-with-notion-s-v2-0-13-2-0-16-app-a4ab1267e67b4126b6448641ca4a0041

I used these instructions that were given by the dev, and it initially worked but now the app won't open after apply enhancements.

**platform**
what OS are you using? e.g. windows 7, windows 10, WSL, ubuntu, arch linux, macOS

I am using Mac OS

**Comment by dragonwocky** [comment]
yeah those instructions don't work anymore. the only way to use a working version of the enhancer until v0.11.0 releases is to use notion-repackaged: https://github.com/notion-enhancer/notion-repackaged/releases/tag/v2.0.16-5

the instructions do say that.
![image](https://user-images.githubusercontent.com/16874139/143969348-3b7cb273-9055-476c-a718-2aeb2b561250.png)
