### ISSUE TITLE
stuck at loading screen

### ISSUE THREAD

**Issue by notprash** [notion-enhancer/desktop#662]
**describe the bug**
I am stuck at loading screen

**expected behaviour**
Just normally sign into notion

**screenshots**
![image](https://user-images.githubusercontent.com/67903361/144871977-a57c9d01-dc72-4a28-9166-04a3063eb1de.png)

**platform**
Arch linux

**Comment by dragonwocky** [comment]
please dont open multiple issues for the same problem.
https://github.com/notion-enhancer/notion-repackaged/issues/65
