### ISSUE TITLE
Integrated Titlebar - min/max/close buttons not showing

### ISSUE THREAD

**Issue by carloshenrgin** [notion-enhancer/desktop#664]
I enabled the integrated titlebar tweak and now my min/max/close buttons are not showing up.

The titlebar should be integrated and not yeeted out of existence

![image](https://user-images.githubusercontent.com/80416070/145211125-249c19a2-8730-48c4-9158-b3f8b3b3030e.png)

**platform**
windows 10

**Comment by dragonwocky** [comment]
@carloshenrgin did you also enable the "tiling window manager mode"? Because that option is specifically intended to "yeet the buttons out of existence".

**Comment by carloshenrgin** [comment]
Oh... I probably miss clicked it when I was putting my configurations on this PC. It worked, thank you and sorry for wasting your time
