### ISSUE TITLE
The font size of header is changed abruptly

### ISSUE THREAD

**Issue by STRUDYGRASS** [notion-enhancer/desktop#669]
use notion enhanced 2.016-5 for windows. Already test in a different PC, and have already getted same problem from other.
The header's font size is same as h3, whether the header is h1 or h2.
It happended abrutly today. please fix it
![Snipaste_2021-12-15_21-03-55](https://user-images.githubusercontent.com/34856217/146191520-0d5ab8bd-a2c9-4bcd-89c1-7708f3188e2e.jpg)
.

**Comment by dragonwocky** [comment]
...there have been literally 3 different issues for this same problem in the last 20 minutes. please check before opening a new issue. https://github.com/notion-enhancer/desktop/issues/668
a fix will be out with v0.11.0. until then you just gotta be patient, sorry.
