### ISSUE TITLE
notion-enhancer 字号显示不正常

### ISSUE THREAD

**Issue by UndertheSkyStone** [notion-enhancer/desktop#670]
![Quicker_20211215_211151](https://user-images.githubusercontent.com/86789000/146192883-68caa0a5-bd41-4d0b-949a-d31126947628.png)
如图所示，一级标题和普通文字的字号一样大

**Comment by dragonwocky** [comment]
...there have been literally 3 different issues for this same problem in the last 20 minutes. please check before opening a new issue. https://github.com/notion-enhancer/desktop/issues/668
a fix will be out with v0.11.0. until then you just gotta be patient, sorry.
