### ISSUE TITLE
The title of notion has all become smaller

### ISSUE THREAD

**Issue by LiYangSir** [notion-enhancer/desktop#671]
I found that after I used it, the title of notion all became smaller, and it only changed back after uninstalling all of them.
![image](https://user-images.githubusercontent.com/50188356/146193356-bb70b05f-c889-414f-adfb-12aaa84c0180.png)
![image](https://user-images.githubusercontent.com/50188356/146193553-ed61183f-e36d-4636-b1dd-e0786a86ec61.png)

**Comment by dragonwocky** [comment]
...there have been literally 3 different issues for this same problem in the last 20 minutes. please check before opening a new issue. https://github.com/notion-enhancer/desktop/issues/668
a fix will be out with v0.11.0. until then you just gotta be patient, sorry.
