### ISSUE TITLE
Dont see the installation guide on the page

### ISSUE THREAD

**Issue by CounterWay** [notion-enhancer/desktop#672]
Hello there, am wondering if there is an installation guide. I dont seem to see it anywhere.  Was it removed?

Thanks,

**Comment by dragonwocky** [comment]
currently, the only working installation method is to install the executable from https://github.com/notion-enhancer/notion-repackaged/releases/tag/v2.0.16-5 that matches your operating system (e.g. the `.exe` on windows).

you can find the old guide here in the master branch of the repo: https://github.com/notion-enhancer/desktop/tree/master

it has been removed from the dev branch of the repo in preparation for the nearly-ready v0.11.0, which comes with major changes compared to all other versions of the enhancer and the old documentation no longer applied to it.

new documentation is work in progress and will be available exclusively on http://notion-enhancer.github.io/ when it is ready (as there are multiple separate repositories here in github for different parts of the enhancer, so an external unified documentation will be better to maintain and easier to read/understand).

**Comment by yd-yin** [comment]
Thanks for your great work! 
And looking forward to the amazing content on http://notion-enhancer.github.io/!

**Comment by CounterWay** [comment]
Thank you. I will hold off until the new release will come. Appreciate your work on this. When do you think it will be ready by?

**Comment by dragonwocky** [comment]
@CounterWay soon. could be 2 days, could be 2 weeks.
