### ISSUE TITLE
Headers stopped working

### ISSUE THREAD

**Issue by jexcarlo** [notion-enhancer/desktop#675]
describe the bug
All headers on my Notion is showing just as simple text, the heigh of the block is still the same as a header, but the text looks like a ordinary text block. 

expected behaviour
The text should have the height of a header and not a simple text block

screenshots
*All text in bold is a header*
![image](https://user-images.githubusercontent.com/91605850/146940809-d2726654-0bfc-402c-9e26-a1f54a3feb92.png)

*How it should be*
![image](https://user-images.githubusercontent.com/91605850/146940965-2d430909-c83a-4914-83a9-27688981f06e.png)

platform
windows 10

**Comment by dragonwocky** [comment]
https://github.com/notion-enhancer/desktop/issues/668
