### ISSUE TITLE
right to left is nor working !! 🙂

### ISSUE THREAD

**Issue by eslamsolyman** [notion-enhancer/desktop#677]
![image](https://user-images.githubusercontent.com/96717304/147446468-08c452c3-8db2-4fbe-914c-fdb865772fc5.png)

**Comment by dragonwocky** [comment]
https://github.com/notion-enhancer/desktop/issues/589

**Comment by eslamsolyman** [comment]
still not fixed 

> #589

**Comment by dragonwocky** [comment]
@eslamsolyman yes, it was. the bug that was stopping it working in #589 has been fixed, a new bug has shown up now: https://github.com/notion-enhancer/repo/issues/49
