### ISSUE TITLE
collapsible headers CloudHill v1.0.0 breaks not working/all headers broken after disabling

### ISSUE THREAD

**Issue by HalilioG** [notion-enhancer/desktop#678]
When using Notion repackaged, and enabling collapsible headers (any combination of options) does not work, and just displays headers as bold text. This continues after disabling collapsible headers, and uninstalling/reinstalling the whole notion repackaged. Makes using notion repackaged painful, as all headers are just displayed as bold text (same size).
![image](https://user-images.githubusercontent.com/96741466/147492940-7952b347-afcb-49b6-98cf-bb409dae8696.png)

**Comment by dragonwocky** [comment]
https://github.com/notion-enhancer/desktop/issues
