### ISSUE TITLE
I can't use notion with "tabs", and some mods are ineffective.

### ISSUE THREAD

**Issue by Mipaaaaaaaaaaaaa** [notion-enhancer/desktop#679]
When I switch mod "tabs", the Notion will keep loading. And some mods such as "word counter" don't work even I relaunch it.

**Comment by dragonwocky** [comment]
https://github.com/notion-enhancer/desktop/issues/606 and others

we know lots of things are broken. everything is fixed in the v0.11.0 work-in-progress and will be released soon.
