### ISSUE TITLE
Opening a new window everytime I switch to the app?

### ISSUE THREAD

**Issue by yourlocalvirgo** [notion-enhancer/desktop#682]
Hi! I just installed the Mac version of this project, and noticed that everytime I minimize the application and switch back to it, it opens a new window of my workspace on top of the one I'm already running. I can't find a way around this. I've tried relaunching the app several times. 

Is anyone else having this issue?

**Comment by dragonwocky** [comment]
try disabling the "close to tray" option or using the `cmd+shift+a` keyboard shortcut to focus the window instead of the dock - it's a known bug that will be fixed in v0.11.0
