### ISSUE TITLE
[Crash] Manual Installation is broken?

### ISSUE THREAD

**Issue by Davoleo** [notion-enhancer/desktop#684]
**What is happening?**
Notion doesn't start but crashes with JavaScript error after applying `notion-enhancer`

**What should be happening?**
Notion should be launched correctly

**Screenshots (if applicable):**
![image](https://user-images.githubusercontent.com/24458276/147855096-c3cbc535-999e-456d-b3d7-9d00c02b9394.png)

**Operating system/browser name & version:** Windows 10 21H2

**notion-enhancer and/or notion-repackaged version:** `notion-enhancer/0.11.0 win32-x64/10.0.19044 node/v16.9.0`

**Comment by SalemNabeelSalem** [comment]
Can tell how to solve this problem ? @Davoleo

**Comment by dragonwocky** [comment]
can't currently be solved, it's a bug. until it's fixed use the notion-repackaged installation instead @SalemNabeelSalem

**Comment by faraazb** [comment]
I can get it to work by editing [this](https://github.com/notion-enhancer/desktop/blob/8e9442336d49cc74bbe46d4b4949fb7a7c1e7515/pkg/apply.mjs#L78) line to fix the inserted `require` statement as
```js
`\n\n//notion-enhancer\nrequire('notion-enhancer')('${target.replace(/\\/g, "/")}', exports, (js) => eval(js))`
// target.replace(/\\/g, "\\\\")} would also work I guess
```
I don't know if this is the best way but it shouldn't affect other platforms.

**Comment by miozus** [comment]
![circle-forever](https://user-images.githubusercontent.com/35659194/149702483-9c3035cc-f079-4e65-98f6-ef81619e37a9.png)

`require` :

backslash \ ⇒ slash /   

but it launched with circle round and round forever.

Not work on Windows 11 21H2 22000.434

**Comment by corp0ra1** [comment]
> I can get it to work by editing [this](https://github.com/notion-enhancer/desktop/blob/8e9442336d49cc74bbe46d4b4949fb7a7c1e7515/pkg/apply.mjs#L78) line to fix the inserted `require` statement as
> 
> ```js
> `\n\n//notion-enhancer\nrequire('notion-enhancer')('${target.replace(/\\/g, "/")}', exports, (js) => eval(js))`
> // target.replace(/\\/g, "\\\\")} would also work I guess
> ```
> 
> I don't know if this is the best way but it shouldn't affect other platforms.

yes, i can get it to work too. and i find the reason : 
1)after < notion-enhancer apply >,i check  the file <C:\Users\XXXX\AppData\Local\Programs\Notion\resources\app> , and as you see, there are something wrong with the path 
2)after i do as you  say ,the path is right and it work out.
![image](https://user-images.githubusercontent.com/35833862/153890788-6572b4bd-a9cc-4d62-b0a6-8fd5142e7a03.png)

**Comment by corp0ra1** [comment]
> I can get it to work by editing [this](https://github.com/notion-enhancer/desktop/blob/8e9442336d49cc74bbe46d4b4949fb7a7c1e7515/pkg/apply.mjs#L78) line to fix the inserted `require` statement as
> 
> ```js
> `\n\n//notion-enhancer\nrequire('notion-enhancer')('${target.replace(/\\/g, "/")}', exports, (js) => eval(js))`
> // target.replace(/\\/g, "\\\\")} would also work I guess
> ```
> 
> I don't know if this is the best way but it shouldn't affect other platforms.

yes, i can get it to work too. and i find the reason : 
1)after < notion-enhancer apply >,i check  the file <C:\Users\XXXX\AppData\Local\Programs\Notion\resources\app> , and as you see, there are something wrong with the path 
2)after i do as you  say ,the path is right and it work out.
![image](https://user-images.githubusercontent.com/35833862/153890788-6572b4bd-a9cc-4d62-b0a6-8fd5142e7a03.png)

**Comment by Vincen-31** [comment]
> 

I try this method, but the app doesn't show notion-enhancer like yours. My app's version is [Notion-Enhanced-2.0.18-1-win](https://github.com/notion-enhancer/notion-repackaged/releases/download/v2.0.18-1/Notion-Enhanced-2.0.18-1-win.zip).
And then I switch the version to [2.0.16.5](https://github.com/notion-enhancer/notion-repackaged/releases/download/v2.0.16-5/Notion-Enhanced-2.0.16-5-win.zip). Everything is ok.
![image](https://user-images.githubusercontent.com/60336738/223325120-6986066d-1f19-4b8b-8831-188e4d874758.png)
