### ISSUE TITLE
don't have this extra option in the Notion sidebar labelled

### ISSUE THREAD

**Issue by fsafaf** [notion-enhancer/desktop#685]
don't have this extra option in the Notion sidebar labelled
<img width="259" alt="iShot2022-01-02 01 19 20" src="https://user-images.githubusercontent.com/47275775/147856235-be2e65dc-d2b0-4521-8e79-e7f640ff2b4e.png">

i used this
<img width="768" alt="iShot2022-01-02 01 21 08" src="https://user-images.githubusercontent.com/47275775/147856265-f898de95-52f4-4044-959c-780aaa4cf16d.png">

how can i get it

**Comment by gerlinl** [comment]
I am seeing the same issue on Windows after it Notion Enhanced auto-updated with the latest version (2.0.18.0)
![Notion _Enhanced](https://user-images.githubusercontent.com/2956655/147856505-0c86f1dd-9a8f-4841-bc9f-0992364eee40.jpg)

**Comment by Broderick-Westrope** [comment]
I have a Windows 10 PC and Manjaro PC. Both of them auto updated which removed all the existing enhancements and I cannot see the "notion-enhancer" option in the sidebar.

**Comment by dragonwocky** [comment]
Go to the top of the installation instructions, read the warning and follow the instructions:
![image](https://user-images.githubusercontent.com/16874139/147863546-44db2f06-780c-4253-a23f-230eeebc14d7.png)
