### ISSUE TITLE
Portable Install forcing local install, Enhancer options not available in Notion 2.0.18-1, Notion-Enhancer v 0.11.0

### ISSUE THREAD

**Issue by ctkoakenleaf** [notion-enhancer/desktop#690]
BEFORE MAKING A BUG REPORT, PLEASE READ THE
[CONTRIBUTING](https://notion-enhancer.github.io/about/contributing) GUIDE.

BUG REPORTS ARE NOT FOR SUPPORT REQUESTS. IF YOU JUST NEED HELP,
ASK IN THE [DISCORD](https://discord.gg/sFWPXtA) SERVER.

BUG REPORTS THAT DO NOT PROPERLY FILL
IN THE TEMPLATE MAY BE IGNORED OR REJECTED.
YOU MUST DELETE ALL TEXT ON OR ABOVE THIS LINE BEFORE SUBMITTING.

**What is happening?**
Portable version of app loads the installer when trying to open the portable program. Installer installs as expected, but there appears to be no option within the notion app window to access the enhancer options. Also, the notion-enhancer system tray icon seems to be missing.

**What should be happening?**
Portable app should not need to be installed. Some way to intitutivitly access the notion-enhancer options should be accessable from the app window.

**Screenshots (if applicable):**

**Operating system/browser name & version:**
Windows 11 (build 22000.376)

**notion-enhancer and/or notion-repackaged version:**
Notion 2.0.18-1, notion-enhnacer 0.11.0

**notion-enhancer configuration (enabled/disabled mods and their settings):**
None, currently.

**Comment by dragonwocky** [comment]
How the portable app installs is out of our control, our executables are generated by electron-builder.

The tray icon is expected to be missing. It is now a mod that can optionally be turned on. See the [Basic Usage](https://notion-enhancer.github.io/getting-started/basic-usage/) guide for where to access the menu.

If you read the [installation instructions](https://notion-enhancer.github.io/getting-started/installation/) properly, there is a warning at the very top with an extra step for past users of the notion-enhancer. You need to delete the `.notion-enhancer` folder in your home/user directory.
