### ISSUE TITLE
Is there a setting option for run at startup?

### ISSUE THREAD

**Issue by Lucas-TY** [notion-enhancer/desktop#691]
BEFORE MAKING A FEATURE REQUEST, PLEASE READ THE
[CONTRIBUTING](https://notion-enhancer.github.io/about/contributing) GUIDE.

FEATURE REQUESTS THAT DO NOT PROPERLY FILL
IN THE TEMPLATE MAY BE IGNORED OR REJECTED.
YOU MUST DELETE ALL TEXT ON OR ABOVE THIS LINE BEFORE SUBMITTING.

**What makes the feature necessary?**
There was a startup option at tray in the old version, but I can't find that option in the newest version
**How would the feature work?**
Need a setting option for run at startup

**Comment by dragonwocky** [comment]
there is, under the "tray" mod in the menu.

**Comment by Lucas-TY** [comment]
![image](https://user-images.githubusercontent.com/48132189/147901378-55cf4aa2-b890-4995-9955-6fc213726267.png)
Thanks
Is that the menu you mentioned?

**Comment by dragonwocky** [comment]
no, in the notion-enhancer menu
![image](https://user-images.githubusercontent.com/16874139/147901495-49d53c45-038f-400b-9521-3885b105ade7.png)

**Comment by Lucas-TY** [comment]
Found it! Thank you!!

**Comment by CJayAcopra** [comment]
for some reason the option to start notion on starup doesnt work on popos, does anybody knows how to fix it? thanks
