### ISSUE TITLE
Indentation lines appearing on non-indented text

### ISSUE THREAD

**Issue by hariiprasath** [notion-enhancer/desktop#692]
**What is happening?**
Indentation lines are appearing on bulleted (or numbered or to-do list) blocks that are longer than one line.
![indent bug](https://user-images.githubusercontent.com/10820205/147906022-f81f472a-11cf-465a-8eb6-56e155aa518e.png)

**What should be happening?**
Indentation lines, as I understand, should appear only when a block is indented with a TAB and not for multi-line blocks.
![indent bug corrected](https://user-images.githubusercontent.com/10820205/147906123-1c44d258-77ca-4466-b0b3-6646895a8fda.png)

**Operating system name & version:**
Win10 x64 21H2

**notion-enhancer and/or notion-repackaged version:**
notion-enhancer v0.11.0-dev

**Comment by dragonwocky** [comment]
This is working correctly - the indentation lines are based on the bullet points, not on the content of the block.

**Comment by hariiprasath** [comment]
@dragonwocky oh, sorry, my bad. 
@runargs is there any custom insert I can use to remove the indentation lines from multi-line blocks and reserve them for only when there are children for a list item?

**Comment by hariiprasath** [comment]
I might sound fussy but I still feel like this (screenshots) behaviour of indentation lines is not how it should work. 

All expanded
![toggle](https://user-images.githubusercontent.com/10820205/148528667-48777538-e737-4287-8be9-0327f3c63635.png)
All collapsed
![toggle collapse](https://user-images.githubusercontent.com/10820205/148528709-b2da2c58-ae43-4925-936c-892de73018ea.png)
All but second expanded
![toggle 2 collapse](https://user-images.githubusercontent.com/10820205/148528761-7d9e6064-bdfe-4cab-a253-beed9465e1af.png)

**Comment by dragonwocky** [comment]
The indentation lines are not meant to represent actual tabbing/whitespace. They are a visual aid meant to connect parents blocks with their content - including both text & child blocks. The extension is working correctly, even if it that may not match up with how you imagine it should.
