### ISSUE TITLE
Can't update to 0.11

### ISSUE THREAD

**Issue by Spider-DT** [notion-enhancer/desktop#694]
OS: Win10 19041
Old enhancer version 0.10.2
---
**What is happening?**
run npm i -g notion-enhancer in cmd
but did not get update
**What should be happening?**
Enhancer version should be update to 0.11 
**Screenshots (if applicable):**
![image](https://user-images.githubusercontent.com/60735795/148002940-12982fdb-fdb0-4c82-a9e5-fd860f23c3c5.png)

**Comment by dragonwocky** [comment]
This looks like a cache issue on your side - `0.11.0` is the current version in the npm repository: https://www.npmjs.com/package/notion-enhancer.

However, manual installation is currently bugged (see https://github.com/notion-enhancer/desktop/issues/684) and using notion-repackaged instead is recommended.

**Comment by Spider-DT** [comment]
ok, Thanks, anyway @dragonwocky
