### ISSUE TITLE
sidebar

### ISSUE THREAD

**Issue by wqddg** [notion-enhancer/desktop#696]
The sidebar is full and cannot slide
![H_ECQ3IOHYVTPDD~MYSY7JQ](https://user-images.githubusercontent.com/50018362/148044200-a45b01e1-766f-4ec8-9811-1bbd1e2dc8a2.png)

**Comment by dragonwocky** [comment]
wrong place, doesn't explain the problem cohesively at all, and is likely a dup of https://github.com/notion-enhancer/repo/issues/30

please follow the [contributing guidelines](https://notion-enhancer.github.io/about/contributing/) or your bug reports / feature requests will be closed
