### ISSUE TITLE
Tabs is great, but not good enough for macOS

### ISSUE THREAD

**Issue by l782993610** [notion-enhancer/desktop#700]
![image](https://user-images.githubusercontent.com/59809602/148126755-4616f896-d5c4-47e0-a3c8-37a37f60935d.png)

**Comment by dragonwocky** [comment]
please update this to follow the [contributing guidelines](https://notion-enhancer.github.io/about/contributing/).

**Comment by l782993610** [comment]
As you can see, in macOS, with Tabs enabled, the tabs are obscured by the window control buttons, while the menu bar of the page does not move to the left (a 72px margin on the left)

**Comment by dragonwocky** [comment]
dup of https://github.com/notion-enhancer/repo/issues/28 but thanks for the 72px measurement
