### ISSUE TITLE
Feature request: Disabling spell checker

### ISSUE THREAD

**Issue by geoffrey45** [notion-enhancer/desktop#701]
**What makes the feature necessary?**
When working with lots of text that aren't necessarily english words like code, I get a lot of red lines when i'm editting content.

**How would the feature work?**
Maybe add a extension or a setting somewhere to toggle spell check on/off.

**Comment by l782993610** [comment]
Just right click on some where you can switch the spell check. Why is it necessary?

**Comment by dragonwocky** [comment]
![image](https://user-images.githubusercontent.com/16874139/148633007-e3562ec6-5f5f-4402-b1a8-801caa996f3c.png)
@l782993610 is right, there's already a disable spell check button built into notion
