### ISSUE TITLE
No notion-enhancer inside notion sidebar and no tab functionality either

### ISSUE THREAD

**Issue by nandudb** [notion-enhancer/desktop#702]
I have re-installed latest notion-enhancer 2.18 version and latest notion.app.
When i start with notion-enhancer, i dont see notion-enhancer in the sidebar and none of the functionality of notion-enhancer are available. Also wondering whether 'Tab' functionality in notion-enhancer is no longer available?

![image](https://user-images.githubusercontent.com/8333356/148245378-1556d905-5575-4675-a47d-083e13a48aa5.png)

**Comment by spencershastings** [comment]
I'm having the same issue. Even the manual installation is not working. Notion is working just fine, but it's like Enhancer is non existent and I've followed all the steps.

**Comment by moonrambler** [comment]
Me too.  Node has been upgraded to 16+. And it doesn't work.

**Comment by jrykner** [comment]
Same as mentioned

**Comment by dragonwocky** [comment]
manual installation is bugged as per https://github.com/notion-enhancer/desktop/issues/684

the menu not showing up in the sidebar is not a bug and is expected **if you did not follow the "warning" at the top of the installation instructions on the website**. please read the instructions properly.

**Comment by mkh66346263** [comment]
> 

I follow the instructions and the issue sill happend.

**Comment by dragonwocky** [comment]
@mkh66346263 see https://github.com/notion-enhancer/desktop/issues/762
