### ISSUE TITLE
JavaScript Error

### ISSUE THREAD

**Issue by oneano** [notion-enhancer/desktop#705]
BEFORE MAKING A BUG REPORT, PLEASE READ THE
[CONTRIBUTING](https://notion-enhancer.github.io/about/contributing) GUIDE.

BUG REPORTS ARE NOT FOR SUPPORT REQUESTS. IF YOU JUST NEED HELP,
ASK IN THE [DISCORD](https://discord.gg/sFWPXtA) SERVER.

BUG REPORTS THAT DO NOT PROPERLY FILL
IN THE TEMPLATE MAY BE IGNORED OR REJECTED.
YOU MUST DELETE ALL TEXT ON OR ABOVE THIS LINE BEFORE SUBMITTING.

**What is happening?**
Javascript error in the attached image
**What should be happening?**
Notion should run , but has the error
**Screenshots (if applicable):**
![v](https://user-images.githubusercontent.com/8225652/148323381-ef87af4a-57d3-4a6a-b22e-f75f41dec971.png)

**Operating system/browser name & version:**
windows 10 latest

**notion-enhancer and/or notion-repackaged version:**
notion-enhancer
**notion-enhancer configuration (enabled/disabled mods and their settings):**
I do not know

**Comment by miozus** [comment]
After updating notion-enhancer by commandline, the Same Isuue I met, I follow the Exception and change separator `\` to `/` at two files which shown in MsgBox.

Then Notion launchs with launching cirlcle circling forever. **Not sovled.**

Windows 11 21H2 22000.376

**Comment by dragonwocky** [comment]
dup of https://github.com/notion-enhancer/desktop/issues/684#issuecomment-1004797099
