### ISSUE TITLE
weekly calendar view is not working

### ISSUE THREAD

**Issue by zziiheenn** [notion-enhancer/desktop#707]
BEFORE MAKING A BUG REPORT, PLEASE READ THE
[CONTRIBUTING](https://notion-enhancer.github.io/about/contributing) GUIDE.

BUG REPORTS ARE NOT FOR SUPPORT REQUESTS. IF YOU JUST NEED HELP,
ASK IN THE [DISCORD](https://discord.gg/sFWPXtA) SERVER.

BUG REPORTS THAT DO NOT PROPERLY FILL
IN THE TEMPLATE MAY BE IGNORED OR REJECTED.
YOU MUST DELETE ALL TEXT ON OR ABOVE THIS LINE BEFORE SUBMITTING.

**What is happening?**

weekly calendar view is not working

**What should be happening?**

Weekly calendar view doesn't work both inline and Full page.
I've tried reloading it multiple times, but it's didn't work.

**Screenshots (if applicable):**

<img width="836" alt="스크린샷 2022-01-08 03 47 56" src="https://user-images.githubusercontent.com/97306365/148592349-88b4b5ee-f84d-4094-858d-fa72a594dfac.png">

<img width="959" alt="스크린샷 2022-01-08 03 48 04" src="https://user-images.githubusercontent.com/97306365/148592386-5177ae7d-a1bd-4a4b-9366-7cb4307b60b7.png">

**Operating system/browser name & version:**
Mac Os Application

**notion-enhancer and/or notion-repackaged version:**
notion-enhancer 2.0.18-1

**notion-enhancer configuration (enabled/disabled mods and their settings):**

**Comment by dragonwocky** [comment]
....that's a table view. weekly calendar view only works on **calendar** views.
