### ISSUE TITLE
Column headers in table are not aligning

### ISSUE THREAD

**Issue by KristalMDow** [notion-enhancer/desktop#708]
**What is happening?**
For any table, in any view, on any page, the column headers do not align with the column content.

**What should be happening?**
Column header should align with rest of column.

**Screenshots (if applicable):**
![image](https://user-images.githubusercontent.com/30303538/148598550-e8644b78-34c1-4c69-a460-86e58c6c19bb.png)

**Operating system/browser name & version:**
This is the App, Windows 10. 

**notion-enhancer and/or notion-repackaged version:** 
notion-enhancer v0.11.0

**notion-enhancer configuration (enabled/disabled mods and their settings):**
All on default settings: tweaks, integrated titlebar, tray, tabs, always on top, view scale, scroll to top, simpler databases, emoji sets, code line numbers, calendar scroll, collapsible headers, collapsible properties, weekly view, truncated titles, focus mode, global block links, 

light+ theme

No integrations

**Comment by KristalMDow** [comment]
Follow up after further testing: I was able to isolate this to the tweaks mod, specifically the "wrap tables to page width" setting

**Comment by dragonwocky** [comment]
dup of https://github.com/notion-enhancer/repo/issues/32
