### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by Mystik01** [notion-enhancer/desktop#710]
BEFORE MAKING A BUG REPORT, PLEASE READ THE
[CONTRIBUTING](https://notion-enhancer.github.io/about/contributing) GUIDE.

BUG REPORTS ARE NOT FOR SUPPORT REQUESTS. IF YOU JUST NEED HELP,
ASK IN THE [DISCORD](https://discord.gg/sFWPXtA) SERVER.

BUG REPORTS THAT DO NOT PROPERLY FILL
IN THE TEMPLATE MAY BE IGNORED OR REJECTED.
YOU MUST DELETE ALL TEXT ON OR ABOVE THIS LINE BEFORE SUBMITTING.

**What is happening?**
Installed through NPM, opened Notion and error.
**What should be happening?**
It should work.
**Screenshots (if applicable):**
![image](https://user-images.githubusercontent.com/65687597/148688371-7aeaa81e-f3d0-4887-a110-e4b67c968fe6.png)

**Operating system/browser name & version:**

**notion-enhancer and/or notion-repackaged version:**

**notion-enhancer configuration (enabled/disabled mods and their settings):**

**Comment by dragonwocky** [comment]
https://github.com/notion-enhancer/desktop/issues/684
