### ISSUE TITLE
Notion Enhanced does not "activate" on Linux

### ISSUE THREAD

**Issue by alimosallaei19** [notion-enhancer/desktop#711]
**What is happening?** I am on PopOS v21.10, and have installed the Notion-Enhanced `.deb` file. However, when I open the app, it looks like regular Notion, and none of the keyboard shortcuts I am trying are working (Alt+E, Ctrl+E, SUPER+E) to open up the settings panel. 

**What should be happening?** Notion Enhanced should be "activating", as in taking over regular Notion. There should be a Notion Enhanced tab at the top left, along with keyboard shortcuts working to open up the settings panel. 

**Screenshots (if applicable):**
![image](https://user-images.githubusercontent.com/63680409/148712256-71b965e3-c546-4d3e-a547-8e18e30ef8f6.png)

**Operating system/browser name & version:** Pop!_OS v21.10, Arch x64, Linux Kernel 5.15.8

**notion-enhancer and/or notion-repackaged version:** Notion-App-Enhanced v2.0.18 (318.4mb) - amd64 and arm64 deb files tried.

**notion-enhancer configuration (enabled/disabled mods and their settings):** N/A

**Comment by dragonwocky** [comment]
does following the warning at the top of the installation instructions help?
![image](https://user-images.githubusercontent.com/16874139/148713707-13a04a65-bc1b-417c-80c4-b11f8247753f.png)

**Comment by alimosallaei19** [comment]
That did work! I did see the message in the docs about that but got a bit lost when the desktop version of notion-enhancer for Linux was v2 instead of v0.11. Thanks for your help!

**Comment by dragonwocky** [comment]
The Notion app (v2.0.18-1) is versioned separately to the included notion-enhancer (v0.11.0).

**Comment by 21um1er3** [comment]
> does following the warning at the top of the installation instructions help? ![image](https://user-images.githubusercontent.com/16874139/148713707-13a04a65-bc1b-417c-80c4-b11f8247753f.png)

Hi ! I have the same problem - the "enhancer" tab does not appear. Already watched ALL the videos and reread the manual CAREFULLY. All "Warrning" followed. Please help :)
![NVIDIA_Share_CTeXFQhrpB](https://user-images.githubusercontent.com/97348672/172372606-35e1f089-ba1c-4a44-9073-85e010016e00.jpg)

**Comment by dragonwocky** [comment]
@21um1er3 please do not bump closed issues, you are encountering a new problem here, not the same as this one. See https://github.com/notion-enhancer/desktop/issues/762.
