### ISSUE TITLE
Bar not following theme colors

### ISSUE THREAD

**Issue by Dedsd** [notion-enhancer/desktop#715]
Plataform: Linux x64
Bug: All the themes now appear with this bar not following the colors
![image](https://user-images.githubusercontent.com/71463162/150126773-1869b4bf-d1d1-4221-963a-d6c2267b275c.png)

**Comment by dragonwocky** [comment]
dup of https://github.com/notion-enhancer/desktop/issues/715

**Comment by Dedsd** [comment]
What?

**Comment by dragonwocky** [comment]
this bug has already been reported in a separate issue. this issue a) was opened in the wrong place, b) was opened after the other one already existed and c) doesn't follow the template provided for issues, so it has been closed in favour of the other one.

**Comment by dragonwocky** [comment]
sorry, I meant https://github.com/notion-enhancer/repo/issues/37
