### ISSUE TITLE
title bar overlapping with macOS windows buttons

### ISSUE THREAD

**Issue by saikatm** [notion-enhancer/desktop#717]
image is attached below.
macOS: BigSur 11.1
Notion Enhanced Version: Version 2.0.18-1 (2.0.18-1)

![image](https://user-images.githubusercontent.com/9909763/150185514-2e9dfa6d-d2f9-49c1-8701-bd2738f640af.png)
![image](https://user-images.githubusercontent.com/9909763/150185677-b6e2ca34-4fd2-4e29-a7a2-9d0ae57d7e2d.png)

**Comment by dragonwocky** [comment]
https://github.com/notion-enhancer/repo/issues/28
