### ISSUE TITLE
The Outliner's indent is weird even some titles have same label

### ISSUE THREAD

**Issue by aptx113** [notion-enhancer/desktop#718]
**What is happening?**
The titles with the same label in the outliner have different indents.  
   
**What should be happening?**
They should have same indent if they are both labeled H1 for example.

**Screenshots (if applicable):**
![截圖 2022-01-21 上午10 17 15](https://user-images.githubusercontent.com/56501046/150454991-75fba667-ebc1-4b6f-8c53-e4068446b021.png)

**Operating system/browser name & version:**
macOS Monterey 12.1

**notion-enhancer and/or notion-repackaged version:**
Notion-Enhanced-2.0.18-1

**notion-enhancer configuration (enabled/disabled mods and their settings):**
tabs, outliner, scroll to top, word counter, code line numbers, collapse headers, Global block link are enable

**Comment by dragonwocky** [comment]
dup of https://github.com/notion-enhancer/repo/issues/30
