### ISSUE TITLE
Pinned NED doesn't invoke NED but just Notion

### ISSUE THREAD

**Issue by ruby-rust-perl** [notion-enhancer/desktop#719]
# What is happening?

I am using the portable version of `notion-enhancer desktop` in parallel with Notion 2.0.18 and when I pin `notion-enhancer desktop` to the taskbar and when I try to launch it, it just opens Notion. But it opens the enhanced version by clicking the `.exe` file from the portable directly. But it is the same `.exe` file I pinned to the taskbar. The enhanced version of course opens the Notion desktop (original) but with a plugin of Notion enhancer visible in the sidebar. But pinning doesn't work.

# What should be happening?
The pinned item must open Enhanced Notion

# Specifications
```
OS: Windows 11 (21H2, Build: 22000.434, Stable)
Notion: 2.0.18
Notion enhancer desktop: 0.11.0 (portable)
```

**Comment by dragonwocky** [comment]
Using the vanilla & enhanced versions in parallel is not recommended and is expected to cause problems. Please uninstall vanilla Notion and follow the instructions here to cleanup the app shortcuts/taskbar icon: https://github.com/notion-enhancer/notion-repackaged/issues/13#issuecomment-965690286
