### ISSUE TITLE
Enhancer Menu not appearing - Screenshots

### ISSUE THREAD

**Issue by JWhiteUX** [notion-enhancer/desktop#720]
Sorry, too much info was needed, here's a simplified bug report. 

**Steps Taken**
1. From the previous version, observed new version availability  
2. Running npm command did not work (unrelated)
3. From [related page](https://notion-enhancer.github.io/), downloaded Mac compatible installer
4. Mounted, drag-drop-applications
5. Rightclick > Open > "yeah, run it…for fsake"
6. Notion Enhanced now Running
7. Opt+E not working, check the documentation
8. "A new sidebar option will appear"
-- Break: Unable to proceed --

**Expected
** After reading there would be a new row in sidebar to open Enhancer, expected it there to be an option to open enhancer

**Actual**
Nothing appears, _see figures_
<img width="236" alt="Screen Shot 2022-01-23 at 6 33 22 PM" src="https://user-images.githubusercontent.com/12961108/150713255-ec9755ef-111d-4a77-9f5f-68496beb93ea.png">
<img width="274" alt="Screen Shot 2022-01-23 at 6 33 15 PM" src="https://user-images.githubusercontent.com/12961108/150713258-47e1fd84-fe56-4f6f-b5d0-921d4e33ddaa.png">

**Summary**
Updated using installer, checked docs because quick command and previous icon missing, and unable to open enhancer. Docs suggest a new icon would appear, however this is not the case. No icon/row is visible and Enhancer is unresponsive to quickcommand input. Unable to engage enhancer. Filed bug report (hi… 👍 )

**Comment by dragonwocky** [comment]
please read the warning at the very top of the installation instructions. this is expected if you have not followed the instructions fully.
![image](https://user-images.githubusercontent.com/16874139/150713561-b8f87e7a-e6d9-40f0-a021-94c77568a7ce.png)
