### ISSUE TITLE
Enhancements menu disappeared in MacOS?

### ISSUE THREAD

**Issue by Ngort** [notion-enhancer/desktop#721]
**What is happening?**
Notion Repackaged: No way to access Enhancements Menu and apply mods / enhancements after updating to 2.0.18-1 by replacing folder in Applications.

**What should be happening?**
I should be able to access such menu with Cmd+E or Option+E or some similar hotkey, and there should be a Notion icon on my taskbar.

**Screenshots (if applicable):**
N/A

**Operating system/browser name & version:**
MacOS Monterrey 12.0.1, M1Max Macbook Pro

**notion-enhancer and/or notion-repackaged version:**

2.0.18-1

**notion-enhancer configuration (enabled/disabled mods and their settings):**
N/A? Can't see.

**Comment by dragonwocky** [comment]
please read the warning at the very top of the installation instructions. this is expected if you have not followed the instructions fully.
![image](https://user-images.githubusercontent.com/16874139/150713561-b8f87e7a-e6d9-40f0-a021-94c77568a7ce.png)

also, the default hotkey has changed to `alt+ctrl+e` (even if you're on mac). you can change it in the notion-enhancer settings (`core` -> `menu` -> `hotkey`) after you perform the above fix.
