### ISSUE TITLE
Mac OS - Tabs UI

### ISSUE THREAD

**Issue by fralps** [notion-enhancer/desktop#722]
When I check the tabs option, it works perfectly fine but there is a style issue (cf screenshot)

<img width="480" alt="Capture d’écran 2022-01-26 à 16 43 12" src="https://user-images.githubusercontent.com/48285890/151198869-78843809-6b24-4987-a54b-9db65a357f08.png">

**Operating system/browser name & version:**
I'm on Mac OS Monterey 12.1 on a MacBook Pro Intel

**notion-enhancer and/or notion-repackaged version:**
Notion repackaged

**notion-enhancer configuration (enabled/disabled mods and their settings):**
Tabs mod checked

Thanks 🙏

**Comment by dragonwocky** [comment]
dup of https://github.com/notion-enhancer/repo/issues/28

**Comment by fralps** [comment]
Oups yeah you're right sorry for that 😉
