### ISSUE TITLE
Themes do not load in Notion-Enhancer

### ISSUE THREAD

**Issue by alimosallaei19** [notion-enhancer/desktop#723]
**What is happening?** I have installed Notion Enhancer on my Windows 10 PC, and when I enable a theme in the settings menu and reload the app, the default white theme of Notion is stuck. Additionally, there is no longer an option to even just enable the Notion default dark mode. 

**What should be happening?** When I enable a theme and reload the app, the theme should be present.

**Screenshots (if applicable):**
![image](https://user-images.githubusercontent.com/63680409/151889313-3b7d44d6-2f6e-4594-9d64-d7a1e5eb495d.png)

**Operating system/browser name & version:** Windows 10 Pro, Version 21H2 -> OS Build 19044.1288, x64

**notion-enhancer and/or notion-repackaged version:** Notion-Enhancer v0.11.0-dev, latest install

**notion-enhancer configuration (enabled/disabled mods and their settings):**
> Tweaks Enabled
> Integrated Titlebar enabled
> Indentation Lines enabled
> Code line numbers enabled
> Calendar Scroll enabled
> Gruvbox theme enabled

All have the default settings.

**Comment by dragonwocky** [comment]
Try setting Notion's to dark mode in settings & members -> my notifications & settings -> my settings -> appearance.
