### ISSUE TITLE
Feature Request: Locate current page in project/page browser

### ISSUE THREAD

**Issue by machinekoder** [notion-enhancer/desktop#724]
_**What makes the feature necessary?**_
Notion per default has no way to locate the open page in the project/page browser. However, it's very useful to navigate to the page hierarchy quickly.

_**How would the feature work?**_
The navigation bar should have a button which allows selecting the currently open notion page in the project/page browser on the left. This feature is very common in IDEs, see for example https://stackoverflow.com/a/25114695/5768039

**Comment by dragonwocky** [comment]
This has been requested before, I considered it, but:
- Finding the page in the sidebar for normal pages, though possible, would require API access and come with performance issues, as there's no simple way to match a sidebar entry to the open page.
- Pages are often placed within databases, and can't be located in the sidebar.

Note that the browser on the left should not be compared to a file tree in an IDE. Notion functions at a considerably abstracted level compared to a real filesystem.
