### ISSUE TITLE
Sidebar option is not available, even though ".notion-enhancer" was deleted prior to installation 

### ISSUE THREAD

**Issue by leetwito** [notion-enhancer/desktop#726]
**What is happening?**
The sidebar option is not available.
I have removed completely notion & notion-enhancer older versions, including the ".notion-enhancer" folder in C:/Users/MYUSER

**Operating system/browser name & version:**
Windows 10

**notion-enhancer and/or notion-repackaged version:**
notion-enhancer 0.11.0

**Comment by dragonwocky** [comment]
Please provide more information (e.g. screenshots of the console, steps taken during installation process).
