### ISSUE TITLE
Broken table style

### ISSUE THREAD

**Issue by leetwito** [notion-enhancer/desktop#727]
**What is happening?**
Table style is broken 

**Screenshots (if applicable):**
![enhancer_bug](https://user-images.githubusercontent.com/29614540/152117138-79c6c01f-59e2-4143-8d12-d7b697f64b27.png)

**Operating system/browser name & version:**
windows 10 
**notion-enhancer and/or notion-repackaged version:**
enhancer V 0.11.0 

**notion-enhancer configuration (enabled/disabled mods and their settings):**
{
  "_mods": {
    "b28ee2b9-4d34-4e36-be8a-ab5be3d79f51": true,
    "5174a483-c88d-4bf8-a95f-35cd330b76e2": true,
    "a5658d03-21c6-4088-bade-fa4780459133": true,
    "e1692c29-475e-437b-b7ff-3eee872e1a42": true,
    "752933b5-1258-44e3-b49a-61b4885f8bda": true,
    "cb6fd684-f113-4a7a-9423-8f0f0cff069f": true,
    "a2401ee1-93ba-4b8c-9781-7f570bf5d71e": true,
    "548fe2d7-174a-44dd-88d8-35c7f9a093a7": true,
    "1794c0bd-7b96-46ad-aa0b-fc4bd76fc7fb": true
  }
}

**Comment by dragonwocky** [comment]
known bug, disable the "wrap tables to page width" option under the tweaks extension.
