### ISSUE TITLE
Broken simpler databases menu

### ISSUE THREAD

**Issue by KristalMDow** [notion-enhancer/desktop#728]
**What is happening?**
Clicking the cog icon on inline databases does bring up the toggle menu, but toggling has no effect. Cannot escape the menu without opening a new window in Notion using Ctrl+Shift+N shortcut. None of the usual features such as hiding parts of the databases are working.

**What should be happening?**
Clicking the cog icon on inline databases should bring up a toggle menu that is effective and goes away after clicking or hovering away.

**Screenshots (if applicable):**
![image](https://user-images.githubusercontent.com/30303538/152697395-eeaaf4b2-ab37-43e7-808d-02ad684102b5.png)
All things are toggled off, but are still visible. Cannot navigate away from this menu,

**Operating system/browser name & version:**
Windows 10, up to date 2/6/22

**notion-enhancer and/or notion-repackaged version:** 1.11

**notion-enhancer configuration (enabled/disabled mods and their settings):** Only Simpler Databases, no settings to modify

**Comment by dragonwocky** [comment]
dup of https://github.com/notion-enhancer/repo/issues/64

**Comment by mich-dooley** [comment]
Also having this issue on MacOS 12.2.1
