### ISSUE TITLE
Grey line in page title

### ISSUE THREAD

**Issue by imsumoregn** [notion-enhancer/desktop#730]
**What is happening?**
The page title's background is gray ( notion's default dark theme) on every theme.
**What should be happening?**
The theme should have worked properly
**Screenshots (if applicable):**
![image](https://user-images.githubusercontent.com/87747324/153770071-bab2009f-5fa2-46d5-865c-1683fc11d548.png)
**Operating system/browser name & version:**
Win10/Chrome98
**notion-enhancer and/or notion-repackaged version:**
2.0.18.0
**notion-enhancer configuration (enabled/disabled mods and their settings):**
All default exept theme. All theme is bugged.

**Comment by dragonwocky** [comment]
dup of https://github.com/notion-enhancer/repo/issues/37
