### ISSUE TITLE
Add options to customize/close the reading/speaking time in word counter.

### ISSUE THREAD

**Issue by Travelerrrrr** [notion-enhancer/desktop#732]
**What makes the feature necessary?**
I apprieciate the word counter feature so much, but the reading/speaking time is only suitable for English words. As for other  language, like Chinese for example, it would be better to allow the users to customize the reading/speaking speed or just close this feature.

**How would the feature work?**
Probably I think you can add options for users to customize the reading/speaking speed, like 'characters per minute', or an option to close it (because it is just confusing for other language). 

Thanks a lot! Really appriciate your brilliant work!

**Comment by dragonwocky** [comment]
The notion-enhancer currently only supports English and the display of right-to-left text with the right-to-left extension. Multi-language support/customisation is not available, though it's something I want to get to at some point in the future (https://github.com/notion-enhancer/repo/issues/76). Until then, features like this are out of scope.

P.S. Please read the [contributing guide](https://notion-enhancer.github.io/about/contributing/) before opening issues in future - i.e. this issue should have been made [here](https://github.com/notion-enhancer/repo/issues) instead.

**Comment by Travelerrrrr** [comment]
Thanks a lot for your work!!!
Looking forward to new updates and improvements. :)
