### ISSUE TITLE
Does not function on Mac

### ISSUE THREAD

**Issue by disabledandfab** [notion-enhancer/desktop#736]
The program should be allowing me to use it, essentially. It opens, and I may be able to click something, before it freezes. I can't move my cursor, type, scroll, etc. I seem to be having the same issue with the Chrome Extension. 
Info
Mac OS Monterey
Notion Enhanced Version 2.0.18-1
Configurations: Tweaks, font chooser (rainyhearts and Indie Flower), tray, always on top, view scale, outliner, scroll to top, indentation lines, bypass preview, top bar icons, word counter, code line numbers, calendar scroll, collapsible headers, collapsible properties, weekly view, truncated titles, focus mode, and global block link.
I’m using the themes”pinky boom” and “playful purple”

**Comment by dragonwocky** [comment]
The notion-enhancer does not handle large pages very well- I recommend either a) disabling some of the more intensive mods like word counter, collapsible headers, outliner, and the themes or b) breaking up your notes into smaller pages. The individual performance issues of each of these mods are known bugs (some that can be fixed, some that can't).
