### ISSUE TITLE
Add option to start NE minimized to tray

### ISSUE THREAD

**Issue by enoversum** [notion-enhancer/desktop#737]
**What makes the feature necessary?**
Having Notion Enhancer starting with Windows is already very convenient, and being able to minimize it to the tray. It would be even more comfortable if it could start minimized to the tray, so I don't have to click it away when my computer boots up.

**How would the feature work?**
Give an option in the settings, NE would start, but not show unless I click on the tray icon 😄 .

**Comment by dragonwocky** [comment]
This is built into the notion-enhancer already! If you have both the `open notion on startup` and `run notion in the background` options under the tray extension enabled, Notion should start minimised to the tray when your computer boots up.

This used to be something that was explicitly enabled, however, the option was removed to allow for more natural window behaviours:
- On startup, the app should start minimised.
- When clicking the icon in your taskbar, the app should open directly.

**Comment by enoversum** [comment]
@dragonwocky Ah, Tom, I am so sorry. You know why I didn't see this? Because out of a habit, I had put a shortcut to Notion Enhanced to the Autostart folder in my start menu, as the normal Notion doesn't support auto-starting on its own. This circumvented your functionality. Of course it works as you describe—thanks for taking your time to still comment this 'issue' 🙂.
