### ISSUE TITLE
Custom emoji set, same as Custom icon set

### ISSUE THREAD

**Issue by mpbotti** [notion-enhancer/desktop#741]
Hi, could you make an integration for custom emojis? Same as icon set, but for emojis.
Regards, M.

**Comment by dragonwocky** [comment]
have you tried the emoji sets extension? it lets you pick from a selection of emoji sets
fully custom emojis are out of scope at the moment

**Comment by mpbotti** [comment]
Yes I did! and it works fine... but, only works over the Page - Add icon feature
![image](https://user-images.githubusercontent.com/29799871/155849750-6649e374-6e71-459e-9cd8-d5547099155c.png)
I would love to also use it at /emoji feature:
![image](https://user-images.githubusercontent.com/29799871/155849804-4f77675c-ae0d-4f39-bc19-e812a9df37fc.png)
See, no Emoji Icons option on this screen... 
Never mind, I think I can live without it,
Regards, M.
