### ISSUE TITLE
simpler databases frozen and not working 

### ISSUE THREAD

**Issue by lozbi** [notion-enhancer/desktop#742]
BEFORE MAKING A BUG REPORT, PLEASE READ THE
[CONTRIBUTING](https://notion-enhancer.github.io/about/contributing) GUIDE.

BUG REPORTS ARE NOT FOR SUPPORT REQUESTS. IF YOU JUST NEED HELP,
ASK IN THE [DISCORD](https://discord.gg/sFWPXtA) SERVER.

BUG REPORTS THAT DO NOT PROPERLY FILL
IN THE TEMPLATE MAY BE IGNORED OR REJECTED.
YOU MUST DELETE ALL TEXT ON OR ABOVE THIS LINE BEFORE SUBMITTING.

**What is happening?**
even after reloading toggles within the simpler databases function do not work, once a setting is toggled on the feature freezes my notion page.
**What should be happening?**
the toggles should trigger changes in the database and not freeze the application.
**Screenshots (if applicable):**
![image](https://user-images.githubusercontent.com/100817585/156485555-b7429e64-9160-4c22-98ef-5eefe60f49a7.png)
![image](https://user-images.githubusercontent.com/100817585/156485617-8f8dd7ba-04ae-45b3-8942-83eab9184f71.png)

**Comment by dragonwocky** [comment]
dup of https://github.com/notion-enhancer/repo/issues/64
