### ISSUE TITLE
Unable to open as a page element inside a database

### ISSUE THREAD

**Issue by carlosmn25** [notion-enhancer/desktop#748]
**What is happening?**

I have this database with a list view to store my travel plans, and the elements inside are pages themselves so that I can write down all the information about the trip. When I hover over the list element, the "Open as a page" button doesn't appear, so I can't access the content of the page in any way.

**What should be happening?**
When I open this database in Notion (Windows 10 or web browser), I can see the "Open as a page" button to edit or view the content if I hover over the element.

**Screenshots (if applicable):**

Notion enhancer:
![imagen](https://user-images.githubusercontent.com/32327878/161520539-9bab1cd1-a06f-4b43-a147-5abb99f3ceb5.png)

Notion (web browser):
![imagen](https://user-images.githubusercontent.com/32327878/161520826-9e94f400-43fd-4d58-9e68-ee1fa6c65820.png)

**Operating system/browser name & version**:
Ubuntu 20.04.1 LTS

**notion-enhancer and/or notion-repackaged version:**
notion-enhancer v0.11.0-dev

**notion-enhancer configuration (enabled/disabled mods and their settings):**
Tabs
Emoji sets
Word counter
Code line numbers
Calendar scroll
Light+ theme

**Comment by carlosmn25** [comment]
I'm not sure, but I think I'm not allowed to add tags to the issue in this repo (I'm quite new to GitHub and this is the first report that I've ever created on an open source project). It would be nice if someone added the "bug" tag to it.

**Comment by dragonwocky** [comment]
does this only occur in the notion-enhancer app, or when using it as a browser extension too?

**Comment by dragonwocky** [comment]
Try clearing the app's cache: open devtools (`ctrl+shift+i`), go to the **Application** tab -> **Clear storage** -> click **Clear site data**

**Comment by carlosmn25** [comment]
I was going to try this, but I've started the app and the problem isn't there now. I have restarted it several times to check and it doesn't happen now. I will close this issue.
