### ISSUE TITLE
permanent borders around pages

### ISSUE THREAD

**Issue by itsavonell** [notion-enhancer/desktop#756]
i have this permanent border around this page and it won't go away. 

![image_2022-05-22_204417393](https://user-images.githubusercontent.com/23192892/169723908-0f024f56-9ab6-407f-af3a-63baf4944778.png)

**Comment by dragonwocky** [comment]
if you open the page in a non-enhanced version of notion (e.g. a private browser tab) are those borders there? could you share a link to a page where i can reproduce that?

**Comment by itsavonell** [comment]
the issue is gone with the update! i don't know what happened but i enabled the extensions one by one and the problem didn't come back.
