### ISSUE TITLE
Extensions-tab overlap with MacOS close button

### ISSUE THREAD

**Issue by Miriam-Eason** [notion-enhancer/desktop#758]
Background：
MacOS12 + apple silicon M1pro
Intel installer

Issus:
When I use the tab extension in MacOS, the left tab overlapped with the MacOS's three buttons like that:
<img width="668" alt="image" src="https://user-images.githubusercontent.com/77019865/170210669-f02226cd-a88e-40a9-9c37-d6da3ccf921a.png">

**Comment by scotch115** [comment]
Duplicate of this [issue](https://github.com/notion-enhancer/repo/issues/28)
