### ISSUE TITLE
Cannot change window size

### ISSUE THREAD

**Issue by ypa957** [notion-enhancer/desktop#759]
Unmaximize in the integrated titlebar does not work, so the window size cannot be changed. When the tiling window manager mode is not enabled

**Comment by dragonwocky** [comment]
I can't replicate this, please provide screenshots.

**Comment by ypa957** [comment]
The notion interface can only be full screen and cannot be reduced

**Comment by dragonwocky** [comment]
![image](https://user-images.githubusercontent.com/16874139/170811032-7acb427e-888b-4838-a04c-101b644eb89d.png)

Closing this as invalid. Please provide screenshots and steps to reproduce or this will be ignored.
