### ISSUE TITLE
Notion Enhancing Menu Disappeard

### ISSUE THREAD

**Issue by Fr0styyyy** [notion-enhancer/desktop#762]
Hallo 
I have been using the software for about a week and everything worked fine 
the first time opening the enhancement menu was there. I used the menu only once and the most of the features were enabled but the menu disappeared completely after that 1st time 
the features remained though but then when I tried to reinstall it so it appear again it never did, I tried solutions someone experienced this like me before but it did not work, from writing commands and  deleting some files 

_notion-enhancer apply -y_
_npm i -g notion-enhancer_
both said the notion enhancer is unrecognized on the laptop even though i installed notion with the option *all users* not only the current one
I tried searching for something called npm file but it doesn't exist in the user file

![Screenshot 2022-06-04 141652](https://user-images.githubusercontent.com/88462609/171998614-c392f3bc-3938-4605-acd4-884a014633e7.png)

**Comment by dragonwocky** [comment]
From the #announcements channel in Discord:
![image](https://user-images.githubusercontent.com/16874139/172000222-45829926-9946-43f3-9307-bcb539db541f.png)

**Comment by Fr0styyyy** [comment]
Thank you so much and I will consider participating to the discord channel

**Comment by amenda-zjl** [comment]
Hi there! What is the hotkey in MAC? (and no found the tray menu🥲

**Comment by dragonwocky** [comment]
@amenda-zjl the hotkey is the same on Mac as on Windows - `Ctrl+Alt+E` (the `Alt` key may be labelled `Opt`/`Option`). If that doesn't work, join the Discord and have a look at what people have been trying there.

**Comment by amenda-zjl** [comment]
@dragonwocky So what's your four-numbers label? How can I get into your channel🥺

**Comment by dragonwocky** [comment]
@amenda-zjl click the "Community" button or the red banner at the top on the notion-enhancer website: https://notion-enhancer.github.io/

**Comment by noamangg** [comment]
> From the #announcements channel in Discord: ![image](https://user-images.githubusercontent.com/16874139/172000222-45829926-9946-43f3-9307-bcb539db541f.png)

I try Ctrl+Alt+E it doesn't work

**Comment by dragonwocky** [comment]
@noamangg
![image](https://user-images.githubusercontent.com/16874139/174739817-a5a3eba5-23fb-43bc-85bd-527369e9f190.png)

**Comment by zeroknots** [comment]
@dragonwocky Im on US keyboard on M1 Mac OS 12.2.1

pressing Ctrl+Alt+E doesnt do anything

**Comment by ICyChain1211** [comment]
great！i works! Thanks

**Comment by Jollur** [comment]
thankssssssss!!

**Comment by sshallow** [comment]
![image](https://user-images.githubusercontent.com/21257340/182988275-e6eab9db-8958-492d-9a6a-e399c91efde4.png)
![image](https://user-images.githubusercontent.com/21257340/182988358-b0f3bf5c-cace-4fdb-9345-f3ca4da48215.png)
`Ctrl+opt+e` does not work

**Comment by dragonwocky** [comment]
@sshallow 
<img width="846" alt="image" src="https://user-images.githubusercontent.com/16874139/182991074-3945ee07-6431-40c4-86e3-084162af010e.png">

**Comment by sshallow** [comment]
tks, but` ctrl+shift+i ` does not work

**Comment by dragonwocky** [comment]
@sshallow sorry, that's the windows hotkey, try `Command + Option + I` for mac

**Comment by sshallow** [comment]
> @sshallow sorry, that's the windows hotkey, try `Command + Option + I` for mac

it's work!  tks

**Comment by btech16** [comment]
> > From the #announcements channel in Discord: ![image](https://user-images.githubusercontent.com/16874139/172000222-45829926-9946-43f3-9307-bcb539db541f.png)
> 
> I try Ctrl+Alt+E it doesn't work

Ctrl + Alt + E ->(hold Ctrl+Alt) and click "E" more than once

**Comment by davidsmorais** [comment]
Tried the steps mentioned here:
- Ctrl+Alt+E does nothing.
- Using the console to focus on the menu also doesn't find the element.
![image](https://user-images.githubusercontent.com/22729436/193452222-ae5c5e10-25af-4e99-bc86-969a693ccf28.png)

**Comment by dragonwocky** [comment]
@davidsmorais are there any other errors in the console above?

**Comment by davidsmorais** [comment]
@dragonwocky , sorry for the late reply.

Yes, I had an error along the lines of 'Unable to rmdir C:/Users/.../.notion-enhancer > directory was not empty' after deleting this directory I managed to run the console comand to pop up the menu.
I guess this was from an early version of notion-enhancer I installed in the past.

**Comment by dragonwocky** [comment]
@davidsmorais yes, the installation instructions do tell you to delete that:
![image](https://user-images.githubusercontent.com/16874139/202933923-b077a67a-8ec2-4f48-adbd-ed47baec2d95.png)

**Comment by SuCicada** [comment]
type 
`__enhancerElectronApi.focusMenu()` 
in console of dev tools

**Comment by elhakeem** [comment]
Notion and Notion Enhancer are electron apps.
You can open the dev tools of any electron app using `ctrl + shift + I` or using this app [debugtron](https://github.com/pd4d10/debugtron).
The next step is to open the console and write `__enhancerElectronApi.focusMenu()`

**Comment by Denji-kun** [comment]
> @noamangg
> ![image](https://user-images.githubusercontent.com/16874139/174739817-a5a3eba5-23fb-43bc-85bd-527369e9f190.png)
> 

how do i do that in Android

**Comment by dragonwocky** [comment]
@Denji-kun the notion-enhancer does not support Android. Also, don't ping closed issues: refer to https://github.com/notion-enhancer/notion-enhancer/issues/770.

**Comment by thewaliii** [comment]
Why enhancer was abandoned? No updates for ages!

**Comment by jliving207** [comment]
The trick that worked for me was to Press CTRL + ALT + E as soon as you open Notion Enhancer the app on windows, while it's still loading. Worked like a charm, thanks to the developer guy is a god send.

**Comment by SEYED1424** [comment]
> Tried the steps mentioned here:
> 
> * Ctrl+Alt+E does nothing.
> * Using the console to focus on the menu also doesn't find the element.
>   ![image](https://user-images.githubusercontent.com/22729436/193452222-ae5c5e10-25af-4e99-bc86-969a693ccf28.png)

How you solved that?
I have this error and I don't know how can I solve that. (I deleted .notion-enhancer before fresh installation)

**Comment by jliving207** [comment]
Press CTRL + ALT + E as soon as you open the application and it hasn't even loaded menu will pop up
