### ISSUE TITLE
Notion Enhancer sidebar option not visible on Mac m1

### ISSUE THREAD

**Issue by ashwinkumar6** [notion-enhancer/desktop#765]
**Device info:**
MacBook Air (M1, 2020) 
Version: Monterey 12.4
Notion Enhancer Version:  2.0.18-1

I was using vanilla notion before. I uninstalled it, deleted the .notion-enhancer file and folder from `/home/<name>/.notion-enhancer`

Installed notion dmg package from [docs](https://notion-enhancer.github.io/getting-started/installation/)

Had to run `xattr -cr /Applications/Notion\ Enhanced.app` because of an existing bug

Opened Notion Enhancer but the `Notion Enhancer` option is not displayed

**Comment by dragonwocky** [comment]
see https://github.com/notion-enhancer/desktop/issues/765

**Comment by safwaan-menk** [comment]
Having the same issue - notion-enhancer not in the sidebar
