### ISSUE TITLE
Outliner not working with tabs

### ISSUE THREAD

**Issue by ReaLadge** [notion-enhancer/desktop#769]
**What is happening?**
The extension "Outliner" is only showing when the first tab of notion enhanced is launched. Wont show up on other tabs. Most times it doesn't show up at all even after relaunched. Pretty sure this is semi recent issue. Don't remember it doing this a few months ago.

**What should be happening?**
![image](https://user-images.githubusercontent.com/70264500/182076930-cf5efc90-ab12-4d7a-a81c-74f6f9d2a871.png)

**Screenshots (if applicable):**
![image](https://user-images.githubusercontent.com/70264500/182076228-e895cec2-146f-467b-b83f-52ca8c5b55f9.png)

**Operating system/browser name & version:**
![image](https://user-images.githubusercontent.com/70264500/182076400-18e2cc2f-63b1-4ec5-9136-e651dda75b1a.png)

**notion-enhancer and/or notion-repackaged version:**
![image](https://user-images.githubusercontent.com/70264500/182077347-c808966d-0f5c-451a-816f-548eea822eeb.png)

**notion-enhancer configuration (enabled/disabled mods and their settings):**

Extensions:
- Tabs
- Outliner
- Indentation lines
- Emoji sets

Nothing else

**Comment by Ivansnote** [comment]
I got some problem,but more outright,witch is completely empty in any pages.I reinstalled several times and got no help.

**Comment by dragonwocky** [comment]
see my comment at the bottom of https://github.com/notion-enhancer/repo/issues/123
