### ISSUE TITLE
Can't find the Notion Enhancer button on the sidebar anymore?

### ISSUE THREAD

**Issue by jontstaz** [notion-enhancer/desktop#770]
**What is happening?**
No notion-enhancer hyperlink on the sidebar

**What should be happening?**
There should be a notion enhancer button on the sidebar

**Screenshots (if applicable):**
https://i.imgur.com/S15r3qu.png

**Operating system/browser name & version:**
Windows 11

**notion-enhancer and/or notion-repackaged version:**
notion-enhancer

**notion-enhancer configuration (enabled/disabled mods and their settings):**
can't remember

**Comment by dragonwocky** [comment]
dup of https://github.com/notion-enhancer/desktop/issues/770

**Comment by sophon48** [comment]
> dup of #770

This _is_ issue 770. Please can you point me towards the correct thread for this issue?

**Comment by ycycse** [comment]
I got the same question on win11. Could I ask where I can find the fixed release?

**Comment by dragonwocky** [comment]
@ycycse the fix hasn’t been released yet. This issue will be closed when the fix is released.

**Comment by ycycse** [comment]
> @ycycse the fix hasn’t been released yet. This issue will be closed when the fix is released.

I get it. Thank you.

**Comment by ZekXtreme** [comment]
Same Issue with me on Arch Linux. Hope This gets fixed soon

**Comment by DreamFields** [comment]
Please refer to this link:
https://discord.com/channels/748161877045149706/748162220424167534/982412979498786886

**Comment by insignificance** [comment]
same here . macOS 13.1 、Notion enchanted 2.0.18、 Notion 2.1.11

**Comment by HassanKhalil137** [comment]
Hi all, Any updates on this issue "No notion-enhancer on the sidebar", please?
