### ISSUE TITLE
Nothing Changed after I installed notion enhancer (windows 10)

### ISSUE THREAD

**Issue by 3phi5** [notion-enhancer/desktop#772]
"changed 24 packages, and audited 25 packages in 5s  
3 packages are looking for funding   
run `npm fund` for details  
found 0 vulnerabilities"
That what appeared to me when I entered this code (npm i -g notion-enhancer)
And nothing changed in notion after this 
please help me 
![image](https://user-images.githubusercontent.com/112293652/187054412-d74187da-3441-4673-86ac-b2620f564d70.png)

**Comment by dragonwocky** [comment]
see https://github.com/notion-enhancer/desktop/issues/762
