### ISSUE TITLE
Notion Enhance Desktop not working on Mac

### ISSUE THREAD

**Issue by sukheja-varun** [notion-enhancer/desktop#774]
**What is happening?**
Not able to see Notion Enhancer option on Notion App after following all the steps:

**What should be happening?**
Notion Enhance option in the left menu should be visible.

**Screenshots (if applicable):**
![image](https://user-images.githubusercontent.com/21065146/187557666-a14ada1e-8e64-4965-a64b-587fb393bb49.png)

![image](https://user-images.githubusercontent.com/21065146/187557448-7c783c9a-784d-4f21-a7f0-fc518c7a61e0.png)

**Operating system/browser name & version:**
OS: macOS Monterey 12.5 
Notion Desktop: Version 2.0.24 (2.0.24)

**notion-enhancer and/or notion-repackaged version:**
notion-enhancer dmg

**notion-enhancer configuration (enabled/disabled mods and their settings):**
NA

**Comment by dragonwocky** [comment]
the notion-enhancer does not current support notion desktop v2.0.24, you must use notion-repackaged or the browser extension

as for the disappearing menu, see https://github.com/notion-enhancer/desktop/issues/762

**Comment by sukheja-varun** [comment]
@dragonwocky but the official docs https://notion-enhancer.github.io/getting-started/installation says,
The notion-enhancer works on MacOS, Linux and Windows. It can be used within the desktop app or the web client as a browser extension.

and it even has the steps mentioned as:
MacOS
> Warning: as this is a modified version of the Notion app, it is unsigned. It may be detected as malware or be unable to be opened. If this occurs, it can be fixed by following [Apple's official instructions](https://support.apple.com/en-us/HT202491).

 Apple Silicon (M1) Macs →
- arm64 installer: [.dmg](https://github.com/notion-enhancer/notion-repackaged/releases/download/v2.0.18-1/Notion-Enhanced-2.0.18-1-arm64.dmg)
- Portable arm64 build: [.zip](https://github.com/notion-enhancer/notion-repackaged/releases/download/v2.0.18-1/Notion-Enhanced-2.0.18-1-arm64-mac.zip)

An extra step is required to run the M1 (arm64) build of the app due to a bug in the packager we depend on (see [electron-userland/electron-builder#5850](https://github.com/electron-userland/electron-builder/issues/5850)).

Open the terminal, type the following command, and then press the return key:

```
xattr -cr "<installation location>.app"
```

> The <installation location> should be replaced with the file path to where the app has been installed, e.g. /Applications/Notion Enhanced.

> If this is too complicated, it is recommended to use the notion-enhancer in the browser or run the Intel build of notion-repackaged through Rosetta instead.


Also at the end of the same page it is mentioned as:
 Enhancement →
If the npx package runner is available, the notion-enhancer can be inserted into Notion with a single command.

```
npx notion-enhancer apply
```

**Comment by sukheja-varun** [comment]
@dragonwocky also the usage page https://notion-enhancer.github.io/getting-started/basic-usage/ says:
The only noticeable difference should be an extra option in the Notion sidebar labelled  notion-enhancer. 
![image](https://notion-enhancer.github.io/assets/screenshots/first-open.png)

**Comment by dragonwocky** [comment]
@sukheja-varun the banner at the top also says that things are not working as they should be and the discord is the correct place to find the updated information on the current workarounds.

The documentation describes how it "should" work, which unfortunately does not currently match how it does work for a variety of reasons - this is a temporary situation until I am able to release an update.

<img width="983" alt="image" src="https://user-images.githubusercontent.com/16874139/187560678-74a52d2d-8730-4965-835a-b4dbf886b567.png">
