### ISSUE TITLE
No way to access notion-enhancer options on Mac

### ISSUE THREAD

**Issue by rosenpin** [notion-enhancer/desktop#775]
**What is happening?**
The notion enhancer button isn't showing up. In the Discord announcment regarding this issue it says:
> You can still alternatively open the menu to attempt to enable the notion-enhancer's features one of two ways:
> - by pressing the hotkey (Ctrl+Alt+E by default).
This isn't the case on Mac though, this shortcut doesn't work. I tried multiple other combinations like Cmd+Alt+E/Cmd+Shift+E nothing works

**What should be happening?**
There should be some possible way to open the notion enhancer on Mac

**Screenshots (if applicable):**
<img width="209" alt="image" src="https://user-images.githubusercontent.com/5289630/188102283-0b83cf66-2a98-4e99-9b4a-bec164549480.png">

**Operating system/browser name & version:**
Mac M1

**notion-enhancer and/or notion-repackaged version:**
Version 2.0.18-1 (2.0.18-1)

**Comment by dragonwocky** [comment]
There are multiple other ways listed in the Discord:
> - by navigating through the tray menu (if you have it enabled).
> - https://discord.com/channels/748161877045149706/772963605326594058/983652901719265311 or https://discord.com/channels/748161877045149706/748162434237202472/998951569586401371 (via devtools).

Closing as a dup of https://github.com/notion-enhancer/desktop/issues/762

**Comment by rosenpin** [comment]
> There are various other ways listed in the Discord:
> 
> > * by navigating through the tray menu (if you have it enabled).
> > * https://discord.com/channels/748161877045149706/772963605326594058/983652901719265311 or https://discord.com/channels/748161877045149706/748162434237202472/998951569586401371 (via devtools).
> 
> Closing as a dup of #762

Right, my bad
