### ISSUE TITLE
Apple M2, MacOS Ventura Beta 3 - Attempted to open the Apple Silicon .dmg for Notion Enhancer, system says it's damaged and should be deleted.

### ISSUE THREAD

**Issue by Unxsual** [notion-enhancer/desktop#776]

**Comment by dragonwocky** [comment]
Please read the installation instructions: https://notion-enhancer.github.io/getting-started/installation/
There are documented extra steps to run the app on Mac.
![image](https://user-images.githubusercontent.com/16874139/188250108-2990977e-8960-46a7-b18b-a946de703b61.png)
