### ISSUE TITLE
Can't see the enhancer in the menu

### ISSUE THREAD

**Issue by cgmcgm7** [notion-enhancer/desktop#777]
I downloaded Notion Enhanced v.2.0.18-1 and installed it. I open it but can't see anything new in the left menu :/ idk what am i doing wrong.
Ty!

**Comment by cleomalone** [comment]
I am also having this problem!

**Comment by dragonwocky** [comment]
see https://github.com/notion-enhancer/desktop/issues/762

**Comment by davidsmorais** [comment]
Have tried what's described in #762 and pressing ctrl+alt+E does nothing for me

**Comment by cleomalone** [comment]
Yeah, same here actually! I just went back to regular notion.
