### ISSUE TITLE
A javaScript error occured in the main process

### ISSUE THREAD

**Issue by mohdkatlesh** [notion-enhancer/desktop#778]
Hi there,

I learned about the notion-enhancer today, and after I installed the "node.js" and installed the notion-enhancer by command line the error raised in the screen 

![image](https://user-images.githubusercontent.com/43403852/192158584-e53b87f3-49f3-43f2-95dc-a4330bfa825c.png)

**Comment by dragonwocky** [comment]
manual installation currently doesn't work for 2 reasons
- see https://github.com/notion-enhancer/desktop/issues/684
- notion has updated to a newer version of electron that the enhancer hasn't caught up with yet

for the time being you will have to use notion-repackaged, which is actually just the official app with the command line script already run for you
