### ISSUE TITLE
extensions bug

### ISSUE THREAD

**Issue by 863952540** [notion-enhancer/desktop#780]
BEFORE MAKING A BUG REPORT, PLEASE READ THE
[CONTRIBUTING](https://notion-enhancer.github.io/about/contributing) GUIDE.

BUG REPORTS ARE NOT FOR SUPPORT REQUESTS. IF YOU JUST NEED HELP,
ASK IN THE [DISCORD](https://discord.gg/sFWPXtA) SERVER.

BUG REPORTS THAT DO NOT PROPERLY FILL
IN THE TEMPLATE MAY BE IGNORED OR REJECTED.
YOU MUST DELETE ALL TEXT ON OR ABOVE THIS LINE BEFORE SUBMITTING.

**What is happening?**
I'm following the every step of installment. Then I tap "ctrl+alt+e" open the menu, and tick some extentions. Then reloaded, noting has changed. 
Versions: notion-enhancer v0.11.0
Is there any method to solve this problem? Thanks for your attention!
**What should be happening?**

**Screenshots (if applicable):**

**Operating system/browser name & version:**

**notion-enhancer and/or notion-repackaged version:**

**notion-enhancer configuration (enabled/disabled mods and their settings):**

**Comment by dragonwocky** [comment]
i can't help you if just say "some extensions." every extension does a different thing and some extensions work at the moment and some don't.

have a look through the issues here to see if any match the problems you're having first: https://github.com/notion-enhancer/repo/issues

then if there are any extensions broken that haven't been reported yet, create a bug report for each of those separate extensions (with as much information as possible) in https://github.com/notion-enhancer/repo/issues
