### ISSUE TITLE
Icon doesn't show up

### ISSUE THREAD

**Issue by Noob-linux-user** [notion-enhancer/desktop#782]
**What is happening?**
The icon doesn't show in the desktop app of Linux. But they work on mobile devices and on the web
**What should be happening?**
We should see the icons
**Screenshots (if applicable):**
Below
**Operating system/browser name & version:**

linux mint 20.3 and 21
**notion-enhancer and/or notion-repackaged version:**
2.0.18-1
**notion-enhancer configuration (
![Screenshot 2022-11-16 12:34:46](https://user-images.githubusercontent.com/107858045/202109178-2e597e04-fa16-4880-a101-5c27a1f280ec.png)
enabled/disabled mods and their settings):**

**Comment by dragonwocky** [comment]
dup of https://github.com/notion-enhancer/notion-repackaged/issues/106
