### ISSUE TITLE
Unable to find terminal required for application (Solved)

### ISSUE THREAD

**Issue by nazar-kuziv** [notion-enhancer/desktop#787]
**When I try to start notion through the program icon, I get the following error and it does not start:**
![image](https://user-images.githubusercontent.com/57569453/206141022-b47f6c90-0fbe-47df-b258-b45f5c17e965.png)

**At the same time, when I run this program through the terminal, it starts, but with these errors:**
```
10:31:33.390 › Error: Error: ENOENT: no such file or directory, open '/opt/Notion Enhanced/resources/app-update.yml'
10:31:33.772 › {
  level: 'error',
  from: 'main',
  type: 'unhandledRejection',
  error: {
    name: 'TypeError',
    message: 'One-time callback was called more than once',
    stack: 'TypeError: One-time callback was called more than once\n' +
      '    at AsyncFunction.<anonymous> (/opt/Notion Enhanced/resources/app.asar/main/schemeHandler.js:185:13)'
  }
}
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
TypeError: One-time callback was called more than once
```
Tried reinstalling the program, it doesn't help. What can I do about it? I use Arch Linux + GNOME.

**I have already solved this problem, as it turned out this is a problem only on my computer, sorry to waste your time.**

**Comment by FloLangenfeld** [comment]
@llutsefer Sorry to necrobump your issue, but do you remember how you did solved that problem? I'm facing the same issue (same error message, at least).
I'm on a Pop_OS distro with GNOME.
Thanks for any help
