### ISSUE TITLE
Weekly view not working

### ISSUE THREAD

**Issue by AtrixV** [notion-enhancer/desktop#788]
Weekly view not working in Microsoft Edge
![image](https://user-images.githubusercontent.com/111180274/211167768-853da807-99cb-43b1-8b38-f44de45a1a99.png)
![image](https://user-images.githubusercontent.com/111180274/211167470-f8d0e9d3-d04f-4e1d-812b-10b0c8f2d935.png)

Weekly view not working in Windows 11 22H2
![image](https://user-images.githubusercontent.com/111180274/211167786-bd0cb97e-d48e-47c4-b51d-71fbc239ad07.png)
![image](https://user-images.githubusercontent.com/111180274/211167488-43891186-3199-4505-b009-c9eac00fb644.png)

**Comment by dragonwocky** [comment]
dup of https://github.com/notion-enhancer/notion-enhancer/issues/751
