### ISSUE TITLE
In-line table view display error

### ISSUE THREAD

**Issue by bubsie2000** [notion-enhancer/desktop#791]
**What is happening?**
When the requirement for "responsive columns breakpoint" in tweaks is met the columns in the rows of in-line tables don't match with the table header columns. **This isn't the same as the previous table view bug reported when "wrap tables to page width" is toggled on.** Simply having tweaks on causes the bug to appear.

**What should be happening?**
The columns of the in-line table rows should match up evenly with the corresponding columns in the table header.

**Screenshots (if applicable):**
<img width="592" alt="image" src="https://user-images.githubusercontent.com/94096379/217408233-14c73798-62b9-44b8-aad1-35955c2b84f6.png">
<img width="547" alt="image" src="https://user-images.githubusercontent.com/94096379/217408266-d1caca7f-cdb8-484d-b949-08133103a6ca.png">

**Operating system/browser name & version:**
MacOS Ventura 13.1 as well as Google Chrome Version 109.0.5414.119 (Official Build) (arm64).

**notion-enhancer and/or notion-repackaged version:**
Notion-enhancer and notion-repackaged v0.11.0

**notion-enhancer configuration (enabled/disabled mods and their settings):**
The only enabled mod is tweaks. The settings for the mod are:
css insert: custom css file (issue persists even without the file)
responsive columns breakpoint (px): 600px
responsive columns breakpoint (%): 50%
image alignment: center
All other setting toggles are turned off.

**Comment by dragonwocky** [comment]
dup of https://github.com/notion-enhancer/notion-enhancer/issues/883
