### ISSUE TITLE
Cant return to the other pages, when click into no access page.

### ISSUE THREAD

**Issue by bomian98** [notion-enhancer/desktop#792]
**What is happening?**

Last time, i use it and i clicked into a no access page, and then it show as follow. I can't return. I try to close and reopen notion enhancer, it still show as follow. 

So i'm stuck, and couldn't use.

**What should be happening?**

**Screenshots (if applicable):**

![image](https://user-images.githubusercontent.com/47129873/219948762-22129e99-ad13-4d3c-8db7-c13e23297859.png)

**Operating system/browser name & version:**

Windows 11

**notion-enhancer and/or notion-repackaged version:**

0.10.2

**notion-enhancer configuration (enabled/disabled mods and their settings):**

**Comment by dragonwocky** [comment]
does this help? ![](https://cdn.discordapp.com/attachments/741945726791319643/1076862263841017876/image0.jpg)

**Comment by bomian98** [comment]
I use this approach: 
remove the .notion-enhancer file and reopen software. It returns to the main page and then restore the .notion-enhancer file. 
Little complex. 
I think ur approach is better. Thx.
