### ISSUE TITLE
Icons Disappear for no reason. 

### ISSUE THREAD

**Issue by qezics** [notion-enhancer/desktop#793]
Whenever I put an Icon on a page, it disappears. This didn't happen before I installed notion enhancer. After installation, any icons that I used (and their color) would disappear if I used them. Notion released an update two days ago, and that caused the bug to go away. I changed a setting within notion enhancer, and the bug appeared once again. ( tried changing it back and nothing happened).

![Screenshot (91)](https://user-images.githubusercontent.com/128321915/226204430-afd40947-c917-449a-b1b9-77e748b45750.png)

I am using the desktop version of notion, on windows 11. 

![Screenshot (94)](https://user-images.githubusercontent.com/128321915/226204592-14daa950-1506-42c0-8925-55cc0db2bca2.png)
![Screenshot (93)](https://user-images.githubusercontent.com/128321915/226204593-da5831b7-be2e-4bfd-8e5c-7a3cfac39c3f.png)
![Screenshot (92)](https://user-images.githubusercontent.com/128321915/226204594-ff604f62-c5d7-45ee-9ab2-3f4d7bfd1718.png)

**Comment by dragonwocky** [comment]
dup of https://github.com/notion-enhancer/notion-repackaged/issues/106, there's a cache notion tries to render its icons from that doesn't exist in the current release of the notion-repackaged
