### ISSUE TITLE
No setting options appear

### ISSUE THREAD

**Issue by cocohao715** [notion-enhancer/desktop#799]
The version I am using is: Notion-Enhanced-Setup-2.0.18-1
The option notion enhanced does not appear
![QQ截图20230513104154](https://github.com/notion-enhancer/notion-enhancer/assets/32030622/6195c72c-83d3-4dd3-bbed-67999cd938d7)

**Comment by dragonwocky** [comment]
dup of https://github.com/notion-enhancer/notion-enhancer/issues/770, please check discord for a workaround as instructed to by the banner on the website
