### ISSUE TITLE
Notion fails to launch (cookies.json)

### ISSUE THREAD

**Issue by hachikoharuno** [notion-enhancer/desktop#802]
The application does not start, while the following output is in the console:

(electron) Sending uncompressed crash reports is deprecated and will be removed in a future version of Electron. Set { compress: true } to opt-in to the new behavior. Crash reports will be uploaded gzipped, which most crash reporting servers support.
02:51:21.796 › { level: 'info', from: 'AssetCache', type: 'checkingForAppUpdate' }
02:51:21.822 › Checking for update
02:51:21.859 › Error reading /home/user/.config/notion-app/cookies.json {
  constructor: 'Error',
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/home/user/.config/notion-app/cookies.json',
  stack: "Error: /home/user/.config/notion-app/cookies.json: ENOENT: no such file or directory, open '/home/user/.config/notion-app/cookies.json'\n" +
    '    at Object.openSync (fs.js:466:3)\n' +
    '    at Object.func [as openSync] (electron/js2c/asar_bundle.js:5:1812)\n' +
    '    at Object.readFileSync (fs.js:368:35)\n' +
    '    at Object.e.readFileSync (electron/js2c/asar_bundle.js:5:8592)\n' +
    '    at Object.readFileSync (/opt/Notion/resources/app.asar/node_modules/jsonfile/index.js:61:22)\n' +
    '    at JsonStore.loadSync (/opt/Notion/resources/app.asar/main/JsonStore.js:38:44)\n' +
    '    at new JsonStore (/opt/Notion/resources/app.asar/main/JsonStore.js:15:14)\n' +
    '    at Object.<anonymous> (/opt/Notion/resources/app.asar/main/schemeHandler.js:37:25)\n' +
    '    at Module._compile (internal/modules/cjs/loader.js:1152:30)\n' +
    '    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1173:10)'
}

I am using arch linux with gnome 44 on wayland.

**Comment by dragonwocky** [comment]
Can you try creating a file at `/home/user/.config/notion-app/cookies.json` with the content set to `{}`?

**Comment by hachikoharuno** [comment]
#I did as you said and now the behavior has changed. Now the following output in the console:

(electron) Sending uncompressed crash reports is deprecated and will be removed in a future version of Electron. Set { compress: true } to opt-in to the new behavior. Crash reports will be uploaded gzipped, which most crash reporting servers support.
23:13:22.548 › { level: 'info', from: 'AssetCache', type: 'checkingForAppUpdate' }
23:13:22.573 › Checking for update

(notion-app:18122): Gtk-WARNING **: 23:13:22.762: cannot open display: :0

**Comment by hachikoharuno** [comment]
For some reason, the application still started as root, that is, using the command:

sudo notion-app-enhanced --no-sandbox
