### ISSUE TITLE
Notion "/" key won't work on notion-app & notion-app-enhanced

### ISSUE THREAD

**Issue by Jervx** [notion-enhancer/desktop#803]
Notion "/" key won't work on notion-app & notion-app-enhanced on ubuntu 23.04
![image](https://github.com/notion-enhancer/notion-enhancer/assets/48374007/3156e7ad-7306-41b9-a7fd-ddff4d53e85c)

But on the Notion website it works just fine.
![image](https://github.com/notion-enhancer/notion-enhancer/assets/48374007/43082be0-b580-4635-8bc2-a40d6623478b)

System info
Ubuntu 23.04 

notion installed via apt
```
sudo apt install notion-app-enhanced
sudo apt install notion-app
```
notion-app-enhanced_2.0.18-1_amd64.deb
notion-app_2.0.18-1_amd64.deb

**Comment by Mohammed-Taher** [comment]
I have the same problem on macos ventura 13.4.1 on Mac book pro 14".

**Comment by dragonwocky** [comment]
see https://github.com/notion-enhancer/notion-repackaged/issues/112
