### ISSUE TITLE
cannot type colon ":" character

### ISSUE THREAD

**Issue by realmikkifriend** [notion-enhancer/desktop#805]
For the past few days, I can't type a ":" character into Notion. I have to type it into other windows and then copy-paste it. This does not apply to notion.so in browser, only to Notion Enhanced. Each time, the console shows the error "Uncaught TypeError: g.at is not a function".

Kubuntu Linux, running Notion Enhancer v0.11.0. I've disabled all of the plug-ins recommended by Discord according to #800.

**Comment by dragonwocky** [comment]
@realmikkicloud see https://github.com/notion-enhancer/notion-repackaged/issues/112
