### ISSUE TITLE
icons don't show up on notion (arch blendos)

### ISSUE THREAD

**Issue by sidharthpunathil** [notion-enhancer/desktop#810]
**What is happening?**
Page Icons are not loading on arch, I tried running from appimage and it loaded on the first try, and from the next try onwards they are not loading

**What should be happening?**
Icons should be loading (it works in web)

**Screenshots (if applicable):**
![image](https://github.com/notion-enhancer/notion-enhancer/assets/31244727/15d87f56-1a39-45cf-825a-acaac085b220)

**Operating system/browser name & version:**
![image](https://github.com/notion-enhancer/notion-enhancer/assets/31244727/0f29120d-eee2-40c9-99a4-20aa3408d6d8)

**notion-enhancer and/or notion-repackaged version:**
notion-app-2.0.18-1
**notion-enhancer configuration (enabled/disabled mods and their settings):**

**Comment by dragonwocky** [comment]
See https://github.com/notion-enhancer/notion-repackaged/issues/106 - There's a cache handler missing from notion-repackaged at the moment, so Notion's built in icon library doesn’t display in-app. I recommend using emojis, uploading your own images, or using the notion-enhancer as a browser extension instead (icons do render in-browser).
