### ISSUE TITLE
The extension "scroll to top" made the app collapsed

### ISSUE THREAD

**Issue by Caffeine19** [notion-enhancer/desktop#811]
BEFORE MAKING A BUG REPORT, PLEASE READ THE
[CONTRIBUTING](https://notion-enhancer.github.io/about/contributing) GUIDE.

BUG REPORTS ARE NOT FOR SUPPORT REQUESTS. IF YOU JUST NEED HELP,
ASK IN THE [DISCORD](https://discord.gg/sFWPXtA) SERVER.

BUG REPORTS THAT DO NOT PROPERLY FILL
IN THE TEMPLATE MAY BE IGNORED OR REJECTED.
YOU MUST DELETE ALL TEXT ON OR ABOVE THIS LINE BEFORE SUBMITTING.

**What is happening?**
when i turn the extension "scroll to top" on, the app collapsed
**What should be happening?**

**Screenshots (if applicable):**
![image](https://github.com/notion-enhancer/notion-enhancer/assets/108726581/fc00090f-6df3-4c65-b728-dedaa3232415)
![image](https://github.com/notion-enhancer/notion-enhancer/assets/108726581/dc887ce8-8f55-4f42-a017-7bbde60a1429)

**Operating system/browser name & version:**
on windows 11
**notion-enhancer and/or notion-repackaged version:**
notion-enhancer:2.0.18
**notion-enhancer configuration (enabled/disabled mods and their settings):**
turn "scroll to top", "integrated titlebar", "tabs", "ingredient lines" on

**Comment by dragonwocky** [comment]
dup of https://github.com/notion-enhancer/notion-enhancer/issues/800
