### ISSUE TITLE
A Side Table Feature for easy jumping

### ISSUE THREAD

**Issue by Vidhanvyrs** [notion-enhancer/desktop#817]
**What makes the feature necessary?**
So this feature will help a particular user to travel faster and to avoid that sloggy scrolling that always needed to be done in long documentation because in long documentation this thing happens let me explain you by giving an example suppose a notion documentation lets say of this type
here is the notion documentation: https://vanilla-nut-5bb.notion.site/React-My-Collective-Notes-3ac0c636fc644435beb3c6c852c741b7?pvs=4
although it is not very long but lets assume it  now if we are reading it sometimes we may require to go up or down to see about the feature that we are reading or the similar topic that we just read so what we do? we scroll up and up 
although we added the table of contents at the top of the documentation we yet need to scroll up to access the different parts of the documentation through table of contents instead we can make the table of contents to be displayed at the right side of the window 

**How would the feature work?**
So the working is simple we need to make sure that if the documentation consist of the table of contents which mostly do , Now once we get to know about that we can add a little arrow type thing to the right side of the window which on clicking we can get the whole table of contents of the page hence making it easy to access different different modules inside the documentation 
here is the proposed prototype :
![image](https://github.com/notion-enhancer/notion-enhancer/assets/94836010/293b7cdf-191e-48d4-ad20-4baf4e9126a3)

**Comment by dragonwocky** [comment]
Try the Outliner - it's exactly this. Not sure how well it's working in the current release, but it will definitely be available in the coming update.

**Comment by Vidhanvyrs** [comment]
hey @dragonwocky just used it on notion they used the prototype design this'll surely help 
So, Happy to be of any use !!
collaborated with: https://github.com/ShauryaTomer
![WhatsApp Image 2024-07-03 at 08 31 40_3ecbd25b](https://github.com/notion-enhancer/notion-enhancer/assets/94836010/b3be6b6e-6445-472a-bd50-ccd3356962c2)
