### ISSUE TITLE
Notion Enhanced Doesn't Show on The Sidebar

### ISSUE THREAD

**Issue by standard-librarian** [notion-enhancer/desktop#901]
**What is happening?**
I don't see the the notion enhanced icon on the sidebar

**Screenshots:**
![image](https://github.com/notion-enhancer/notion-enhancer/assets/68431349/46199c5e-29ce-46a5-99a9-e3a3588e122b)
<img width="242" alt="image" src="https://github.com/notion-enhancer/notion-enhancer/assets/68431349/43ccb97d-f4b6-40af-ab7f-41ffca3764f7">

**Operating system/browser name & version:**
MacOS Sonoma (14.2.1)
MacBook M1

**notion-enhancer and/or notion-repackaged version:**
Notion Enhanced 2.0.18-1

**notion-enhancer configuration (enabled/disabled mods and their settings):**
N/A

**Comment by dragonwocky** [comment]
dup of https://github.com/notion-enhancer/notion-enhancer/issues/770, see below message from the discord for alternate ways to access the menu and use the notion-enhancer

![image](https://github.com/notion-enhancer/notion-enhancer/assets/16874139/645091fb-6214-4ada-a6f9-a26125350229)
https://discord.com/channels/748161877045149706/748162220424167534/982412979498786886

**Comment by standard-librarian** [comment]
thanks!, the `Ctrl+Alt+E` doesn't work on MacOS, i opened it and hit those three keys it shows `Control+Alt+Dead` you can change it in the code to be the default for mac users
![image](https://github.com/notion-enhancer/notion-enhancer/assets/68431349/62653cc6-50bc-42ad-9d0f-1b3e1c1a3aa3)
