### ISSUE TITLE
Using Notion's selectable icons for pages doesn't work.

### ISSUE THREAD

**Issue by adriandelgg** [notion-enhancer/desktop#902]
**What is happening?**
When clicking "Change Icon" next to a page and then selecting "Icons" from the icons that Notion provides, it doesn't work. The screenshot below shows which I'm talking about:
![image](https://github.com/notion-enhancer/notion-enhancer/assets/32179921/a2ed8d12-ffa0-48ad-95e9-b85c1d237d82)

**What should be happening?**
It should allow you to select an icon, and then display it. It lets you select one, but it won't display it. Icons that are emojis will work, but not the built-in Notion icons.

**Screenshots (if applicable):**
![image](https://github.com/notion-enhancer/notion-enhancer/assets/32179921/d9846dcd-e49f-40ca-a28c-453d86b28993)

**Operating system/browser name & version:**
OS: Linux on Debian 12 Bookworm
Using `notion-app-enhanced`.

**notion-enhancer and/or notion-repackaged version:**
Version: `notion-app-enhanced` v23.13.0.109 (according to `notion-app-enhanced --version`).

**notion-enhancer configuration (enabled/disabled mods and their settings):**
tweaks, font chooser, integrated titlebar, topbar icons, dracula theme

**Comment by dragonwocky** [comment]
Yep, this is a known bug specifically with the repackaged version of the app - https://github.com/notion-enhancer/notion-repackaged/issues/106.

**Comment by iliymans** [comment]
same problem with windows 10
![image](https://github.com/user-attachments/assets/022da031-441a-43a2-bac7-e26bc5b7555b)
