### ISSUE TITLE
Spell correction Not working, taking multiple clicks of various keys (right click, left click, enter, double clicks and so on)

### ISSUE THREAD

**Issue by KmiloRe** [notion-enhancer/desktop#904]
# The issue -> It can take between 1 and 6 clicks for a misspelling to be corrected properly on titles and regular text
(it is a known issue on reddit -> https://www.reddit.com/r/Notion/comments/x1merh/right_click_to_spell_check_not_working/)

# What should be happening -> When the spell correction sugestion is clicked, the correction should replace the misspelled word, without any aditional clicks

**Video of issue happening ()** -> https://drive.google.com/file/d/1-EtzWDwTqp_aGsMluwkn5CRV9sWioaNe/view?usp=sharing

**Platform:** Windows 11, desktop Notion app

**My plan ->Education plus plan**

**No notion mods enabled**

**Note:** I have Spell check on for both english and spanish.

**Comment by dragonwocky** [comment]
This appears to an issue with vanilla Notion, not with the notion-enhancer? (The attached video is of the latest vanilla Notion desktop app, which the notion-enhancer does not yet publicly support.)

To clarify, the notion-enhancer is a 3rd-party extension to the app (not affiliated with Notion). If you have an issue using the notion-enhancer, this is the right place to report it, but if you have an issue using Notion itself, please contact Notion's own support team.
