### ISSUE TITLE
Auto-Update to latest GitHub release

### ISSUE THREAD

**Issue by Mikestriken** [notion-enhancer/desktop#916]
**What makes the feature necessary?**
Users will be able to learn there is a new update faster.
Updates can be released more rapidly without annoying users that constantly need to manually update.

**How would the feature work?**
1. User starts notion-enhancer
2. notion-enchancer queries GitHub for a new release
3. If new release is detected, query users if they want notion-enhancer to update

**Comment by dragonwocky** [comment]
Already a feature, the notion-enhancer checks for and will attempt to update to the latest stable release (not including v0.11.1 as it is marked as a pre-release).

**Comment by Mikestriken** [comment]
Thanks, feel free to close this issue.
